"""Fixed, source-bound Common Kernel K1/K2 unittest runner.

The embedded inventory is reviewed configuration. This process runs only inside
runner.py's sandbox; stdout is a bounded, untrusted result frame for the parent.
"""
from __future__ import annotations
import contextlib
import importlib.util
import io
import json
from pathlib import Path
import re
import sys
import unittest

try:
    from .common import Diagnostic, canonical_bytes, sha256
except ImportError:  # pragma: no cover - direct fixed argv entrypoint
    from common import Diagnostic, canonical_bytes, sha256

SUITE_ID = "common-kernel-k1-k2"
CURRENT_DESIGN_PATHS = (
    "docs/helix-harness/L6-function-design/common-kernel.md",
    "docs/helix-harness/L7-unit-test-design/common-kernel-unit-test-design.md",
)
SOURCE_SHA256 = {'helix/helix-harness/units/common-kernel/src/common_kernel.py': 'ce9c7a87cd318c2ff5d12f68c71129f6ad99f0b78616f89c501ccdd2c4643178',
 'helix/helix-harness/units/common-kernel/tests/test_k1.py': 'da847ab19a9c3fa0df17c360bc489c9da2470f53d3ee6487ea0e822905e561ff',
 'helix/helix-harness/units/common-kernel/tests/test_k2.py': '3b1a6ede6642292ef31e458ca519bc293917da5e4654f85eda9ccf4a350d1582'}
FORMAL_MAPPING = ({'callable_qualname': 'K1UnitTests.test_CK_K1_UT_001',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-001',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_001'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_002_ADMIT_INCONSISTENT',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-002-ADMIT-INCONSISTENT',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_002_ADMIT_INCONSISTENT'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_002a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-002a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_002a'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_002b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-002b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_002b'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_002c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-002c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_002c'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_003',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-003',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_003'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_004',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-004',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_004'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_005a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-005a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_005a'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_005b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-005b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_005b'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_006',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-006',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_006'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_007a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-007a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_007a'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_007b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-007b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_007b'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_007c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-007c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_007c'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_008_invalid_not_applicable_is_nonvalue',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-008-INVALID-NA',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_008_invalid_not_applicable_is_nonvalue'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_008a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-008a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_008a'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_008b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-008b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_008b'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_008c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-008c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_008c'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_NotApplicable',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-COMBINE-NotApplicable',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_NotApplicable'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Stale',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-COMBINE-Stale',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Stale'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Unknown',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-COMBINE-Unknown',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Unknown'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Unobserved',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-COMBINE-Unobserved',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Unobserved'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Value',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-COMBINE-Value',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Value'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_NotApplicable',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-RECORD-NotApplicable',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_NotApplicable'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Unknown',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-RECORD-Unknown',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Unknown'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Unobserved',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-RECORD-Unobserved',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Unobserved'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Value',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-ACCEPT-RECORD-Value',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Value'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_NotApplicable',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-KEY-COMBINE-NotApplicable',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_NotApplicable'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Stale',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-KEY-COMBINE-Stale',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Stale'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Unknown',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-KEY-COMBINE-Unknown',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Unknown'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Unobserved',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-KEY-COMBINE-Unobserved',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Unobserved'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Value',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-KEY-COMBINE-Value',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Value'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_KEY_LOOKUP',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-KEY-LOOKUP',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_LOOKUP'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_KEY_RECORD',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-KEY-RECORD',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_RECORD'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_LOOKUP_NotApplicable',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-LOOKUP-NotApplicable',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_LOOKUP_NotApplicable'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_LOOKUP_Unknown',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-LOOKUP-Unknown',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_LOOKUP_Unknown'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_LOOKUP_Unobserved',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-LOOKUP-Unobserved',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_LOOKUP_Unobserved'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_LOOKUP_Value',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-LOOKUP-Value',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_LOOKUP_Value'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_STALE_LOOKUP',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-STALE-LOOKUP',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_STALE_LOOKUP'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_009_STALE_RECORD',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-009-STALE-RECORD',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_009_STALE_RECORD'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_010_COMPLETE',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-010-COMPLETE',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_010_COMPLETE'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_010_PARTIAL',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-010-PARTIAL',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_010_PARTIAL'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_010_READ_FAIL',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-010-READ-FAIL',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_010_READ_FAIL'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_011_projection_cannot_be_combined',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-011',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_011_projection_cannot_be_combined'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_absent',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-absent',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_absent'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_ambiguous',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-ambiguous',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_ambiguous'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_conflict',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-conflict',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_conflict'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_evaluation_error',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-evaluation_error',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_evaluation_error'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_incompatible',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-incompatible',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_incompatible'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_indeterminate',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-indeterminate',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_indeterminate'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_mismatch',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-mismatch',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_mismatch'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_not_applicable',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-not_applicable',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_not_applicable'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_not_observed',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-not_observed',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_not_observed'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_stale',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-stale',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_stale'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_unknown',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-unknown',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_unknown'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_unsupported',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-unsupported',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_unsupported'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_MAP_未評価',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-MAP-未評価',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_未評価'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_unregistered',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-UNREGISTERED',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_unregistered'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_wrong_mapping_incompatible',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-WRONG-INCOMPATIBLE',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_wrong_mapping_incompatible'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_wrong_mapping_mismatch',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-WRONG-MISMATCH',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_wrong_mapping_mismatch'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_012_wrong_mapping_not_observed',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K1-UT-012-WRONG-NOT-OBSERVED',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_012_wrong_mapping_not_observed'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_digest_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.digest-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_digest_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_digest_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.digest-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_digest_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_digest_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.digest-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_digest_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_identity_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.identity-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_identity_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_identity_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.identity-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_identity_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_identity_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.identity-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_identity_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_kind_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.kind-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_kind_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_kind_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.kind-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_kind_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_kind_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.kind-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_kind_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_revision_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.revision-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_revision_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_revision_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.revision-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_revision_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_input_revision_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-input.revision-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_revision_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_inputs_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-inputs-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_inputs_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_inputs_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-inputs-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_inputs_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_inputs_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-inputs-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_inputs_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_operation_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-operation-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_operation_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-operation-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_operation_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-operation-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_operation_version_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-operation_version-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_version_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_operation_version_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-operation_version-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_version_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_operation_version_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-operation_version-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_version_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_scope_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-scope-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_scope_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_scope_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-scope-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_scope_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_scope_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-scope-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_scope_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_digest_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.digest-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_digest_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_digest_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.digest-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_digest_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_digest_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.digest-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_digest_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_identity_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.identity-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_identity_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_identity_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.identity-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_identity_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_identity_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.identity-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_identity_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_kind_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.kind-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_kind_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_kind_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.kind-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_kind_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_kind_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.kind-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_kind_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_revision_combine',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.revision-combine-component',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_revision_combine'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_revision_lookup',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.revision-lookup-query',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_revision_lookup'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_013_subject_revision_record',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-013-subject.revision-record-key',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_revision_record'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_WHOLE',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-WHOLE',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_WHOLE'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_input_digest',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-input.digest',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_input_digest'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_input_identity',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-input.identity',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_input_identity'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_input_kind',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-input.kind',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_input_kind'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_input_revision',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-input.revision',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_input_revision'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_inputs',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-inputs',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_inputs'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_operation',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-operation',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_operation'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_operation_version',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-operation_version',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_operation_version'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_scope',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-scope',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_scope'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_subject',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-subject',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_subject_digest',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-subject.digest',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject_digest'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_subject_identity',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-subject.identity',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject_identity'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_subject_kind',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-subject.kind',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject_kind'},
 {'callable_qualname': 'K1UnitTests.test_CK_K1_UT_014_KEY_subject_revision',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K1-UT-014-KEY-subject.revision',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k1.py',
  'unittest_identity': 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject_revision'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_001_NOT_APPLICABLE',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-001-NOT-APPLICABLE',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_001_NOT_APPLICABLE'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_001_UNKNOWN',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-001-UNKNOWN',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_001_UNKNOWN'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_001_UNOBSERVED',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-001-UNOBSERVED',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_001_UNOBSERVED'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_001_VALUE',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-001-VALUE',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_001_VALUE'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_002a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-002a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_002a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_002b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-002b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_002b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_002c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-002c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_002c'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_002d',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-002d',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_002d'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_003a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-003a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_003a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_003b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-003b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_003b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_003c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-003c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_003c'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_004a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-004a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_004a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_004b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-004b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_004b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_004c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-004c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_004c'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_004d',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-004d',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_004d'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_005_conflict_precedes_stale',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-005',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_005_conflict_precedes_stale'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_006_revision_only_change_is_stale',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-006',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_006_revision_only_change_is_stale'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_007_whitespace_revision_is_stale',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-007',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_007_whitespace_revision_is_stale'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_008a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-008a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_008a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_008b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-008b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_008b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_008c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-008c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_008c'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_009a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-009a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_009a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_009b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-009b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_009b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_010_lookup_does_not_mutate_records',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-010',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_010_lookup_does_not_mutate_records'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_011a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-011a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_011a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_011b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-011b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_011b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_011c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-011c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_011c'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_012_old_revision_is_never_current_value',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-012',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_012_old_revision_is_never_current_value'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_013_GIT_REVISION',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-013-GIT-REVISION',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_013_GIT_REVISION'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_013_NO_PREFIX',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-013-NO-PREFIX',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_013_NO_PREFIX'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_013_PRECEDENCE_DIGEST',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-013-PRECEDENCE-DIGEST',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_013_PRECEDENCE_DIGEST'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_013_PRECEDENCE_MISSING',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-013-PRECEDENCE-MISSING',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_013_PRECEDENCE_MISSING'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_013_SHORT',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-013-SHORT',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_013_SHORT'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_013_UPPERCASE',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-013-UPPERCASE',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_013_UPPERCASE'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_014_layer_versions_stay_independent',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-014',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_014_layer_versions_stay_independent'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_015_DUP',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-015-DUP',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_015_DUP'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_015_ORDER',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-015-ORDER',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_015_ORDER'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_016a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-016a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_016a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_016b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-016b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_016b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_017a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-017a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_017a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_017b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-017b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_017b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_018_OLD_UNKNOWN',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-018-OLD-UNKNOWN',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_018_OLD_UNKNOWN'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_018_OLD_VALUE',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-018-OLD-VALUE',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_018_OLD_VALUE'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_019_exact_plus_same_revision_conflict',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-019',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_019_exact_plus_same_revision_conflict'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_020a',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-020a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_020a'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_020b',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-020b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_020b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_020c',
  'coverage_kind': 'primary_callable',
  'formal_l7_id': 'CK-K2-UT-020c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_020c'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_021_alias_binding_dedup_conflict_and_handoff',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K2-UT-021',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_021_alias_binding_dedup_conflict_and_handoff'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_021a_missing_binding_input',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K2-UT-021a',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_021a_missing_binding_input'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_021b',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K2-UT-021b',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_021b'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_021c',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K2-UT-021c',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_021c'},
 {'callable_qualname': 'K2UnitTests.test_CK_K2_UT_021d_alias_revision_change_stales_lookup',
  'coverage_kind': 'owner_or_fixture_stub',
  'formal_l7_id': 'CK-K2-UT-021d',
  'module_path': 'helix/helix-harness/units/common-kernel/tests/test_k2.py',
  'unittest_identity': 'test_k2.K2UnitTests.test_CK_K2_UT_021d_alias_revision_change_stales_lookup'})
EXPECTED_DISCOVERY_IDS = ('test_k1.K1UnitTests.test_CK_K1_UT_001',
 'test_k1.K1UnitTests.test_CK_K1_UT_002_ADMIT_INCONSISTENT',
 'test_k1.K1UnitTests.test_CK_K1_UT_002a',
 'test_k1.K1UnitTests.test_CK_K1_UT_002b',
 'test_k1.K1UnitTests.test_CK_K1_UT_002c',
 'test_k1.K1UnitTests.test_CK_K1_UT_003',
 'test_k1.K1UnitTests.test_CK_K1_UT_004',
 'test_k1.K1UnitTests.test_CK_K1_UT_005a',
 'test_k1.K1UnitTests.test_CK_K1_UT_005b',
 'test_k1.K1UnitTests.test_CK_K1_UT_006',
 'test_k1.K1UnitTests.test_CK_K1_UT_007a',
 'test_k1.K1UnitTests.test_CK_K1_UT_007b',
 'test_k1.K1UnitTests.test_CK_K1_UT_007c',
 'test_k1.K1UnitTests.test_CK_K1_UT_008_disposition_three_required_fields',
 'test_k1.K1UnitTests.test_CK_K1_UT_008_invalid_not_applicable_is_nonvalue',
 'test_k1.K1UnitTests.test_CK_K1_UT_008a',
 'test_k1.K1UnitTests.test_CK_K1_UT_008b',
 'test_k1.K1UnitTests.test_CK_K1_UT_008c',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_NotApplicable',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Stale',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Unknown',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Unobserved',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_COMBINE_Value',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_NotApplicable',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Unknown',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Unobserved',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_ACCEPT_RECORD_Value',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_NotApplicable',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Stale',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Unknown',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Unobserved',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_COMBINE_Value',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_LOOKUP',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_KEY_RECORD',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_LOOKUP_NotApplicable',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_LOOKUP_Unknown',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_LOOKUP_Unobserved',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_LOOKUP_Value',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_STALE_LOOKUP',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_STALE_RECORD',
 'test_k1.K1UnitTests.test_CK_K1_UT_009_accept_classes_and_record_classes',
 'test_k1.K1UnitTests.test_CK_K1_UT_010_COMPLETE',
 'test_k1.K1UnitTests.test_CK_K1_UT_010_PARTIAL',
 'test_k1.K1UnitTests.test_CK_K1_UT_010_READ_FAIL',
 'test_k1.K1UnitTests.test_CK_K1_UT_011_projection_cannot_be_combined',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_absent',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_ambiguous',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_conflict',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_evaluation_error',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_incompatible',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_indeterminate',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_mismatch',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_not_applicable',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_not_observed',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_stale',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_unknown',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_unsupported',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_MAP_未評価',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_mapping_word_table',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_unregistered',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_wrong_mapping_incompatible',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_wrong_mapping_mismatch',
 'test_k1.K1UnitTests.test_CK_K1_UT_012_wrong_mapping_not_observed',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_digest_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_digest_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_digest_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_identity_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_identity_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_identity_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_kind_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_kind_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_kind_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_revision_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_revision_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_input_revision_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_inputs_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_inputs_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_inputs_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_version_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_version_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_operation_version_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_scope_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_scope_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_scope_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_digest_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_digest_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_digest_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_identity_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_identity_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_identity_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_kind_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_kind_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_kind_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_revision_combine',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_revision_lookup',
 'test_k1.K1UnitTests.test_CK_K1_UT_013_subject_revision_record',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_WHOLE',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_input_digest',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_input_identity',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_input_kind',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_input_revision',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_inputs',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_operation',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_operation_version',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_scope',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject_digest',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject_identity',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject_kind',
 'test_k1.K1UnitTests.test_CK_K1_UT_014_KEY_subject_revision',
 'test_k1.K1UnitTests.test_contract_boundary_value_without_mapping_is_rejected',
 'test_k2.K2UnitTests.test_CK_K2_UT_001_NOT_APPLICABLE',
 'test_k2.K2UnitTests.test_CK_K2_UT_001_UNKNOWN',
 'test_k2.K2UnitTests.test_CK_K2_UT_001_UNOBSERVED',
 'test_k2.K2UnitTests.test_CK_K2_UT_001_VALUE',
 'test_k2.K2UnitTests.test_CK_K2_UT_002_old_value_revision_and_digest_updates',
 'test_k2.K2UnitTests.test_CK_K2_UT_002a',
 'test_k2.K2UnitTests.test_CK_K2_UT_002b',
 'test_k2.K2UnitTests.test_CK_K2_UT_002c',
 'test_k2.K2UnitTests.test_CK_K2_UT_002d',
 'test_k2.K2UnitTests.test_CK_K2_UT_003_old_nonvalues_supersede',
 'test_k2.K2UnitTests.test_CK_K2_UT_003a',
 'test_k2.K2UnitTests.test_CK_K2_UT_003b',
 'test_k2.K2UnitTests.test_CK_K2_UT_003c',
 'test_k2.K2UnitTests.test_CK_K2_UT_004_same_revision_digest_conflict_all_positions',
 'test_k2.K2UnitTests.test_CK_K2_UT_004a',
 'test_k2.K2UnitTests.test_CK_K2_UT_004b',
 'test_k2.K2UnitTests.test_CK_K2_UT_004c',
 'test_k2.K2UnitTests.test_CK_K2_UT_004d',
 'test_k2.K2UnitTests.test_CK_K2_UT_005_conflict_precedes_stale',
 'test_k2.K2UnitTests.test_CK_K2_UT_006_revision_only_change_is_stale',
 'test_k2.K2UnitTests.test_CK_K2_UT_007_whitespace_revision_is_stale',
 'test_k2.K2UnitTests.test_CK_K2_UT_008_operation_version_scope_are_separate_questions',
 'test_k2.K2UnitTests.test_CK_K2_UT_008a',
 'test_k2.K2UnitTests.test_CK_K2_UT_008b',
 'test_k2.K2UnitTests.test_CK_K2_UT_008c',
 'test_k2.K2UnitTests.test_CK_K2_UT_009_identity_set_add_remove',
 'test_k2.K2UnitTests.test_CK_K2_UT_009a',
 'test_k2.K2UnitTests.test_CK_K2_UT_009b',
 'test_k2.K2UnitTests.test_CK_K2_UT_010_lookup_does_not_mutate_records',
 'test_k2.K2UnitTests.test_CK_K2_UT_011_noop_conflict_and_stale_record_priority',
 'test_k2.K2UnitTests.test_CK_K2_UT_011a',
 'test_k2.K2UnitTests.test_CK_K2_UT_011b',
 'test_k2.K2UnitTests.test_CK_K2_UT_011c',
 'test_k2.K2UnitTests.test_CK_K2_UT_012_old_revision_is_never_current_value',
 'test_k2.K2UnitTests.test_CK_K2_UT_013_GIT_REVISION',
 'test_k2.K2UnitTests.test_CK_K2_UT_013_NO_PREFIX',
 'test_k2.K2UnitTests.test_CK_K2_UT_013_PRECEDENCE_DIGEST',
 'test_k2.K2UnitTests.test_CK_K2_UT_013_PRECEDENCE_MISSING',
 'test_k2.K2UnitTests.test_CK_K2_UT_013_SHORT',
 'test_k2.K2UnitTests.test_CK_K2_UT_013_UPPERCASE',
 'test_k2.K2UnitTests.test_CK_K2_UT_013_VALID',
 'test_k2.K2UnitTests.test_CK_K2_UT_013_digest_format_validation_order',
 'test_k2.K2UnitTests.test_CK_K2_UT_014_layer_versions_stay_independent',
 'test_k2.K2UnitTests.test_CK_K2_UT_015_DUP',
 'test_k2.K2UnitTests.test_CK_K2_UT_015_ORDER',
 'test_k2.K2UnitTests.test_CK_K2_UT_015_input_order_and_duplicate_identity',
 'test_k2.K2UnitTests.test_CK_K2_UT_016_kind_mismatch_subject_and_input',
 'test_k2.K2UnitTests.test_CK_K2_UT_016a',
 'test_k2.K2UnitTests.test_CK_K2_UT_016b',
 'test_k2.K2UnitTests.test_CK_K2_UT_017_identity_change_has_no_candidate',
 'test_k2.K2UnitTests.test_CK_K2_UT_017a',
 'test_k2.K2UnitTests.test_CK_K2_UT_017b',
 'test_k2.K2UnitTests.test_CK_K2_UT_018_OLD_UNKNOWN',
 'test_k2.K2UnitTests.test_CK_K2_UT_018_OLD_VALUE',
 'test_k2.K2UnitTests.test_CK_K2_UT_018_exact_match_beats_old_append_position',
 'test_k2.K2UnitTests.test_CK_K2_UT_019_exact_plus_same_revision_conflict',
 'test_k2.K2UnitTests.test_CK_K2_UT_020_last_prior_respects_sequence',
 'test_k2.K2UnitTests.test_CK_K2_UT_020a',
 'test_k2.K2UnitTests.test_CK_K2_UT_020b',
 'test_k2.K2UnitTests.test_CK_K2_UT_020c',
 'test_k2.K2UnitTests.test_CK_K2_UT_021_CROSS_ROLE',
 'test_k2.K2UnitTests.test_CK_K2_UT_021_DEDUP',
 'test_k2.K2UnitTests.test_CK_K2_UT_021_P',
 'test_k2.K2UnitTests.test_CK_K2_UT_021_alias_binding_dedup_conflict_and_handoff',
 'test_k2.K2UnitTests.test_CK_K2_UT_021a_missing_binding_input',
 'test_k2.K2UnitTests.test_CK_K2_UT_021b',
 'test_k2.K2UnitTests.test_CK_K2_UT_021c',
 'test_k2.K2UnitTests.test_CK_K2_UT_021d_alias_revision_change_stales_lookup',
 'test_k2.K2UnitTests.test_CK_K2_UT_030_canonical_json_object_sort',
 'test_k2.K2UnitTests.test_CK_K2_UT_031_array_order',
 'test_k2.K2UnitTests.test_CK_K2_UT_032_finite_float',
 'test_k2.K2UnitTests.test_CK_K2_UT_033_negative_zero',
 'test_k2.K2UnitTests.test_CK_K2_UT_034a_integer',
 'test_k2.K2UnitTests.test_CK_K2_UT_034b_exponent',
 'test_k2.K2UnitTests.test_CK_K2_UT_035a_composed_unicode',
 'test_k2.K2UnitTests.test_CK_K2_UT_035b_decomposed_unicode',
 'test_k2.K2UnitTests.test_CK_K2_UT_036_non_string_key_rejected_by_codec',
 'test_k2.K2UnitTests.test_CK_K2_UT_037_nonfinite_rejected_by_codec',
 'test_k2.K2UnitTests.test_CK_K2_UT_038_cycle_rejected_by_codec',
 'test_k2.K2UnitTests.test_CK_K2_UT_039_lone_surrogate_rejected_by_codec',
 'test_k2.K2UnitTests.test_CK_K2_UT_040_raw_source_digest',
 'test_k2.K2UnitTests.test_CK_K2_UT_041_canonical_bytes_do_not_include_storage_lf')
EXPECTED_DISCOVERY_COUNT = 199
EXPECTED_DISCOVERY_IDS_SHA256 = "2203c7ba4c3064940792d0cd19b8e0e5e6b0123ed0f5ad302472213b1be3c874"
FORMAL_MAPPING_SHA256 = "ca5c7a91e666a13062e6cd22a2bf157f54dad0ce7aa79f3815b70e19c7d11f19"
RESULT_MAX_BYTES = 40000
MODULES = ("test_k1", "test_k2")


def inventory_value() -> dict:
    return {
        "suite_id": SUITE_ID,
        "source_sha256": dict(sorted(SOURCE_SHA256.items())),
        "current_design_paths": list(CURRENT_DESIGN_PATHS),
        "formal_mapping": list(FORMAL_MAPPING),
        "formal_mapping_sha256": FORMAL_MAPPING_SHA256,
        "expected_discovery_ids": list(EXPECTED_DISCOVERY_IDS),
        "expected_discovery_count": EXPECTED_DISCOVERY_COUNT,
        "expected_discovery_ids_sha256": EXPECTED_DISCOVERY_IDS_SHA256,
        "runner_profile": {"implementation": "CPython", "minimum_version": "3.11", "stdlib_module": "unittest"},
    }


def inventory_digest() -> str:
    return sha256(canonical_bytes(inventory_value()))


def l7_formal_ids_present(raw: bytes) -> bool:
    """Resolve each fixed formal ID against a literal or explicit L7 row expansion."""
    try:
        text = raw.decode("utf-8", "strict")
    except UnicodeError:
        return False
    tokens = re.findall(r"`([^`]+)`", text)
    templates = [token for token in tokens
                 if "CK-K" in token and re.search(r"\{(?:CLASS|FIELD|BOUNDARY|WORD)\}", token)]
    for row in FORMAL_MAPPING:
        ident = row["formal_l7_id"]
        if ident in tokens:
            continue
        matched = False
        for template in templates:
            pattern = re.escape(template)
            for variable in ("CLASS", "FIELD", "BOUNDARY", "WORD"):
                pattern = pattern.replace(re.escape("{" + variable + "}"), r"(.+?)")
            if re.fullmatch(pattern, ident):
                matched = True
                break
        if matched:
            continue
        for token in tokens:
            slash = re.fullmatch(r"(.+?)([a-z])/([a-z](?:/[a-z])*)", token)
            if slash:
                expanded = {slash.group(1) + suffix for suffix in (slash.group(2), *slash.group(3).split("/"))}
                if ident in expanded:
                    matched = True
                    break
            ranged = re.fullmatch(r"(.+?)([a-z])–([a-z])", token)
            if ranged:
                expanded = {ranged.group(1) + chr(code)
                            for code in range(ord(ranged.group(2)), ord(ranged.group(3)) + 1)}
                if ident in expanded:
                    matched = True
                    break
        if matched:
            continue
        class_row = "CK-K2-UT-001"
        classes = ("VALUE", "UNKNOWN", "UNOBSERVED", "NOT-APPLICABLE")
        if any(token == class_row for token in tokens) and any(
                ident == class_row + "-" + suffix for suffix in classes):
            matched = True
        if not matched:
            return False
    return True


def _ids(suite):
    for item in suite:
        if isinstance(item, unittest.TestSuite):
            yield from _ids(item)
        else:
            yield item.id()


def _load_fixed_suite(root: Path):
    test_dir = root / "helix/helix-harness/units/common-kernel/tests"
    modules = []
    for module_name in MODULES:
        source = test_dir / (module_name + ".py")
        spec = importlib.util.spec_from_file_location(module_name, source)
        if spec is None or spec.loader is None:
            raise Diagnostic("Unknown", "unreadable", "fixed suite module cannot be loaded")
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)
        modules.append(module)
    loader = unittest.TestLoader()
    suites = [loader.loadTestsFromModule(module) for module in modules]
    combined = unittest.TestSuite(suites)
    return combined


class _IdentityResult(unittest.TextTestResult):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.executed_ids = []
    def startTest(self, test):
        self.executed_ids.append(test.id())
        super().startTest(test)


def _result_payload(discovered, result, exit_code):
    failed_ids = sorted({test.id() for test, _ in result.failures})
    error_ids = sorted({test.id() for test, _ in result.errors})
    skipped_ids = sorted({test.id() for test, _ in result.skipped})
    executed_ids = list(result.executed_ids)
    complete = (result.testsRun == EXPECTED_DISCOVERY_COUNT
                and len(executed_ids) == EXPECTED_DISCOVERY_COUNT
                and len(set(executed_ids)) == EXPECTED_DISCOVERY_COUNT
                and set(executed_ids) == set(discovered))
    state = "success" if complete and exit_code == 0 and not (failed_ids or error_ids or skipped_ids) else "fail"
    return {
        "schema_version": 1, "suite_id": SUITE_ID, "complete": complete,
        "discovered_test_ids": list(discovered), "executed_test_ids": executed_ids,
        "test_count": result.testsRun, "failure_count": len(failed_ids), "failed_ids": failed_ids,
        "error_count": len(error_ids), "error_ids": error_ids,
        "skip_count": len(skipped_ids), "skipped_ids": skipped_ids,
        "exit_code": exit_code, "state": state,
    }


def _run_discovered_suite(suite):
    discovered = sorted(_ids(suite))
    if len(discovered) != len(set(discovered)) or tuple(discovered) != EXPECTED_DISCOVERY_IDS:
        return ({"schema_version": 1, "suite_id": SUITE_ID, "complete": False,
                 "discovered_test_ids": discovered, "executed_test_ids": [],
                 "diagnostic": {"classification": "Unknown", "reason": "conflict"}}, 2)
    stream = io.StringIO()
    runner = unittest.TextTestRunner(stream=stream, resultclass=_IdentityResult, verbosity=0)
    result = runner.run(suite)
    exit_code = 0 if result.wasSuccessful() else 1
    return _result_payload(discovered, result, exit_code), exit_code


def run_suite(root: Path) -> tuple[dict, int]:
    if len(FORMAL_MAPPING) != 165 or len({row["formal_l7_id"] for row in FORMAL_MAPPING}) != 165:
        raise Diagnostic("Unknown", "conflict", "fixed formal mapping inventory is inconsistent")
    if sum(row["coverage_kind"] == "primary_callable" for row in FORMAL_MAPPING) != 139:
        raise Diagnostic("Unknown", "conflict", "fixed primary mapping count is inconsistent")
    if sum(row["coverage_kind"] == "owner_or_fixture_stub" for row in FORMAL_MAPPING) != 26:
        raise Diagnostic("Unknown", "conflict", "fixed owner/stub mapping count is inconsistent")
    if sha256(canonical_bytes(list(FORMAL_MAPPING))) != FORMAL_MAPPING_SHA256:
        raise Diagnostic("Unknown", "conflict", "fixed formal mapping bytes differ from its digest")
    mapping_ids = [row["unittest_identity"] for row in FORMAL_MAPPING]
    if len(set(mapping_ids)) != len(mapping_ids) or not set(mapping_ids) <= set(EXPECTED_DISCOVERY_IDS):
        raise Diagnostic("Unknown", "conflict", "formal mapping identities are not unique members of the fixed discovery set")
    if (len(EXPECTED_DISCOVERY_IDS) != EXPECTED_DISCOVERY_COUNT
            or len(set(EXPECTED_DISCOVERY_IDS)) != EXPECTED_DISCOVERY_COUNT
            or EXPECTED_DISCOVERY_IDS != tuple(sorted(EXPECTED_DISCOVERY_IDS))
            or sha256(("\n".join(EXPECTED_DISCOVERY_IDS) + "\n").encode()) != EXPECTED_DISCOVERY_IDS_SHA256):
        raise Diagnostic("Unknown", "conflict", "fixed expected discovery identity inventory is inconsistent")
    for relative, expected in SOURCE_SHA256.items():
        source = root / relative
        try:
            actual = sha256(source.read_bytes())
        except OSError as exc:
            raise Diagnostic("Unknown", "missing_input", "fixed suite source is unavailable") from exc
        if actual != expected:
            raise Diagnostic("Unknown", "conflict", "fixed suite source bytes differ from inventory")
    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        suite = _load_fixed_suite(root)
        return _run_discovered_suite(suite)


def main(argv=None):
    import argparse
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--suite", choices=(SUITE_ID,), required=True)
    args = parser.parse_args(argv)
    try:
        payload, code = run_suite(Path.cwd())
    except Diagnostic as exc:
        payload, code = {"schema_version": 1, "suite_id": SUITE_ID, "complete": False,
                         "diagnostic": exc.as_dict()}, 2
    encoded = canonical_bytes(payload)
    if len(encoded) > RESULT_MAX_BYTES:
        payload, code = {"schema_version": 1, "suite_id": SUITE_ID, "complete": False,
                         "diagnostic": {"classification": "Unknown", "reason": "conflict"}}, 2
        encoded = canonical_bytes(payload)
    sys.stdout.buffer.write(encoded + b"\n")
    return code


if __name__ == "__main__":
    raise SystemExit(main())
