/**
 * oracle-test-trace baseline (IMP-128、PLAN-REVERSE-41 塊B)。
 *
 * 2026-06-10 スナップショット: test-design 宣言済だが tests/ に ID citation が無い oracle 89 件。
 * 大半は「テスト実在・ID 未記載」(U-ASSETDRIFT/U-CHGIMPACT/U-CODE 等) または正規 defer 済
 * (U-RELGRAPH/U-TOOLADAPTER/U-MCPPROFILE/U-DOCEXPORT の外部ツーリング carry)。
 * forward-citation 規律 (NEW oracle は tests に ID 明記必須) を導入し、既存はこの baseline で
 * 段階 back-fill する (PO option ② 2026-06-10)。**縮小のみ可** — citation を tests に書いたら
 * この list から外す。新規追加で穴を広げない。
 */
export const ORACLE_TEST_TRACE_BASELINE: ReadonlySet<string> = new Set([
  "U-ADAPTER-001",
  "U-ASSETDRIFT-001",
  "U-ASSETDRIFT-002",
  "U-ASSETDRIFT-003",
  "U-ASSETDRIFT-004",
  "U-ASSETDRIFT-005",
  "U-ASSETDRIFT-006",
  "U-CHGIMPACT-001",
  "U-CHGIMPACT-002",
  "U-CHGIMPACT-003",
  "U-CHGIMPACT-004",
  "U-CODE-001",
  "U-CODE-002",
  "U-CODE-003",
  "U-CODE-004",
  "U-CODE-005",
  "U-CODE-006",
  "U-CODE-007",
  "U-CODE-008",
  "U-CODE-009",
  "U-DDDTDD-001",
  "U-DDDTDD-003",
  "U-DDDTDD-004",
  "U-DDDTDD-005",
  "U-DDDTDD-006",
  "U-DDDTDD-007",
  "U-DDDTDD-008",
  "U-DOCEXPORT-001",
  "U-DOCEXPORT-002",
  "U-DOCEXPORT-003",
  "U-DOCEXPORT-004",
  "U-DOCEXPORT-005",
  "U-DOCEXPORT-006",
  "U-DOCEXPORT-007",
  "U-DOCEXPORT-008",
  "U-DOCEXPORT-009",
  "U-DOCEXPORT-010",
  "U-DOCEXPORT-011",
  "U-DOCEXPORT-012",
  "U-FRCOV-001",
  "U-FRCOV-002",
  "U-FRCOV-003",
  "U-FRCOV-004",
  "U-FRCOV-005",
  "U-FRCOV-006",
  "U-GATE-001",
  "U-GATE-002",
  "U-GATE-003",
  "U-GATE-004",
  "U-L6COMP-001",
  "U-L6COMP-002",
  "U-L6COMP-003",
  "U-L6COMP-004",
  "U-L6COMP-005",
  "U-MCPPROFILE-001",
  "U-MCPPROFILE-002",
  "U-MCPPROFILE-003",
  "U-MCPPROFILE-004",
  "U-MCPPROFILE-005",
  "U-MCPPROFILE-006",
  "U-MCPPROFILE-007",
  "U-MCPPROFILE-008",
  "U-MCPPROFILE-009",
  "U-MCPPROFILE-010",
  "U-MCPPROFILE-011",
  "U-MCPPROFILE-012",
  "U-PHOVER-001",
  "U-PHOVER-002",
  "U-RDRIFT-001",
  "U-RDRIFT-002",
  "U-RDRIFT-003",
  "U-RDRIFT-004",
  "U-READ-001",
  "U-READ-002",
  "U-READ-003",
  "U-READ-004",
  "U-SLOG-007",
  "U-TEAMRUN-001",
  "U-TEAMRUN-002",
  "U-TOOLADAPTER-001",
  "U-TOOLADAPTER-002",
  "U-TOOLADAPTER-003",
  "U-TOOLADAPTER-004",
  "U-TOOLADAPTER-005",
  "U-TOOLADAPTER-006",
  "U-TOOLADAPTER-007",
  "U-TOOLADAPTER-008",
  "U-TOOLADAPTER-009",
  "U-TOOLADAPTER-010",
]);

/**
 * Issue #1669: tests の it() にあるが L6/L8 正規登録構造へ未登録の既存 ID。
 * 2026-09-09 one-time 補正: corrected canonical classifier（eligible 表 +
 * U-ID / ID / oracle 列。本文 token mention は登録にしない）で starting main
 * 由来の test corpus を測った exact 547 件。件数だけでなく ID と appearance
 * path provenance を固定する。実行時に現在値へ置き換えない。縮小のみ可。
 * 起点は main 着地済みの U-PRSCOPE-008。
 */
export const ORACLE_UNREGISTERED_BASELINE_CAPTURE = {
  classifier: "corrected-canonical-l6-l8-structures",
  captured: "2026-09-09",
  count: 547,
} as const;

export interface OracleUnregisteredBaselineEntry {
  readonly id: string;
  readonly paths: readonly string[];
}

export const ORACLE_UNREGISTERED_BASELINE_ENTRIES: readonly OracleUnregisteredBaselineEntry[] = [
  {
    id: "IT-DUR-002",
    paths: [
      "tests/autonomous-loop-run-receipts.test.ts",
      "tests/durable-loop-store.test.ts",
      "tests/loop-store-durability-node.test.ts",
    ],
  },
  { id: "IT-DUR-003", paths: ["tests/loop-store-durability-node.test.ts"] },
  { id: "IT-DUR-004", paths: ["tests/loop-store-durability-node.test.ts"] },
  {
    id: "IT-DUR-005",
    paths: ["tests/autonomous-loop-run-receipts.test.ts", "tests/durable-loop-store.test.ts"],
  },
  { id: "IT-DUR-007", paths: ["tests/durable-loop-store.test.ts"] },
  { id: "IT-FLIFE-003", paths: ["tests/feedback-surface.test.ts"] },
  { id: "IT-GITGUARD-007", paths: ["tests/git-command-guard.test.ts"] },
  { id: "IT-HVMA-002", paths: ["tests/closure-authority-backfill-production-route.test.ts"] },
  { id: "IT-UWPROP-001", paths: ["tests/ai-decision-proposal.test.ts"] },
  { id: "IT-UWPROP-002", paths: ["tests/ai-decision-proposal.test.ts"] },
  { id: "IT-UWPROP-003", paths: ["tests/ai-decision-proposal.test.ts"] },
  { id: "U-ADAPTER-005", paths: ["tests/runtime-adapter.test.ts"] },
  { id: "U-ADAPTER-006", paths: ["tests/runtime-adapter.test.ts"] },
  { id: "U-AGENTMODEL-001", paths: ["tests/agent-model-ssot.test.ts"] },
  { id: "U-AGENTMODEL-002", paths: ["tests/agent-model-ssot.test.ts"] },
  { id: "U-AGENTMODEL-003", paths: ["tests/agent-model-ssot.test.ts"] },
  { id: "U-AGFA-001", paths: ["tests/agent-guard.test.ts"] },
  { id: "U-AGFA-002", paths: ["tests/agent-guard.test.ts"] },
  { id: "U-AGFA-003", paths: ["tests/agent-guard.test.ts"] },
  { id: "U-ATOMIC-DESIGN-001", paths: ["tests/atomic-slice-admission-detail-design.test.ts"] },
  { id: "U-ATOMIC-DESIGN-002", paths: ["tests/atomic-slice-admission-detail-design.test.ts"] },
  { id: "U-ATOMIC-DESIGN-003", paths: ["tests/atomic-slice-admission-detail-design.test.ts"] },
  { id: "U-ATOMIC-DESIGN-004", paths: ["tests/atomic-slice-admission-detail-design.test.ts"] },
  { id: "U-ATOMIC-DESIGN-005", paths: ["tests/atomic-slice-admission-detail-design.test.ts"] },
  { id: "U-ATOMIC-DESIGN-006", paths: ["tests/atomic-slice-admission-detail-design.test.ts"] },
  { id: "U-ATOMIC-DESIGN-007", paths: ["tests/atomic-slice-admission-detail-design.test.ts"] },
  { id: "U-AUTH-VERIFY-001", paths: ["tests/development-model-verification-projection.test.ts"] },
  { id: "U-AUTH-VERIFY-002", paths: ["tests/development-model-verification-projection.test.ts"] },
  { id: "U-AUTH-VERIFY-003", paths: ["tests/development-model-verification-projection.test.ts"] },
  { id: "U-AUTH-VERIFY-004", paths: ["tests/development-model-verification-projection.test.ts"] },
  { id: "U-AUTH-VERIFY-005", paths: ["tests/development-model-verification-projection.test.ts"] },
  { id: "U-CAUTO-019", paths: ["tests/closure-auto-approval.test.ts"] },
  { id: "U-CESA-006", paths: ["tests/closure-evidence-semantic-authority.test.ts"] },
  { id: "U-CESA-007", paths: ["tests/closure-evidence-semantic-authority.test.ts"] },
  { id: "U-CESA-010", paths: ["tests/closure-evidence-semantic-authority.test.ts"] },
  { id: "U-CLI-SKILL-DEADLINE-003", paths: ["tests/cli-surface-deadline-contract.test.ts"] },
  { id: "U-CLWI-006a", paths: ["tests/current-location-workflow-identity.test.ts"] },
  { id: "U-CLWI-006b", paths: ["tests/current-location-workflow-identity.test.ts"] },
  { id: "U-CMAT-013", paths: ["tests/closure-evidence-materialization.test.ts"] },
  { id: "U-CNWHOOKBOUND-001", paths: ["tests/project-hook-authority-boundary-design.test.ts"] },
  { id: "U-CNWHOOKBOUND-002", paths: ["tests/project-hook-authority-boundary-design.test.ts"] },
  { id: "U-CNWHOOKBOUND-003", paths: ["tests/project-hook-authority-boundary-design.test.ts"] },
  { id: "U-CNWHOOKBOUND-004", paths: ["tests/project-hook-authority-boundary-design.test.ts"] },
  { id: "U-CNWHOOKBOUND-005", paths: ["tests/project-hook-authority-boundary-design.test.ts"] },
  { id: "U-CNWHOOKBOUND-006", paths: ["tests/project-hook-authority-boundary-design.test.ts"] },
  { id: "U-CNWHOOKBOUND-007", paths: ["tests/project-hook-authority-boundary-design.test.ts"] },
  { id: "U-CNWHOOKBOUND-008", paths: ["tests/project-hook-authority-boundary-design.test.ts"] },
  {
    id: "U-CNWHOOKSCHEMA-DESIGN-001",
    paths: ["tests/project-hook-authority-schema-design.test.ts"],
  },
  {
    id: "U-CNWHOOKSCHEMA-DESIGN-002",
    paths: ["tests/project-hook-authority-schema-design.test.ts"],
  },
  {
    id: "U-CNWHOOKSCHEMA-DESIGN-003",
    paths: ["tests/project-hook-authority-schema-design.test.ts"],
  },
  {
    id: "U-CNWHOOKSCHEMA-DESIGN-004",
    paths: ["tests/project-hook-authority-schema-design.test.ts"],
  },
  {
    id: "U-CNWHOOKSCHEMA-DESIGN-005",
    paths: ["tests/project-hook-authority-schema-design.test.ts"],
  },
  {
    id: "U-CNWHOOKSCHEMA-DESIGN-006",
    paths: ["tests/project-hook-authority-schema-design.test.ts"],
  },
  {
    id: "U-CNWHOOKSCHEMA-DESIGN-007",
    paths: ["tests/project-hook-authority-schema-design.test.ts"],
  },
  { id: "U-CODE-012", paths: ["tests/coding-rules.test.ts"] },
  { id: "U-CODE-013", paths: ["tests/coding-rules.test.ts"] },
  { id: "U-COLUTIL-001", paths: ["tests/collection-utils.test.ts"] },
  { id: "U-CP4-001", paths: ["tests/cycle-p4-verification.test.ts"] },
  { id: "U-CP4-002", paths: ["tests/cycle-p4-verification.test.ts"] },
  { id: "U-CP4-003", paths: ["tests/cycle-p4-verification.test.ts"] },
  { id: "U-CP4-004", paths: ["tests/cycle-p4-verification.test.ts"] },
  { id: "U-CP4-005", paths: ["tests/cycle-p4-verification.test.ts"] },
  { id: "U-CP4-006", paths: ["tests/cycle-p4-verification.test.ts"] },
  { id: "U-CPRCONV-032", paths: ["tests/claude-pr-convergence.test.ts"] },
  { id: "U-CPRCONV-033", paths: ["tests/claude-pr-convergence.test.ts"] },
  { id: "U-CPRCONV-034", paths: ["tests/claude-pr-convergence.test.ts"] },
  { id: "U-CPRCONV-036", paths: ["tests/claude-pr-convergence.test.ts"] },
  { id: "U-CPRCONV-037", paths: ["tests/claude-pr-convergence.test.ts"] },
  { id: "U-CPRCONV-038", paths: ["tests/claude-pr-convergence.test.ts"] },
  { id: "U-CPRCONV-039", paths: ["tests/claude-pr-convergence.test.ts"] },
  { id: "U-CXHOOK-002b", paths: ["tests/codex-hook-adapter.test.ts"] },
  { id: "U-CXHOOK-016", paths: ["tests/codex-hook-adapter.test.ts"] },
  { id: "U-CXHOOK-017", paths: ["tests/codex-hook-adapter.test.ts"] },
  { id: "U-DBWID-002b", paths: ["tests/slow/projection-writer.test.ts"] },
  { id: "U-DDBREG-001", paths: ["tests/drive-db-registration.test.ts"] },
  { id: "U-DDBREG-002", paths: ["tests/drive-db-registration.test.ts"] },
  { id: "U-DDBREG-003", paths: ["tests/drive-db-registration.test.ts"] },
  { id: "U-DDBREG-004", paths: ["tests/drive-db-registration.test.ts"] },
  { id: "U-DDBREG-005", paths: ["tests/drive-db-registration.test.ts"] },
  { id: "U-DDBREG-006", paths: ["tests/drive-db-registration.test.ts"] },
  { id: "U-DDBREG-007", paths: ["tests/drive-db-registration.test.ts"] },
  { id: "U-DDBREG-008", paths: ["tests/drive-db-registration.test.ts"] },
  { id: "U-DEPD-004", paths: ["tests/dependency-drift.test.ts"] },
  { id: "U-DEPD-005", paths: ["tests/dependency-drift.test.ts"] },
  { id: "U-DESC-009", paths: ["tests/descent-obligation.test.ts"] },
  { id: "U-DESC-010", paths: ["tests/descent-obligation.test.ts"] },
  { id: "U-DESC-011", paths: ["tests/descent-obligation.test.ts"] },
  { id: "U-DESC-012", paths: ["tests/descent-obligation.test.ts"] },
  { id: "U-DESC-013", paths: ["tests/descent-obligation.test.ts"] },
  { id: "U-DESC-014", paths: ["tests/descent-obligation.test.ts"] },
  { id: "U-DESIGNCOV-017", paths: ["tests/design-coverage.test.ts"] },
  { id: "U-DESIGNCOV-018", paths: ["tests/design-coverage.test.ts"] },
  { id: "U-DESLANG-006", paths: ["tests/design-language.test.ts"] },
  { id: "U-DESLANG-007", paths: ["tests/design-language.test.ts"] },
  { id: "U-DESLANG-008", paths: ["tests/design-language.test.ts"] },
  { id: "U-DESLANG-009", paths: ["tests/design-language.test.ts"] },
  { id: "U-DESLANG-011", paths: ["tests/design-language.test.ts"] },
  { id: "U-DESLANG-012", paths: ["tests/design-language.test.ts"] },
  { id: "U-DESLANG-018", paths: ["tests/design-language.test.ts"] },
  { id: "U-DIGEST-010", paths: ["tests/digest.test.ts"] },
  { id: "U-DIGEST-011", paths: ["tests/digest.test.ts"] },
  { id: "U-DMP-001", paths: ["tests/drive-model-passage.test.ts"] },
  { id: "U-DMP-002", paths: ["tests/drive-model-passage.test.ts"] },
  { id: "U-DMP-002b", paths: ["tests/drive-model-passage.test.ts"] },
  { id: "U-DMP-003", paths: ["tests/drive-model-passage.test.ts"] },
  { id: "U-DOCCHECKREG-001", paths: ["tests/doctor-check-registry-authority.test.ts"] },
  { id: "U-DOCCHECKREG-002", paths: ["tests/doctor-check-registry-authority.test.ts"] },
  { id: "U-DOCCHECKREG-003", paths: ["tests/doctor-check-registry-authority.test.ts"] },
  { id: "U-DOCCHECKREG-004", paths: ["tests/doctor-check-registry-authority.test.ts"] },
  { id: "U-DOCEXPORT-005b", paths: ["tests/document-export.test.ts"] },
  { id: "U-DOCEXPORT-013", paths: ["tests/document-export.test.ts"] },
  { id: "U-DOCEXPORT-014", paths: ["tests/document-export.test.ts"] },
  { id: "U-DOCEXPORT-015", paths: ["tests/document-export.test.ts"] },
  { id: "U-DRB-012", paths: ["tests/design-reality-binding.test.ts"] },
  { id: "U-DRB-013", paths: ["tests/design-reality-binding.test.ts"] },
  { id: "U-DRB-014", paths: ["tests/design-reality-binding.test.ts"] },
  { id: "U-DRB-020", paths: ["tests/design-reality-binding.test.ts"] },
  { id: "U-DRB-024", paths: ["tests/design-reality-binding.test.ts"] },
  { id: "U-DRTA-001", paths: ["tests/process-drive-route-authority.test.ts"] },
  { id: "U-DRTA-002", paths: ["tests/process-drive-route-authority.test.ts"] },
  { id: "U-DRTA-003", paths: ["tests/process-drive-route-authority.test.ts"] },
  { id: "U-DRTA-004", paths: ["tests/process-drive-route-authority.test.ts"] },
  { id: "U-DRTA-005", paths: ["tests/process-drive-route-authority.test.ts"] },
  { id: "U-DTJ-015b", paths: ["tests/design-template-authority.test.ts"] },
  { id: "U-EDISC-005", paths: ["tests/ddd-tdd-rules.test.ts"] },
  { id: "U-EFFORT-001", paths: ["tests/model-effort.test.ts"] },
  { id: "U-EFFORT-002", paths: ["tests/model-effort.test.ts"] },
  { id: "U-EFFORT-003", paths: ["tests/model-effort.test.ts"] },
  { id: "U-EFFORT-004", paths: ["tests/model-effort.test.ts"] },
  { id: "U-EFFORT-005", paths: ["tests/model-effort.test.ts"] },
  { id: "U-EFFORT-006", paths: ["tests/model-effort.test.ts"] },
  { id: "U-EFFORT-007", paths: ["tests/model-effort.test.ts"] },
  { id: "U-FBLOG-001", paths: ["tests/feedback-log.test.ts"] },
  { id: "U-FBLOG-002", paths: ["tests/feedback-log.test.ts"] },
  { id: "U-FBLOG-003", paths: ["tests/feedback-log.test.ts"] },
  { id: "U-FBLOG-004", paths: ["tests/feedback-log.test.ts"] },
  { id: "U-FBLOG-005", paths: ["tests/feedback-log.test.ts"] },
  { id: "U-FBLOG-006", paths: ["tests/feedback-log.test.ts"] },
  { id: "U-FBLOG-007", paths: ["tests/feedback-log.test.ts"] },
  { id: "U-FBLOG-008", paths: ["tests/feedback-log.test.ts"] },
  { id: "U-FEDC-001", paths: ["tests/frontend-design-coverage.test.ts"] },
  { id: "U-FEDC-002", paths: ["tests/frontend-design-coverage.test.ts"] },
  { id: "U-FEDC-003", paths: ["tests/frontend-design-coverage.test.ts"] },
  { id: "U-FEDC-004", paths: ["tests/frontend-design-coverage.test.ts"] },
  { id: "U-FEDC-005", paths: ["tests/frontend-design-coverage.test.ts"] },
  { id: "U-FEDC-006", paths: ["tests/frontend-design-coverage.test.ts"] },
  { id: "U-FEDC-007", paths: ["tests/frontend-design-coverage.test.ts"] },
  { id: "U-FEDC-008", paths: ["tests/frontend-design-coverage.test.ts"] },
  { id: "U-FRC-001", paths: ["tests/fr-roadmap-coverage.test.ts"] },
  { id: "U-FRC-002", paths: ["tests/fr-roadmap-coverage.test.ts"] },
  { id: "U-FRC-003", paths: ["tests/fr-roadmap-coverage.test.ts"] },
  { id: "U-FRC-003b", paths: ["tests/fr-roadmap-coverage.test.ts"] },
  { id: "U-FRC-004", paths: ["tests/fr-roadmap-coverage.test.ts"] },
  { id: "U-FRC-004b", paths: ["tests/fr-roadmap-coverage.test.ts"] },
  { id: "U-FRC-005", paths: ["tests/fr-roadmap-coverage.test.ts"] },
  { id: "U-FULLSHARD-WF-004", paths: ["tests/harness-check-workflow.test.ts"] },
  { id: "U-FWALK-001", paths: ["tests/file-walk.test.ts"] },
  { id: "U-FWALK-002", paths: ["tests/file-walk.test.ts"] },
  { id: "U-GCONF-001b", paths: ["tests/gate-confirm.test.ts"] },
  { id: "U-GCONF-001c", paths: ["tests/gate-confirm.test.ts"] },
  { id: "U-GCRA-001b", paths: ["tests/github-cross-review-admission.test.ts"] },
  { id: "U-GCRA-001e", paths: ["tests/github-cross-review-admission.test.ts"] },
  { id: "U-GCRA-012a", paths: ["tests/github-cross-review-admission.test.ts"] },
  { id: "U-GCRA-012b", paths: ["tests/github-cross-review-admission.test.ts"] },
  { id: "U-GES-014b", paths: ["tests/goal-evidence-audit.test.ts"] },
  { id: "U-GHWF-001", paths: ["tests/l12-hybrid-recognition.test.ts"] },
  { id: "U-GREENCMD-004", paths: ["tests/green-command-digest.test.ts"] },
  { id: "U-GREENDEF-000", paths: ["tests/review-evidence.test.ts"] },
  { id: "U-GREENDEF-001", paths: ["tests/review-evidence.test.ts"] },
  { id: "U-GREENDEF-002", paths: ["tests/review-evidence.test.ts"] },
  { id: "U-GREENDEF-002b", paths: ["tests/review-evidence.test.ts"] },
  { id: "U-GREENDEF-003", paths: ["tests/review-evidence.test.ts"] },
  { id: "U-GREENDEF-004", paths: ["tests/review-evidence.test.ts"] },
  { id: "U-HKC-001", paths: ["tests/hook-contract.test.ts"] },
  { id: "U-HKC-002", paths: ["tests/hook-contract.test.ts"] },
  { id: "U-HKC-003", paths: ["tests/hook-contract.test.ts"] },
  { id: "U-HOOKQUIET-001", paths: ["tests/cli-surface.test.ts"] },
  { id: "U-HOOKQUIET-002", paths: ["tests/cli-surface.test.ts"] },
  {
    id: "U-ICGRAPH-006",
    paths: [
      "tests/github-issue-closure-graph-adapter.test.ts",
      "tests/issue-closure-graph.test.ts",
    ],
  },
  { id: "U-ICGRAPH-007", paths: ["tests/github-issue-closure-graph-adapter.test.ts"] },
  { id: "U-ICGRAPH-009", paths: ["tests/github-issue-closure-graph-adapter.test.ts"] },
  { id: "U-ICGRAPH-010", paths: ["tests/github-issue-closure-graph-adapter.test.ts"] },
  { id: "U-IMETA-WF-002", paths: ["tests/issue-metadata-audit-workflow.test.ts"] },
  { id: "U-IMPACTCI-000", paths: ["tests/impact-ci.test.ts"] },
  { id: "U-IMPACTCI-CLI-001", paths: ["tests/impact-ci.test.ts"] },
  { id: "U-IMPACTCI-DESIGN-001", paths: ["tests/impact-ci-recovery-detail-design.test.ts"] },
  { id: "U-IMPACTCI-DESIGN-002", paths: ["tests/impact-ci-recovery-detail-design.test.ts"] },
  { id: "U-IMPACTCI-DESIGN-003", paths: ["tests/impact-ci-recovery-detail-design.test.ts"] },
  { id: "U-IMPACTCI-DESIGN-004", paths: ["tests/impact-ci-recovery-detail-design.test.ts"] },
  { id: "U-IMPACTCI-DESIGN-005", paths: ["tests/impact-ci-recovery-detail-design.test.ts"] },
  { id: "U-IMPACTCI-DESIGN-006", paths: ["tests/impact-ci-recovery-detail-design.test.ts"] },
  { id: "U-IPT-001", paths: ["tests/impl-plan-trace.test.ts"] },
  { id: "U-IPT-002", paths: ["tests/impl-plan-trace.test.ts"] },
  { id: "U-IPT-003", paths: ["tests/impl-plan-trace.test.ts"] },
  { id: "U-IPT-004", paths: ["tests/impl-plan-trace.test.ts"] },
  { id: "U-IPT-005", paths: ["tests/impl-plan-trace.test.ts"] },
  { id: "U-ISSUE602-001", paths: ["tests/provider-spawn-buffer.test.ts"] },
  { id: "U-ISSUE602-002", paths: ["tests/provider-spawn-buffer.test.ts"] },
  { id: "U-L3APP-013", paths: ["tests/review-evidence.test.ts"] },
  { id: "U-L3ROUTE-001", paths: ["tests/l3-delivery-route-selection.test.ts"] },
  { id: "U-L3ROUTE-002", paths: ["tests/l3-delivery-route-selection.test.ts"] },
  { id: "U-L3ROUTE-003", paths: ["tests/l3-delivery-route-selection.test.ts"] },
  { id: "U-L3ROUTE-004", paths: ["tests/l3-delivery-route-selection.test.ts"] },
  { id: "U-LLPG-053", paths: ["tests/layer-ledger-canonical-authority.test.ts"] },
  { id: "U-LLPG-054", paths: ["tests/layer-ledger-canonical-authority.test.ts"] },
  { id: "U-LLPG-055", paths: ["tests/layer-ledger-canonical-authority.test.ts"] },
  { id: "U-MDRIFT-006", paths: ["tests/module-drift.test.ts"] },
  { id: "U-MEMC-003b", paths: ["tests/memory-compaction.test.ts"] },
  { id: "U-MEMV2-001a", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-001b", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-002a", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-002b", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-003", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-004a", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-004b", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-005a", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-005b", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-006", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-007a", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-007b", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-008a", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMV2-008b", paths: ["tests/memory/memory-v2.test.ts"] },
  { id: "U-MEMWAKE-REARM-001", paths: ["tests/claude-memory-wake.test.ts"] },
  { id: "U-MEMWAKE-REARM-002", paths: ["tests/claude-memory-wake.test.ts"] },
  { id: "U-MEMWAKE-REARM-003", paths: ["tests/claude-memory-wake.test.ts"] },
  { id: "U-MEMX-001", paths: ["tests/runtime-adapter.test.ts"] },
  { id: "U-MEMX-001b", paths: ["tests/runtime-adapter.test.ts"] },
  { id: "U-MEMX-002", paths: ["tests/runtime-adapter.test.ts"] },
  { id: "U-MEMX-003", paths: ["tests/runtime-adapter.test.ts"] },
  { id: "U-MEMX-004", paths: ["tests/runtime-adapter.test.ts"] },
  { id: "U-MEMX-005", paths: ["tests/runtime-adapter.test.ts"] },
  { id: "U-MODELID-001", paths: ["tests/model-id-ssot.test.ts"] },
  { id: "U-MODELID-002", paths: ["tests/model-id-ssot.test.ts"] },
  { id: "U-MODELID-003", paths: ["tests/model-id-ssot.test.ts"] },
  { id: "U-MODELID-004", paths: ["tests/model-id-ssot.test.ts"] },
  { id: "U-MODELID-005", paths: ["tests/model-id-ssot.test.ts"] },
  { id: "U-MREG-001", paths: ["tests/model-registry.test.ts"] },
  { id: "U-MREG-002", paths: ["tests/model-registry.test.ts"] },
  { id: "U-MREG-003", paths: ["tests/model-registry.test.ts"] },
  { id: "U-MREG-004", paths: ["tests/model-registry.test.ts"] },
  { id: "U-ORCH-007", paths: ["tests/slow/projection-writer.test.ts"] },
  {
    id: "U-OUTSTANDING-014",
    paths: ["tests/completion-decision-packet.test.ts", "tests/slow/doctor.test.ts"],
  },
  { id: "U-OUTSTANDING-015", paths: ["tests/completion-decision-packet.test.ts"] },
  { id: "U-PDESC-010a", paths: ["tests/plan-descent.test.ts"] },
  { id: "U-PHDEPS-001", paths: ["tests/placeholder-deps.test.ts"] },
  { id: "U-PHDEPS-002", paths: ["tests/placeholder-deps.test.ts"] },
  { id: "U-PHDEPS-003", paths: ["tests/placeholder-deps.test.ts"] },
  { id: "U-PHDEPS-004", paths: ["tests/placeholder-deps.test.ts"] },
  { id: "U-PHDEPS-005", paths: ["tests/placeholder-deps.test.ts"] },
  { id: "U-PHDEPS-006", paths: ["tests/placeholder-deps.test.ts"] },
  { id: "U-PHDEPS-007", paths: ["tests/placeholder-deps.test.ts"] },
  { id: "U-PHDEPS-008", paths: ["tests/placeholder-deps.test.ts"] },
  { id: "U-PLAN-855-001", paths: ["tests/frontmatter.test.ts"] },
  { id: "U-PLANBPP-001", paths: ["tests/plan-template-backprop-parity.test.ts"] },
  { id: "U-PLANBPP-002", paths: ["tests/plan-template-backprop-parity.test.ts"] },
  { id: "U-PLANGOV-001", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-001b", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-001c", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-002", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-003", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-004", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-005", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-006", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-007", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-008", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-009", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-010", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011b", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011c", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011d", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011e", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011f", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011g", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011h", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011i", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011j", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011k", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011l", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011m", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-011n", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-012", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-013", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-014", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-015", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-016", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-017", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-018", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-019", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-020", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-021", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-L12-001", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-L12-002", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANGOV-L12-003", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANSCH-007", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANSCH-008", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANSCH-009", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANSCH-010", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PLANSCH-011", paths: ["tests/plan-lint.test.ts"] },
  { id: "U-PRCREATE-381-001", paths: ["tests/github-merge-readiness.test.ts"] },
  { id: "U-PRCREATE-381-003", paths: ["tests/github-merge-readiness.test.ts"] },
  { id: "U-PRCREATE-381-004", paths: ["tests/github-merge-readiness.test.ts"] },
  { id: "U-PRCREATE-381-005", paths: ["tests/github-merge-readiness.test.ts"] },
  { id: "U-PROUTE-003b", paths: ["tests/plan-entry-routing.test.ts"] },
  { id: "U-PRSCOPE-008", paths: ["tests/branch-kind.test.ts"] },
  { id: "U-PRTA-001", paths: ["tests/process-readme-authority.test.ts"] },
  { id: "U-PRTA-002", paths: ["tests/process-readme-authority.test.ts"] },
  { id: "U-PRTA-003", paths: ["tests/process-readme-authority.test.ts"] },
  { id: "U-PRTA-004", paths: ["tests/process-readme-authority.test.ts"] },
  { id: "U-PRTA-005", paths: ["tests/process-readme-authority.test.ts"] },
  { id: "U-PRTA-006", paths: ["tests/process-readme-authority.test.ts"] },
  { id: "U-PSDA-001", paths: ["tests/process-scrum-discovery-authority.test.ts"] },
  { id: "U-PSDA-002", paths: ["tests/process-scrum-discovery-authority.test.ts"] },
  { id: "U-PSDA-003", paths: ["tests/process-scrum-discovery-authority.test.ts"] },
  { id: "U-PSDA-004", paths: ["tests/process-scrum-discovery-authority.test.ts"] },
  { id: "U-PSDA-005", paths: ["tests/process-scrum-discovery-authority.test.ts"] },
  { id: "U-PSPB-011a", paths: ["tests/plan-descent-specific-parent-binding.test.ts"] },
  {
    id: "U-RAC-002b",
    paths: ["tests/requirement-authority.test.ts", "tests/rule-automation-closure.test.ts"],
  },
  { id: "U-RAC-002c", paths: ["tests/requirement-authority.test.ts"] },
  { id: "U-RAC-007", paths: ["tests/requirement-authority.test.ts"] },
  { id: "U-RELGRAPH-006b", paths: ["tests/relation-graph.test.ts"] },
  { id: "U-REPOGUARD-003", paths: ["tests/repo-wide-guard-registry.test.ts"] },
  { id: "U-REPOGUARD-004", paths: ["tests/repo-wide-guard-registry.test.ts"] },
  { id: "U-REPOINFO-001", paths: ["tests/repo-info.test.ts"] },
  { id: "U-REPOINFO-002", paths: ["tests/repo-info.test.ts"] },
  { id: "U-ROADMAP-001", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-002", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-003", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-004", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-005", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-006", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-007", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-008", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-009", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-010", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-011", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-012", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-013", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-014", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-015", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-016", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-017", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-018", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-019", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-020", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-021", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-022", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-023", paths: ["tests/roadmap.test.ts"] },
  { id: "U-ROADMAP-024", paths: ["tests/roadmap.test.ts"] },
  { id: "U-RPORT-001", paths: ["tests/runtime-portability.test.ts"] },
  { id: "U-RPORT-002", paths: ["tests/runtime-portability.test.ts"] },
  { id: "U-RPORT-003", paths: ["tests/runtime-portability.test.ts"] },
  { id: "U-RPORT-004", paths: ["tests/runtime-portability.test.ts"] },
  { id: "U-RPORT-005", paths: ["tests/runtime-portability.test.ts"] },
  { id: "U-RPORT-006", paths: ["tests/runtime-portability.test.ts"] },
  { id: "U-RPORT-007", paths: ["tests/runtime-portability.test.ts"] },
  { id: "U-RRA-005c", paths: ["tests/requirement-refinement-authority.test.ts"] },
  { id: "U-RRTA-001", paths: ["tests/root-readme-typed-authority.test.ts"] },
  { id: "U-RRTA-002", paths: ["tests/root-readme-typed-authority.test.ts"] },
  { id: "U-RRTA-003", paths: ["tests/root-readme-typed-authority.test.ts"] },
  { id: "U-RRTA-004", paths: ["tests/root-readme-typed-authority.test.ts"] },
  { id: "U-RSC-001", paths: ["tests/request-source-retention.test.ts"] },
  { id: "U-RSC-002", paths: ["tests/request-source-retention.test.ts"] },
  { id: "U-SDCD-001", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-002", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-003", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-004", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-005", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-006", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-007", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-008", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-009", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDCD-010", paths: ["tests/sub-doc-catalog-drift.test.ts"] },
  { id: "U-SDSS-001", paths: ["tests/sub-doc-section-structure.test.ts"] },
  { id: "U-SDSS-002", paths: ["tests/sub-doc-section-structure.test.ts"] },
  { id: "U-SDSS-003", paths: ["tests/sub-doc-section-structure.test.ts"] },
  { id: "U-SDSS-004", paths: ["tests/sub-doc-section-structure.test.ts"] },
  { id: "U-SDSS-005", paths: ["tests/sub-doc-section-structure.test.ts"] },
  { id: "U-SDSS-006", paths: ["tests/sub-doc-section-structure.test.ts"] },
  { id: "U-SDSS-007", paths: ["tests/sub-doc-section-structure.test.ts"] },
  { id: "U-SDSS-008", paths: ["tests/sub-doc-section-structure.test.ts"] },
  { id: "U-SETUP-004b", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-004c", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-008", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-014", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-017", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-019", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-020", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-021", paths: ["tests/setup.test.ts"] },
  {
    id: "U-SETUP-022",
    paths: ["tests/doctor.test.ts", "tests/setup.test.ts", "tests/slow/doctor.test.ts"],
  },
  { id: "U-SETUP-023", paths: ["tests/doctor.test.ts", "tests/slow/doctor.test.ts"] },
  {
    id: "U-SETUP-024",
    paths: ["tests/doctor.test.ts", "tests/setup.test.ts", "tests/slow/doctor.test.ts"],
  },
  { id: "U-SETUP-036", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-038", paths: ["tests/setup.test.ts"] },
  { id: "U-SETUP-040", paths: ["tests/consumer-hook-command.test.ts"] },
  { id: "U-SETUP-041", paths: ["tests/consumer-hook-command.test.ts"] },
  { id: "U-SETUP-042", paths: ["tests/consumer-hook-command.test.ts"] },
  { id: "U-SHQUOTE-001", paths: ["tests/shell-quote.test.ts"] },
  { id: "U-SHQUOTE-002", paths: ["tests/shell-quote.test.ts"] },
  { id: "U-SIPF-001", paths: ["tests/screen-impl-pair-freeze.test.ts"] },
  { id: "U-SIPF-002", paths: ["tests/screen-impl-pair-freeze.test.ts"] },
  { id: "U-SIPF-003", paths: ["tests/screen-impl-pair-freeze.test.ts"] },
  { id: "U-SIPF-004", paths: ["tests/screen-impl-pair-freeze.test.ts"] },
  { id: "U-SIPF-005", paths: ["tests/screen-impl-pair-freeze.test.ts"] },
  { id: "U-SIPF-006", paths: ["tests/screen-impl-pair-freeze.test.ts"] },
  { id: "U-SIPF-007", paths: ["tests/screen-impl-pair-freeze.test.ts"] },
  { id: "U-SIPF-008", paths: ["tests/screen-impl-pair-freeze.test.ts"] },
  { id: "U-SKAPP-DESIGN-001", paths: ["tests/development-model-runtime-routing-design.test.ts"] },
  { id: "U-SKAPP-DESIGN-002", paths: ["tests/development-model-runtime-routing-design.test.ts"] },
  { id: "U-SKAPP-DESIGN-003", paths: ["tests/development-model-runtime-routing-design.test.ts"] },
  { id: "U-SKAPP-DESIGN-004", paths: ["tests/development-model-runtime-routing-design.test.ts"] },
  { id: "U-SKAPP-DESIGN-005", paths: ["tests/development-model-runtime-routing-design.test.ts"] },
  { id: "U-SLOG-002b", paths: ["tests/session-log.test.ts"] },
  { id: "U-SLOG-006b", paths: ["tests/session-log.test.ts"] },
  { id: "U-SLOG-007b", paths: ["tests/session-log.test.ts"] },
  { id: "U-SQLBUSY-001", paths: ["tests/sqlite-error.test.ts"] },
  { id: "U-SQLBUSY-002", paths: ["tests/sqlite-error.test.ts"] },
  { id: "U-SRCMAN-001", paths: ["tests/source-package-manifest.test.ts"] },
  { id: "U-SRCMAN-002", paths: ["tests/source-package-manifest.test.ts"] },
  { id: "U-SRCMAN-003", paths: ["tests/source-package-manifest.test.ts"] },
  { id: "U-SRCMAN-004", paths: ["tests/source-package-manifest.test.ts"] },
  { id: "U-SRCMAN-008", paths: ["tests/source-package-manifest.test.ts"] },
  { id: "U-SRCMAN-009", paths: ["tests/source-package-manifest.test.ts"] },
  { id: "U-SSCAN-000", paths: ["tests/secret-scan.test.ts"] },
  { id: "U-SSCAN-001", paths: ["tests/secret-scan.test.ts"] },
  { id: "U-SSCAN-002", paths: ["tests/secret-scan.test.ts"] },
  { id: "U-SSCAN-003", paths: ["tests/secret-scan.test.ts"] },
  { id: "U-SSCAN-004", paths: ["tests/secret-scan.test.ts"] },
  { id: "U-STRUTIL-001", paths: ["tests/string-utils.test.ts"] },
  { id: "U-STRUTIL-002", paths: ["tests/string-utils.test.ts"] },
  { id: "U-TCAN-001", paths: ["tests/tracked-canonical.test.ts"] },
  { id: "U-TCAN-002", paths: ["tests/tracked-canonical.test.ts"] },
  { id: "U-TCAN-003", paths: ["tests/tracked-canonical.test.ts"] },
  { id: "U-TCAN-004", paths: ["tests/tracked-canonical.test.ts"] },
  { id: "U-TCAN-005", paths: ["tests/tracked-canonical.test.ts"] },
  { id: "U-TCAN-006", paths: ["tests/tracked-canonical.test.ts"] },
  { id: "U-TCLOS-001", paths: ["tests/telemetry-closure.test.ts"] },
  { id: "U-TCLOS-002", paths: ["tests/telemetry-closure.test.ts"] },
  { id: "U-TCLOS-002b", paths: ["tests/telemetry-closure.test.ts"] },
  { id: "U-TCLOS-003", paths: ["tests/telemetry-closure.test.ts"] },
  { id: "U-TIER-001", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-002", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-005", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-006", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-007", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-009", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-010", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-011", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-012", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-013", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-014", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TIER-015", paths: ["tests/tier-router.test.ts"] },
  { id: "U-TOOLCONTRACT-001", paths: ["tests/tool-contract.test.ts"] },
  { id: "U-TOOLCONTRACT-002", paths: ["tests/tool-contract.test.ts"] },
  { id: "U-TOOLCONTRACT-003", paths: ["tests/tool-contract.test.ts"] },
  { id: "U-TOOLCONTRACT-005", paths: ["tests/tool-contract.test.ts"] },
  { id: "U-TOOLCONTRACT-006", paths: ["tests/tool-contract.test.ts"] },
  { id: "U-TORDER-006", paths: ["tests/review-evidence.test.ts"] },
  { id: "U-UIL-AUTH-001", paths: ["tests/l3-g3-freeze-packet-v2.test.ts"] },
  { id: "U-UIL-AUTH-002", paths: ["tests/l3-g3-freeze-packet-v2.test.ts"] },
  { id: "U-UIL-AUTH-003", paths: ["tests/l3-g3-freeze-packet-v2.test.ts"] },
  { id: "U-UIL-AUTH-004", paths: ["tests/l3-g3-freeze-packet-v2.test.ts"] },
  {
    id: "U-UWJBOUND-001",
    paths: ["tests/workflow-switch-route-allocation-boundary-design.test.ts"],
  },
  {
    id: "U-UWJBOUND-002",
    paths: ["tests/workflow-switch-route-allocation-boundary-design.test.ts"],
  },
  {
    id: "U-UWJBOUND-003",
    paths: ["tests/workflow-switch-route-allocation-boundary-design.test.ts"],
  },
  {
    id: "U-UWJBOUND-004",
    paths: ["tests/workflow-switch-route-allocation-boundary-design.test.ts"],
  },
  {
    id: "U-UWJBOUND-005",
    paths: ["tests/workflow-switch-route-allocation-boundary-design.test.ts"],
  },
  {
    id: "U-UWJBOUND-006",
    paths: ["tests/workflow-switch-route-allocation-boundary-design.test.ts"],
  },
  {
    id: "U-UWJBOUND-007",
    paths: ["tests/workflow-switch-route-allocation-boundary-design.test.ts"],
  },
  {
    id: "U-UWJSCHEMA-DESIGN-001",
    paths: ["tests/workflow-switch-route-allocation-schema-design.test.ts"],
  },
  {
    id: "U-UWJSCHEMA-DESIGN-002",
    paths: ["tests/workflow-switch-route-allocation-schema-design.test.ts"],
  },
  {
    id: "U-UWJSCHEMA-DESIGN-003",
    paths: ["tests/workflow-switch-route-allocation-schema-design.test.ts"],
  },
  {
    id: "U-UWJSCHEMA-DESIGN-004",
    paths: ["tests/workflow-switch-route-allocation-schema-design.test.ts"],
  },
  {
    id: "U-UWJSCHEMA-DESIGN-005",
    paths: ["tests/workflow-switch-route-allocation-schema-design.test.ts"],
  },
  {
    id: "U-UWJSCHEMA-DESIGN-006",
    paths: ["tests/workflow-switch-route-allocation-schema-design.test.ts"],
  },
  { id: "U-VEXT-001", paths: ["tests/vscode-extension-adapter.test.ts"] },
  { id: "U-VEXT-002", paths: ["tests/vscode-extension-adapter.test.ts"] },
  { id: "U-VEXT-003", paths: ["tests/vscode-extension-adapter.test.ts"] },
  { id: "U-VEXT-004", paths: ["tests/vscode-extension-adapter.test.ts"] },
  { id: "U-VEXT-005", paths: ["tests/vscode-extension-adapter.test.ts"] },
  { id: "U-VEXT-006", paths: ["tests/vscode-extension-adapter.test.ts"] },
  { id: "U-VEXT-007", paths: ["tests/vscode-extension-adapter.test.ts"] },
  { id: "U-VPAIR-003b", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-004b", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-004c", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-004d", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005b", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005c", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005d", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005e", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005f", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005g", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005h", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005i", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005j", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005k", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005l", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005m", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005n", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-005o", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-007a", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-007b", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-007c", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-007d", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-007e", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-007f", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-008b", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-008c", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-008d", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-008e", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-009a", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-009b", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-009c", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-009d", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-009e", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-009f", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-009g", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VPAIR-009h", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VTREE-001", paths: ["tests/visualization-treeview.test.ts"] },
  { id: "U-VTREE-002", paths: ["tests/visualization-treeview.test.ts"] },
  { id: "U-VTREE-002a", paths: ["tests/visualization-treeview.test.ts"] },
  { id: "U-VTREE-003", paths: ["tests/visualization-treeview.test.ts"] },
  { id: "U-VTREE-004", paths: ["tests/visualization-treeview.test.ts"] },
  { id: "U-VTREE-005", paths: ["tests/visualization-treeview.test.ts"] },
  { id: "U-VTRIG-006", paths: ["tests/vmodel-pair.test.ts"] },
  { id: "U-VVM-001", paths: ["tests/visualization-view-model.test.ts"] },
  { id: "U-VVM-002", paths: ["tests/visualization-view-model.test.ts"] },
  { id: "U-VVM-003", paths: ["tests/visualization-view-model.test.ts"] },
  { id: "U-VVM-004", paths: ["tests/visualization-view-model.test.ts"] },
  { id: "U-VVM-005", paths: ["tests/visualization-view-model.test.ts"] },
  { id: "U-VVM-006", paths: ["tests/visualization-view-model.test.ts"] },
  { id: "U-VVM-007", paths: ["tests/visualization-view-model.test.ts"] },
  { id: "U-WCC-FR01-001", paths: ["tests/wcc-fr-01-descriptor-binding.test.ts"] },
  { id: "U-WCC-PAIR-001", paths: ["tests/wcc-trace.test.ts"] },
  { id: "U-WGR-046", paths: ["tests/work-graph-receipt-acceptance.test.ts"] },
  { id: "U-WIB-017", paths: ["tests/worker-isolation-broker.test.ts"] },
  { id: "U-WMPA-001", paths: ["tests/process-workflow-model-authority.test.ts"] },
  { id: "U-WMPA-002", paths: ["tests/process-workflow-model-authority.test.ts"] },
  { id: "U-WMPA-003", paths: ["tests/process-workflow-model-authority.test.ts"] },
  { id: "U-WMPA-004", paths: ["tests/process-workflow-model-authority.test.ts"] },
  { id: "U-WMPA-005", paths: ["tests/process-workflow-model-authority.test.ts"] },
  { id: "U-WWA-DESIGN-001", paths: ["tests/worker-wrapper-admission-design.test.ts"] },
  { id: "U-WWA-DESIGN-002", paths: ["tests/worker-wrapper-admission-design.test.ts"] },
  { id: "U-WWA-DESIGN-003", paths: ["tests/worker-wrapper-admission-design.test.ts"] },
  { id: "U-WWA-DESIGN-004", paths: ["tests/worker-wrapper-admission-design.test.ts"] },
  { id: "U-WWA-DESIGN-005", paths: ["tests/worker-wrapper-admission-design.test.ts"] },
  { id: "U-XREVIEW-006", paths: ["tests/review-evidence.test.ts"] },
];

export const ORACLE_UNREGISTERED_BASELINE: ReadonlySet<string> = new Set(
  ORACLE_UNREGISTERED_BASELINE_ENTRIES.map((entry) => entry.id),
);

/**
 * Issue #1669: L8 citation / PLAN verification_bindings / fast-slow pair /
 * freeze 伝播 / doctor lane で説明できない既存の多重出現。縮小のみ可。
 */
export const ORACLE_UNDECLARED_MULTI_BASELINE: ReadonlySet<string> = new Set([
  "IT-DUR-002",
  "IT-DUR-005",
  "IT-SBOUND-007",
  "U-CMAT-006",
  "U-CMAT-011",
  "U-CMAT-012",
  "U-DECISIONREC-004",
  "U-DUR-007",
  "U-HRET-007",
  "U-HRET-008",
  "U-HRET-009",
  "U-HRET-010",
  "U-HRET-015",
  "U-ICGRAPH-006",
  "U-OUTSTANDING-011",
  "U-PRSCOPE-007",
  "U-PSPB-013",
  "U-PSPB-027",
  "U-RAC-001",
  "U-RAC-002",
  "U-RAC-002b",
  "U-RAC-003",
  "U-SBOUND-001",
  "U-SBOUND-002",
  "U-SBOUND-003",
  "U-SBOUND-004",
  "U-SBOUND-005",
  "U-SBOUND-006",
  "U-SBOUND-007",
  "U-SBOUND-008",
  "U-SBOUND-009",
  "U-SBOUND-010",
]);
