import { VERIFICATION_SOURCE_LEDGER_CHECKED_AT } from "./right-arm-verification-strategy";
import type {
  VerificationProfile,
  VerificationProfileId,
  VerificationSignal,
} from "./verification-profile-types";

export const PROFILES: Record<VerificationProfileId, VerificationProfile> = {
  "node-unit": {
    id: "node-unit",
    label: "Node/Vitest local regression",
    command: "npm run test:local",
    sourceType: "builtin",
    packageName: null,
    executable: "node",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: true,
    riskTier: "low",
    installHint: null,
  },
  doctor: {
    id: "doctor",
    label: "HELIX doctor hard gate",
    command: "npx --no-install tsx src/cli.ts doctor",
    sourceType: "builtin",
    packageName: null,
    executable: "node",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: true,
    riskTier: "low",
    installHint: null,
    recommendedGates: ["G12", "G13", "G14"],
    sourceLedgerSources: ["NIST SSDF SP 800-218", "Google SRE Release Engineering"],
    sourceLedgerCheckedAt: VERIFICATION_SOURCE_LEDGER_CHECKED_AT,
  },
  "mcp-inspector-smoke": {
    id: "mcp-inspector-smoke",
    label: "MCP Inspector tools/list smoke",
    command: "helix mcp inspect <name> --method tools/list",
    sourceType: "mcp",
    packageName: "@modelcontextprotocol/inspector",
    executable: "node",
    authEnv: [],
    requiresNetwork: true,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "medium",
    installHint: "npm install -D @modelcontextprotocol/inspector",
    sourceUrl: "https://github.com/modelcontextprotocol/inspector",
    sourceLedgerSources: ["NIST SSDF SP 800-218"],
    sourceLedgerCheckedAt: VERIFICATION_SOURCE_LEDGER_CHECKED_AT,
    triggerSignals: ["mcp_profile_changed"],
    recommendedGates: ["G8", "G9"],
    recommendedDrives: ["agent", "fullstack"],
    allowedTools: ["tools/list"],
    readOnly: true,
  },
  "playwright-mcp": {
    id: "playwright-mcp",
    label: "Playwright MCP agentic browser check",
    command: "helix verify run --profile playwright-mcp",
    sourceType: "mcp",
    packageName: "@playwright/mcp",
    executable: "node",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "medium",
    installHint: "npm install -D @playwright/mcp",
    sourceUrl: "https://github.com/microsoft/playwright-mcp",
    sourceLedgerSources: ["Playwright Test", "W3C WCAG 2.2"],
    sourceLedgerCheckedAt: VERIFICATION_SOURCE_LEDGER_CHECKED_AT,
    triggerSignals: ["ui_flow", "mcp_profile_changed"],
    recommendedGates: ["G10", "G11"],
    recommendedDrives: ["fe", "fullstack", "agent"],
    allowedTools: ["browser_navigate", "browser_snapshot", "browser_click"],
    readOnly: false,
  },
  "docker-mcp-toolkit": {
    id: "docker-mcp-toolkit",
    label: "Docker MCP Toolkit isolated server profile",
    command: "helix mcp inspect docker-mcp-toolkit --method tools/list",
    sourceType: "mcp",
    packageName: "docker-mcp-toolkit",
    executable: "docker",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: true,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "high",
    installHint: "Install Docker MCP Toolkit through Docker Desktop after human approval.",
    sourceUrl: "https://docs.docker.com/ai/mcp-catalog-and-toolkit/toolkit/",
    sourceLedgerSources: ["NIST SSDF SP 800-218"],
    sourceLedgerCheckedAt: VERIFICATION_SOURCE_LEDGER_CHECKED_AT,
    triggerSignals: ["db_integration", "mcp_profile_changed"],
    recommendedGates: ["G8", "G9"],
    recommendedDrives: ["be", "db", "fullstack", "agent"],
    optional: true,
    profileIsolation: "docker-desktop-mcp-toolkit",
    allowedTools: ["tools/list"],
    readOnly: false,
    requiresHumanApproval: true,
  },
  "vitest-browser-playwright": {
    id: "vitest-browser-playwright",
    label: "Vitest Browser Mode with Playwright provider",
    command: "npm test -- --browser",
    sourceType: "test-foundation",
    packageName: "@vitest/browser-playwright",
    executable: "node",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "low",
    installHint: "npm install -D @vitest/browser-playwright",
    sourceUrl: "https://vitest.dev/guide/browser/",
    sourceLedgerSources: ["Playwright Test", "W3C WCAG 2.2"],
    sourceLedgerCheckedAt: VERIFICATION_SOURCE_LEDGER_CHECKED_AT,
    triggerSignals: ["ui_flow"],
    recommendedGates: ["G10", "G11"],
    recommendedDrives: ["fe", "fullstack", "agent"],
  },
  "github-mcp-readonly": {
    id: "github-mcp-readonly",
    label: "GitHub MCP read-only issue/PR/CI context",
    command: "helix verify run --profile github-mcp-readonly",
    sourceType: "mcp",
    packageName: "github-mcp-server",
    executable: null,
    authEnv: ["GITHUB_TOKEN", "GH_TOKEN", "GITHUB_PERSONAL_ACCESS_TOKEN"],
    requiresNetwork: true,
    requiresDocker: false,
    requiresAuth: true,
    defaultEnabled: false,
    riskTier: "medium",
    installHint: "Install github/github-mcp-server and configure read-only toolsets.",
    sourceUrl: "https://github.com/github/github-mcp-server",
    sourceLedgerSources: [
      "GitHub Environments required reviewers",
      "Google SRE Release Engineering",
    ],
    sourceLedgerCheckedAt: VERIFICATION_SOURCE_LEDGER_CHECKED_AT,
    triggerSignals: ["external_issue", "workflow_policy"],
    recommendedGates: ["G12", "G13", "G14"],
    recommendedDrives: ["be", "fe", "fullstack", "db", "agent"],
    allowedTools: ["issues:read", "pull_requests:read", "actions:read"],
    readOnly: true,
    requiresHumanApproval: true,
  },
  testcontainers: {
    id: "testcontainers",
    label: "Testcontainers integration dependency check",
    command: "helix verify run --profile testcontainers",
    sourceType: "test-foundation",
    packageName: "testcontainers",
    executable: "docker",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: true,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "medium",
    installHint: "npm install -D testcontainers",
    sourceUrl: "https://node.testcontainers.org/",
    sourceLedgerSources: ["NIST SSDF SP 800-218"],
    sourceLedgerCheckedAt: VERIFICATION_SOURCE_LEDGER_CHECKED_AT,
    triggerSignals: ["db_integration"],
    recommendedGates: ["G8", "G9"],
    recommendedDrives: ["be", "db", "fullstack"],
  },
  msw: {
    id: "msw",
    label: "MSW API mock contract check",
    command: "helix verify run --profile msw",
    sourceType: "test-foundation",
    packageName: "msw",
    executable: null,
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "low",
    installHint: "npm install -D msw",
    sourceUrl: "https://mswjs.io/",
    sourceLedgerSources: ["NIST SSDF SP 800-218"],
    sourceLedgerCheckedAt: VERIFICATION_SOURCE_LEDGER_CHECKED_AT,
    triggerSignals: ["api_mock_gap"],
    recommendedGates: ["G8", "G9", "G12"],
    recommendedDrives: ["be", "fullstack", "agent"],
  },
};

// runner は固定 allowlist (ユーザー入力をコマンドへ連結しない)。readonly で実行時の動的追加を型で禁止し、
// 将来エントリを足すときは A-125 safety boundary (allow-list review) を経由する (A-128 F-4 / IMP-130(c))。
export const PROFILE_RUNNERS: Partial<
  Record<VerificationProfileId, readonly [string, readonly string[]]>
> = {
  "node-unit": ["npm", ["run", "test:local"]] as const,
  doctor: ["npx", ["--no-install", "tsx", "src/cli.ts", "doctor"]] as const,
  "vitest-browser-playwright": ["npm", ["test", "--", "--browser"]] as const,
};

export const SIGNAL_TO_PROFILE: Record<VerificationSignal, VerificationProfileId[]> = {
  source_change: ["node-unit", "doctor"],
  ui_flow: ["vitest-browser-playwright", "playwright-mcp"],
  db_integration: ["testcontainers"],
  api_mock_gap: ["msw"],
  mcp_profile_changed: ["mcp-inspector-smoke"],
  external_issue: ["github-mcp-readonly"],
  workflow_policy: ["doctor"],
  doc_backprop: ["doctor"],
};
