import { existsSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  analyzeCompletionDecisionPacket,
  completionDecisionPacketMessages,
  loadCompletionDecisionPacketInput,
} from "../src/lint/completion-decision-packet";
import {
  analyzeOutstandingWork,
  type CompletionDecisionPacket,
  completionDecisionPacketForOutstanding,
} from "../src/lint/outstanding";

function basePacket(): CompletionDecisionPacket {
  return completionDecisionPacketForOutstanding(
    analyzeOutstandingWork(
      [
        {
          planId: "PLAN-S3",
          layer: "cross",
          kind: "poc",
          status: "draft",
          workflowPhase: "S3",
          text: "S4 decision pending.",
        },
      ],
      0,
    ),
    {
      generatedAt: "2026-06-30T00:00:00.000Z",
      now: "2026-06-30T00:30:00.000Z",
      validForMinutes: 60,
      sourceCommand: "ut-tdd completion decision-packet --json",
    },
  );
}

describe("completion decision packet lint", () => {
  // U-OUTSTANDING-002
  it("accepts a fresh packet with source command and matching freshness metadata", () => {
    const result = analyzeCompletionDecisionPacket(basePacket(), "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(true);
    expect(result.violations).toEqual([]);
    expect(completionDecisionPacketMessages(result)[0]).toContain(
      "completion-decision-packet - OK",
    );
  });

  it("rejects stale packets after the freshness window", () => {
    const result = analyzeCompletionDecisionPacket(basePacket(), "2026-06-30T01:00:00.001Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("stale_packet");
  });

  it("rejects missing or unknown source commands", () => {
    const packet = { ...basePacket(), sourceCommand: "copied-from-chat" };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("invalid_source_command");
  });

  it("accepts packets generated by handover CURRENT.json", () => {
    const packet = { ...basePacket(), sourceCommand: "ut-tdd handover" };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(true);
    expect(result.sourceCommand).toBe("ut-tdd handover");
  });

  it("rejects freshness metadata that does not match generatedAt/window", () => {
    const packet = {
      ...basePacket(),
      freshness: {
        ...basePacket().freshness,
        expiresAt: "2026-06-30T03:00:00.000Z",
      },
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("invalid_expires_at");
  });

  it("rejects decisionCount drift from the decisions array", () => {
    const packet = { ...basePacket(), decisionCount: 99 };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("decision_count_mismatch");
  });

  it("rejects decisions without structured required records", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        requiredRecords: [],
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("missing_required_records");
  });

  it("rejects required records without fields or source paths", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        requiredRecords: [
          {
            recordName: "s4_decision_record",
            fields: [],
            sourcePaths: [],
          },
        ],
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("invalid_required_record");
  });

  // U-OUTSTANDING-006
  it("rejects required record source paths that are not repo-relative", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        requiredRecords: decision.requiredRecords.map((record) => ({
          ...record,
          sourcePaths: ["/tmp/not-a-repo-source.md"],
        })),
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("invalid_required_record_source_path");
  });

  // U-OUTSTANDING-006
  it("rejects missing required record source paths when repo existence is checked", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        requiredRecords: decision.requiredRecords.map((record) => ({
          ...record,
          sourcePaths: ["docs/process/modes/missing-source.md"],
        })),
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z", {
      sourcePathExists: () => false,
    });

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("invalid_required_record_source_path");
  });

  // U-OUTSTANDING-005
  it("rejects decisions whose required records lack record templates", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        recordTemplates: [],
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("missing_record_templates");
  });

  // U-OUTSTANDING-005
  it("rejects record templates that do not cover every required field", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        recordTemplates: [
          {
            recordName: "s4_decision_record",
            insertionHint: "Add this block before S4 decision.",
            yamlLines: ["s4_decision_record:", '  - allowed_outcome: "<confirmed|rejected|pivot>"'],
          },
        ],
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("invalid_record_template");
    expect(result.violations.map((v) => v.detail).join("\n")).toContain(
      "template missing field=decision_owner",
    );
  });

  it("U-OUTSTANDING-007: rejects record templates that cover fields but omit workflow semantic guidance", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        recordTemplates: decision.requiredRecords.map((record) => ({
          recordName: record.recordName,
          insertionHint: "Add this block before S4 decision.",
          yamlLines: [
            `${record.recordName}:`,
            ...record.fields.map((field) => `  - ${field}: "<${field}>"`),
          ],
        })),
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations).toContainEqual({
      reason: "invalid_record_template",
      detail: "decision[0] s4_decision_record template missing guidance=confirmed",
    });
  });

  it("rejects decisions whose required records lack record-level allowed outcomes", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        allowedOutcomesByRecord: [],
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("missing_allowed_outcomes_by_record");
  });

  it("rejects decisions when record-level allowed outcomes do not cover required records", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        allowedOutcomesByRecord: [
          {
            recordName: "other_record",
            allowedOutcomes: ["record_decision"],
          },
        ],
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("invalid_allowed_outcomes_by_record");
  });

  it("rejects decisions whose required records lack record-level workflow routes", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        nextWorkflowRoutesByRecord: [],
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("missing_next_routes_by_record");
  });

  it("rejects decisions when record-level workflow routes do not cover required records", () => {
    const packet = {
      ...basePacket(),
      decisions: basePacket().decisions.map((decision) => ({
        ...decision,
        nextWorkflowRoutesByRecord: [
          {
            recordName: "other_record",
            nextWorkflowRoute: "other route",
          },
        ],
      })),
    };
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T00:30:00.000Z");

    expect(result.ok).toBe(false);
    expect(result.violations.map((v) => v.reason)).toContain("invalid_next_routes_by_record");
  });

  // U-OUTSTANDING-003
  // U-OUTSTANDING-006
  it("loads the current repo packet as fresh doctor input", () => {
    const packet = loadCompletionDecisionPacketInput(process.cwd(), "2026-06-30T03:00:00.000Z");
    const result = analyzeCompletionDecisionPacket(packet, "2026-06-30T03:00:00.000Z", {
      sourcePathExists: (sourcePath) => existsSync(join(process.cwd(), sourcePath)),
    });

    expect(result.ok).toBe(true);
    expect(result.sourceCommand).toBe("ut-tdd completion decision-packet --json");
    expect(result.validForMinutes).toBe(1440);
  });
});
