#!/usr/bin/env python3
"""Wave16 schema10 full static verifier; archive assets are read, never executed."""
from pathlib import Path
import hashlib,json,re,subprocess,sys
R=Path(__file__).resolve().parents[3]; G=R/'docs/governance'; A=G/'audits/source-rebaseline'; AR=R/'archive/legacy-generation-2026-09-14/root'
REV='6dad906ed9a52c9e49611931645db2f298c6bf6a'; BATCH='LEGACY-SEMANTIC-WAVE16-2026-09-21'
L=G/'legacy-requirement-direct-semantic-review-wave16.jsonl'; M=G/'legacy-requirement-direct-semantic-review-wave16.meta.json'; STATUS=A/'legacy-requirement-direct-semantic-review-wave16-status-2026-09-21.md'; METHOD=A/'legacy-requirement-direct-semantic-review-wave16-method-2026-09-21.md'; PREMISE=A/'legacy-requirement-direct-semantic-review-wave16-premise-packet-2026-09-21.md'; RESPONSE=A/'legacy-requirement-direct-semantic-review-wave16-review-response-2026-09-21.md'
CAT=G/'legacy-asset-phase-product-classification-bootstrap.jsonl'; CROSS=G/'legacy-requirement-implementation-crosswalk-bootstrap.jsonl'; DECOMP=G/'legacy-ir-product-unit-decomposition-bootstrap.jsonl'; PHASE=G/'phase-capability-inventory.json'; MAN=R/'archive/legacy-generation-2026-09-14/MANIFEST.sha256'; PRIOR=[(G/f'legacy-requirement-direct-semantic-review-wave{n}.jsonl',G/f'legacy-requirement-direct-semantic-review-wave{n}.meta.json') for n in range(1,16)]
def atom(i,k,s,t,f,shared=()):
 fragments=list(f) if isinstance(f,(list,tuple)) else [f]
 return {'atom_id':i,'boundary_review_state':'product_boundary_pending_human_decision','kind':k,'responsibility_role':ROLE[k],'shared_with_units':list(shared),'source_fragments':fragments,'subject':s,'text':t}
ROLE={
'shared_intake_normalization':'shared intake contract normalization','style_activation_reconnection':'development style/case-driven activation/specialist reconnection','current_ref_authority':'current advertised ref authority','atomic_behavior_complete_decomposition':'atomic behavior complete decomposition','decision_traceability':'admission to requirement/design/test/Gate trace','aggregate_only_rejection':'aggregate/source/read-only is not adopted','authority_derived_denominator':'authority receipt-derived denominator','observation_count_nonbinding':'observation count not requirement'}
U={
'IRUNIT-HIL-BR-12-HELIX-HARNESS':{'product':'HELIX-HARNESS','product_scope':['HELIX-HARNESS'],'product_target':'HELIX-HARNESS','phases':['PHCAP-03'],'shared_peer':'IRUNIT-HIL-BR-12-HELIX-OS','shared_overlap_mode':'decomposition_only','atoms':[atom('BR12-HARNESS-A01','shared_intake_normalization','shared intake normalization','同じintake契約へ正規化し',['同じintake契約へ正規化し'],['IRUNIT-HIL-BR-12-HELIX-OS']),atom('BR12-HARNESS-A02','style_activation_reconnection','style activation and specialist reconnection','development style、case-driven activation、specialist capability、style再接続点を決定する','development style、case-driven activation、specialist capability、style再接続点を決定する')],'connective':['、','。'],'anchors':['intake','development','case','specialist','reconnect'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(475,517)],['BR12-HARNESS-A01','BR12-HARNESS-A02'],'requirement_role_phase_nonintersection_explicit'),'design':('LEGACY-ASSET-3B336ED418F22DB3745A','design','unresolved','design_contract_evidence',[(42,50)],['BR12-HARNESS-A01'],'product_candidate_phase_unresolved'),'implementation':('LEGACY-ASSET-412ED61BCBBD6ACCC3C1','implementation_source','unresolved','partial_implementation_behavior_evidence_unexecuted',[(1,61)],['BR12-HARNESS-A02'],'classification_conflict_phase_product_nonintersection')}},
'IRUNIT-HIL-BR-14-HELIX-HARNESS':{'product':'HELIX-HARNESS','product_scope':['HELIX-HARNESS'],'product_target':'HELIX-HARNESS','phases':['PHCAP-03','PHCAP-04','PHCAP-06','PHCAP-07'],'shared_peer':None,'shared_overlap_mode':'none','atoms':[atom('BR14-HARNESS-A01','current_ref_authority','current advertised ref authority','current advertised ref authority',['ZIP、前身repository exact 2件（`unison-ai-product/UT-TDD_AGENT-HARNESS`、`RetryYN/ai-dev-kit-vscode`）','のcurrent advertised `heads/tags/pull` ref authority']),atom('BR14-HARNESS-A02','atomic_behavior_complete_decomposition','atomic behavior complete decomposition','現行HELIXのsourceをatomic behavior単位へ完全分解し','現行HELIXのsourceをatomic behavior単位へ完全分解し'),atom('BR14-HARNESS-A03','decision_traceability','decision traceability','各項目を採否判断から要件・設計・テスト・Gateまで追跡する','各項目を採否判断から要件・設計・テスト・Gateまで追跡する')],'connective':['、','。'],'anchors':['authority','atomic','admission','decision','Gate'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(561,602)],['BR14-HARNESS-A01','BR14-HARNESS-A02','BR14-HARNESS-A03'],'requirement_role_phase_nonintersection_explicit'),'design':('LEGACY-ASSET-B07A2E5BD7DA80C16817','design','unresolved','design_contract_evidence',[(31,44),(132,148)],['BR14-HARNESS-A02','BR14-HARNESS-A03'],'product_candidate_phase_unresolved'),'implementation':('LEGACY-ASSET-A098EACAF07A5848E6B1','implementation_source','unresolved','partial_implementation_behavior_evidence_unexecuted',[(273,355)],['BR14-HARNESS-A02'],'classification_conflict_phase_product_nonintersection')}},
'IRUNIT-HIL-BR-14-HELIX-OS':{'product':'HELIX-OS','product_scope':['HELIX-OS'],'product_target':'HELIX-OS','phases':[],'shared_peer':None,'shared_overlap_mode':'none','atoms':[atom('BR14-OS-A01','aggregate_only_rejection','aggregate-only rejection','file集合やaggregate親の列挙、source宣言、読了だけを採用済みとみなさない','file集合やaggregate親の列挙、source宣言、読了だけを採用済みとみなさない'),atom('BR14-OS-A02','authority_derived_denominator','authority-derived denominator','ref件数、unique tree entry分母、全ref-entry edge分母はauthority receiptから導出し','ref件数、unique tree entry分母、全ref-entry edge分母はauthority receiptから導出し'),atom('BR14-OS-A03','observation_count_nonbinding','observation count non-binding','観測時の件数を要件へ固定しない','観測時の件数を要件へ固定しない')],'connective':['、','。'],'anchors':['aggregate','authority','denominator','observation','entry'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(561,602)],['BR14-OS-A01','BR14-OS-A02','BR14-OS-A03'],'requirement_role_phase_nonintersection_explicit'),'design':('LEGACY-ASSET-41A13F9012DD822F1DDC','design','unresolved','design_contract_evidence',[(31,47),(84,99),(115,127)],['BR14-OS-A01','BR14-OS-A02'],'product_candidate_phase_unresolved'),'implementation':('LEGACY-ASSET-AF851B7714F4CF28BAC6','implementation_source','unresolved','partial_implementation_behavior_evidence_unexecuted',[(28,40),(53,107),(110,134)],['BR14-OS-A01'],'classification_conflict_phase_product_nonintersection')}}}

FIELDS={'artifact_evidence_kind','asset_id','authority_effect','batch_id','bounded_search_query','candidate_membership_semantics','candidate_phase_targets','candidate_product_targets','catalog_legacy_implementation_status','classification_id','consumer_closure_evidence','consumer_closure_status','counterevidence','coverage','covered_requirement_atom_ids','covered_requirement_atoms','current_requirement_implementation_status','evidence_atom_bindings','evidence_refs','legacy_asset_evidence_state','legacy_execution_status','legacy_requirement_implementation_contribution','new_build_allowed','observed_consumer_refs','phase_authority_status','phase_candidates','product_alignment_status','product_scope','review_id','review_scope','role_kind','schema_revision','selection_route','semantic_link_status','semantic_relation','source_path','source_requirement_id','source_sha256','source_statement_semantic_digest','source_text_spans','unit_candidate_id','unresolved'}
def need(x,s):
 if not x:raise AssertionError(s)
def sha(b):return 'sha256:'+hashlib.sha256(b).hexdigest()
def canon(x):return sha(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
def jl(p):return [json.loads(x) for x in p.read_text().splitlines() if x.strip()]
def excerpt(path,a,b):
 ls=path.read_text(errors='replace').splitlines();need(1<=a<=b<=len(ls),f'line bounds {path}:{a}-{b}');return '\n'.join(ls[a-1:b])+'\n'
def token(a,t):
 if re.fullmatch(r'[A-Za-z0-9_/-]+',a):return any((m.start()==0 or not t[m.start()-1].isalnum()) and (m.end()==len(t) or not t[m.end()].isalnum()) for m in re.finditer(re.escape(a),t))
 return a in t
JP_PARTICLES=re.compile(r'(?:から|まで|より|だけ|しか|ほど|ばかり|くらい|ぐらい|こそ|さえ|など|なんて|って|は|が|を|に|へ|で|と|の|も|や)')
def particle_stripped(fragment):
 return JP_PARTICLES.sub('',fragment)
def expected_cov(unit,rows):
 d=U[unit];ids=[a['atom_id'] for a in d['atoms']];rs=[r for r in rows if r['unit_candidate_id']==unit];shared=sorted(a['atom_id'] for a in d['atoms'] if a['shared_with_units']);connection=d['product'] is None;exclusive=[] if connection else sorted(set(ids)-set(shared));connection_atoms=sorted(ids) if connection else [];dcon=sorted({x for r in rs if r['role_kind'] in {'design','plan'} and r['semantic_link_status']=='confirmed' for x in r['covered_requirement_atom_ids']});dun=sorted({x for r in rs if r['role_kind'] in {'design','plan'} and r['semantic_link_status']=='unresolved' for x in r['covered_requirement_atom_ids']});iun=sorted({x for r in rs if r['role_kind']=='implementation' and r['semantic_link_status']=='unresolved' for x in r['covered_requirement_atom_ids']});z={'unit_kind':'cross_product_connection' if connection else 'product_unit','atom_inventory':d['atoms'],'connective_fragments':d['connective'],'contract_confirmed_atom_ids':ids,'design_confirmed_atom_ids':dcon,'design_unresolved_atom_ids':dun,'design_rejected_asset_ids':sorted(r['asset_id'] for r in rs if r['role_kind'] in {'design','plan'} and r['semantic_link_status']=='rejected'),'design_partial_pending_kind_atom_ids':[],'implementation_confirmed_atom_ids':[],'implementation_unresolved_atom_ids':iun,'implementation_rejected_atom_ids':[],'implementation_rejected_asset_ids':sorted(r['asset_id'] for r in rs if r['role_kind']=='implementation' and r['semantic_link_status']=='rejected'),'implementation_uncovered_atom_ids':sorted(set(ids)-set(iun)),'no_evidence_atom_ids':sorted(set(ids)-set(dcon)-set(dun)-set(iun)),'shared_atom_ids':shared,'product_exclusive_atom_ids':exclusive,'cross_product_connection_atom_ids':connection_atoms}
 for k in list(z):z[k+'_sha256']=canon(z[k])
 z.update({'contract_semantic_edge_coverage_complete':True,'semantic_edge_coverage_complete':False,'no_shared_source_span':not shared,'product_boundary_decision_complete':False,'product_exclusive_contract_coverage_complete':not connection,'connection_contract_human_decision_pending':connection});return z
def main():
 rows=jl(L);meta=json.loads(M.read_text());cat={x['asset_id']:x for x in jl(CAT)};cross={x['unit_candidate_id']:x for x in jl(CROSS)};decomps=jl(DECOMP);dec={u['unit_candidate_id']:u for x in decomps for u in x['candidate_units']};dec_parent={u['unit_candidate_id']:x for x in decomps for u in x['candidate_units']};manifest={x.split('  ',1)[1]:x.split('  ',1)[0] for x in MAN.read_text().splitlines() if '  ' in x};st=STATUS.read_text();expected_phase_rows=[]
 need(len(cat)==4020,'catalog count');need(set(meta)=={'authority_effect','batch_id','bounded_search_receipts','consumer_closure_status','cumulative_reviewed_edge_count','cumulative_reviewed_unit_count','inputs','legacy_execution_performed','new_build_allowed','output_sha256','parent_revision','prior_review_batches','record_count','reviewed_edges','reviewed_unit_ids','schema_revision','semantic_link_counts','source_revision','status','unit_aggregates'},'meta fields');need(meta['schema_revision']==10 and meta['batch_id']==BATCH and meta['parent_revision']==REV,'meta identity');need(meta['record_count']==len(rows)==9 and meta['output_sha256']==sha(L.read_bytes()),'ledger digest');need(meta['authority_effect']=='none' and meta['status']=='research_premise_candidate' and meta['consumer_closure_status']=='pending' and not meta['legacy_execution_performed'] and not meta['new_build_allowed'],'authority boundary');need(meta['reviewed_unit_ids']==list(U) and meta['cumulative_reviewed_unit_count']==47 and meta['cumulative_reviewed_edge_count']==141,'unit/count')
 inputs=[MAN,CAT,CROSS,DECOMP,PHASE]+[p for pair in PRIOR for p in pair];need(meta['inputs']=={str(p.relative_to(R)):sha(p.read_bytes()) for p in inputs},'input digests')
 for p in inputs:need(sha(subprocess.run(['git','show',f'{REV}:{p.relative_to(R)}'],cwd=R,check=True,capture_output=True).stdout)==sha(p.read_bytes()),f'parent blob {p}')
 prioru=set();priore=set();priorassets=set();pb=[];prior_atom_map={}
 for lp,mp in PRIOR:
  old=jl(lp);om=json.loads(mp.read_text());prioru|=set(om['reviewed_unit_ids']);priore|={(x['unit_candidate_id'],x['asset_id']) for x in om['reviewed_edges']};priorassets|={x['asset_id'] for x in old if x['artifact_evidence_kind'] in {'design','plan','implementation_source'}}
  for x in old:
   for a in x.get('covered_requirement_atoms',[]):prior_atom_map[a['atom_id']]=a
  pb.append({'batch_id':om['batch_id'],'ledger_sha256':sha(lp.read_bytes()),'meta_sha256':sha(mp.read_bytes())})
 edges={(r['unit_candidate_id'],r['asset_id']) for r in rows};expected={(u,x[0]) for u,d in U.items() for x in d['roles'].values()};selected={x[0] for d in U.values() for role,x in d['roles'].items() if role!='requirement'};need(meta['prior_review_batches']==pb and not edges&priore and not selected&priorassets,'prior overlap');need(edges==expected and len(prioru|set(U))==47 and len(priore|edges)==141,'edge/cumulative exact');need(meta['reviewed_edges']==[{'unit_candidate_id':r['unit_candidate_id'],'asset_id':r['asset_id']} for r in rows],'edge order')
 by={(r['unit_candidate_id'],r['role_kind']):r for r in rows};need(len(by)==9,'unique unit roles');need([r['review_id'] for r in rows]==[f'LSRW16-EDGE-{i:03d}' for i in range(1,10)],'review ids')
 for unit,d in U.items():
  c=cross[unit];du=dec[unit]
  if unit=='IRUNIT-HIL-BR-12-HELIX-HARNESS':
   peer=prior_atom_map.get('BR12-OS-A06');need(peer and peer['shared_with_units']==[unit] and peer['source_fragments']==['同じintake契約へ正規化し'] and peer['text']=='全入力を同じintake契約へ正規化する','BR12 peer symmetry')
  if unit=='IRUNIT-HIL-BR-14-HELIX-OS':need(c['direct_phase_candidates']==[] and c['phase_capability_evidence']==[] and d['phases']==[],'BR14 OS phase zero exact')
  parent=dec_parent[unit];connection=d['product'] is None;unit_kind='cross_product_connection' if connection else 'product_unit';need(c['product_scope']==d['product_scope'] and du.get('product_target')==d['product_target'] and du['unit_kind']==unit_kind and all(x.get('review_state')=='product_boundary_pending_human_decision' for x in (du.get('shared_source_overlaps') or [])),'product/shared');need((du.get('connected_product_targets')==d['product_scope']) if connection else 'connected_product_targets' not in du,'connection targets');connection_flags={'connection_contract_human_decision_pending','shared_connection_atom_requires_independent_review'};need((connection_flags<=set(parent['unresolved_reasons'])) if connection else not (connection_flags&set(parent['unresolved_reasons'])),'connection parent flags');overlaps=[x['source_text'] for x in (du.get('shared_source_overlaps') or [])];shared_frags=[f for a in d['atoms'] if a['shared_with_units'] for f in a['source_fragments']];need(all(x.get('review_state')=='product_boundary_pending_human_decision' for x in (du.get('shared_source_overlaps') or [])),'shared overlap state');need(overlaps==shared_frags if d['shared_overlap_mode']=='decomposition_only' else (overlaps==c['source_text_spans'] if d['shared_overlap_mode']=='exact_spans' else (overlaps==[''.join(c['source_text_spans'])] if d['shared_overlap_mode']=='composite_exact_spans' else overlaps==[])),'shared overlap exact');need(shared_frags==['同じintake契約へ正規化し'] if d['shared_overlap_mode']=='decomposition_only' else (shared_frags==c['source_text_spans'] if d['shared_overlap_mode']=='exact_spans' else (shared_frags==c['source_text_spans'] if d['shared_overlap_mode']=='composite_exact_spans' else shared_frags==[])),'shared atom mapping');need(all((not a['shared_with_units']) or a['shared_with_units']==[d['shared_peer']] for a in d['atoms']),'shared peer exact');shared_keys=[particle_stripped(f) for f in shared_frags];exclusive_frags=[f for a in d['atoms'] if not a['shared_with_units'] for f in a['source_fragments']];exclusive_keys=[particle_stripped(f) for f in exclusive_frags];need(all(s and e and s not in e and e not in s for s in shared_keys for e in exclusive_keys),f'shared/exclusive fragment containment overlap {unit}');need(c['direct_phase_candidates']==d['phases'],'unit phases');frags=[f for a in d['atoms'] for f in a['source_fragments']];need(len(frags)==len(set(frags)) and all(sum(f in s for s in c['source_text_spans'])==1 for f in frags),'atom fragment placement');need(set(d['connective'])<= {'と','、','。'} and len(d['connective'])==len(set(d['connective'])) and not set(d['connective'])&set(frags),'connective allowlist')
  expected_phase_rows.extend('| '+' | '.join([unit,'／'.join(d['product_scope']),p['phase_id'],p['current_status'],p['legacy_capability_status'],p['transition_assessment']])+' |' for p in c['phase_capability_evidence'])
  for s in c['source_text_spans']:
   rem=s
   for f in frags:
    if f in rem:rem=rem.replace(f,'')
   for x in d['connective']:rem=rem.replace(x,'')
   need(not re.sub(r'[\s。、・|`]','',rem),f'atom loss {unit}: {rem}')
  search=sorted(a for a,z in cat.items() if any(token(q,(AR/z['source_path']).read_text(errors='replace')) for q in d['anchors']));rec=meta['bounded_search_receipts'][unit];sel=sorted(x[0] for x in d['roles'].values());rest=sorted(set(search)-set(sel));need(rec=={'query':{'match_mode':'archive_file_contains_any_utf8_anchor','anchors':d['anchors']},'catalog_record_count':4020,'candidate_asset_count':len(search),'candidate_asset_ids_sha256':canon(search),'selected_asset_ids':sel,'unreviewed_asset_count':len(rest),'unreviewed_asset_ids_sha256':canon(rest)},f'search receipt {unit}');need(set(sel)<=set(search),f'selected outside search {unit}')
  amap={a['atom_id']:a for a in d['atoms']}
  for role,x in d['roles'].items():
   aid,kind,status,relation,spans,ids,alignment=x;r=by[(unit,role)];z=cat[aid];need(set(r)==FIELDS,f'row fields {r["review_id"]}');need(r['asset_id']==aid and r['artifact_evidence_kind']==kind and r['semantic_link_status']==status and r['semantic_relation']==relation and r['product_alignment_status']==alignment,'role result');need(r['schema_revision']==10 and r['batch_id']==BATCH and r['authority_effect']=='none' and r['selection_route']=='bounded_global_search' and r['candidate_membership_semantics']=='bounded_global_search_candidate_only_not_semantic_evidence','row boundary');need(r['bounded_search_query']==rec['query'] and r['phase_candidates']==d['phases'] and r['product_scope']==d['product_scope'],'row unit exact');need(r['source_requirement_id']==c['source_requirement_id'] and r['source_statement_semantic_digest']==c['source_statement_semantic_digest'] and r['source_text_spans']==c['source_text_spans'],'crosswalk exact');need(all(r[o]==z[s] for o,s in {'artifact_evidence_kind':'artifact_evidence_kind','classification_id':'classification_id','source_path':'source_path','source_sha256':'source_sha256','candidate_phase_targets':'candidate_phase_targets','candidate_product_targets':'candidate_product_targets','legacy_asset_evidence_state':'implementation_evidence_state','catalog_legacy_implementation_status':'legacy_implementation_status','observed_consumer_refs':'consumer_refs'}.items()),f'catalog exact {r["review_id"]}')
   phase_hit=bool(set(d['phases'])&set(z['candidate_phase_targets'])); product_hit=bool(set(z['candidate_product_targets']) & set(d['product_scope']))
   if alignment=='classification_conflict_phase_product_nonintersection': need(not phase_hit and not product_hit and z['candidate_product_targets']==[],f'classification conflict exact {r["review_id"]}')
   elif alignment=='classification_conflict_product_nonintersection': need(phase_hit and not product_hit and z['candidate_product_targets']==[],f'classification product conflict exact {r["review_id"]}')
   elif alignment=='phase_and_product_candidate_intersection': need(phase_hit and product_hit,f'phase/product intersection {r["review_id"]}')
   elif alignment=='product_candidate_phase_unresolved': need(not phase_hit and product_hit,f'product candidate without phase intersection {r["review_id"]}')
   elif alignment=='requirement_role_phase_nonintersection_explicit': need(role=='requirement' and not phase_hit and product_hit,f'requirement phase nonintersection {r["review_id"]}')
   else: need(alignment=='requirement_role_exact_contract_phase_intersection_not_semantic_basis' and role=='requirement' and phase_hit and product_hit,f'requirement phase intersection {r["review_id"]}')
   p=AR/z['source_path'];need(hashlib.sha256(p.read_bytes()).hexdigest()==r['source_sha256']==manifest[r['source_path']],'archive digest');need(r['legacy_execution_status']=='not_run' and r['current_requirement_implementation_status']=='not_established' and r['consumer_closure_status']=='pending' and not r['consumer_closure_evidence'] and not r['new_build_allowed'],'record state');need((connection_flags<=set(r['unresolved'])) if connection else not (connection_flags&set(r['unresolved'])),'connection row flags');need(r['covered_requirement_atom_ids']==ids and r['covered_requirement_atoms']==[amap[i] for i in ids],'atom coverage exact');need([(e['line_start'],e['line_end']) for e in r['evidence_refs']]==spans,'span exact')
   if status in {'confirmed','unresolved'}:
    need(r['counterevidence'] and all(isinstance(q,str) and q.strip() for q in r['counterevidence']),f'bounded counterevidence {r["review_id"]}')
    if role=='requirement':need(any('実装・実行証拠ではない' in q for q in r['counterevidence']) and any('consumer closure未確認' in q for q in r['counterevidence']),f'requirement limits {r["review_id"]}')
    if role in {'design','plan'}:need(any('実装・実行証拠ではない' in q for q in r['counterevidence']),f'design/plan limits {r["review_id"]}')
   texts=[]
   for e in r['evidence_refs']:
    need(e['archive_path']==str(p.relative_to(R)) and e['artifact_role']==role and e['excerpt_status']=='static_read_only' and e['source_requirement_relation']==relation,'evidence metadata');t=excerpt(p,e['line_start'],e['line_end']);need(e['excerpt_sha256']==sha(t.encode()),'excerpt digest');texts.append(t)
   if status=='rejected':need(not ids and not r['evidence_atom_bindings'] and any('covered atoms=0' in q for q in r['counterevidence']),'rejected zero')
   else:
    need(sorted(b['atom_id'] for b in r['evidence_atom_bindings'])==sorted(ids),'binding ids')
    for b in r['evidence_atom_bindings']:
     need(b['atom_id'] in ids and b['evidence_ref_indexes'] and all(0<=i<len(texts) for i in b['evidence_ref_indexes']),'binding refs');joined='\n'.join(texts[i] for i in b['evidence_ref_indexes']);need(all(q in joined for q in b['required_terms']),'binding terms')
     if b['match_mode']=='literal_source_fragment':need(all(f in joined for f in amap[b['atom_id']]['source_fragments']),'literal binding')
     else:
      anchors=b['source_fragment_anchors'];mapped=b.get('anchor_evidence_terms',{})
      need(b['match_mode']=='controlled_term_set_partial' and anchors and set(mapped)<=set(anchors) and all(
       q in amap[b['atom_id']]['text'] and q in ''.join(amap[b['atom_id']]['source_fragments']) and
       (q in joined or bool(mapped.get(q)) and all(t in b['required_terms'] and t in joined for t in mapped[q]))
       for q in anchors),'controlled binding evidence-grounded anchors')
   if r['review_id']=='LSRW16-EDGE-001':need(any('shared peer' in q for q in r['counterevidence']),'EDGE-001 shared counterevidence')
   if r['review_id']=='LSRW16-EDGE-002':need(any('BR12-HARNESS-A02' in q and 'development style' in q for q in r['counterevidence']),'BR12 design uncovered counterevidence')
   if r['review_id']=='LSRW16-EDGE-003':need(any('BR12-HARNESS-A01' in q and 'intake' in q for q in r['counterevidence']),'BR12 implementation uncovered counterevidence')
   if r['review_id'] in {'LSRW16-EDGE-005','LSRW16-EDGE-006'}:need(any('BR14-HARNESS-A01' in q and 'current advertised' in q for q in r['counterevidence']),'BR14-H uncovered counterevidence')
   if r['review_id']=='LSRW16-EDGE-008':need(any('BR14-OS-A03' in q and '観測時の件数' in q for q in r['counterevidence']),'BR14-OS design uncovered counterevidence')
   if r['review_id']=='LSRW16-EDGE-009':need(any('BR14-OS-A02' in q and 'authority receipt' in q for q in r['counterevidence']) and any('BR14-OS-A03' in q and '観測時の件数' in q for q in r['counterevidence']),'BR14-OS implementation uncovered counterevidence')
   if role in {'design','plan'} and status=='confirmed':need(kind in {'design','plan'} and relation in {'design_contract_evidence','design_candidate_unresolved'} and ids and r['legacy_requirement_implementation_contribution']=='design_contract_only_no_implementation_claim' and all(b['match_mode']=='controlled_term_set_partial' and b['required_terms'] and b['source_fragment_anchors'] for b in r['evidence_atom_bindings']) and any('consumer closure未確認' in q for q in r['counterevidence']),'design confirmed gate')
  agg=next(a for a in meta['unit_aggregates'] if a['unit_candidate_id']==unit);cov=expected_cov(unit,rows);need(agg['product_scope']==d['product_scope'] and agg['reviewed_edge_count']==3 and agg['atom_coverage_receipt']==cov,'aggregate coverage');need(agg['semantic_link_counts']=={s:sum(r['unit_candidate_id']==unit and r['semantic_link_status']==s for r in rows) for s in ('confirmed','rejected','unresolved')},'aggregate statuses');need(agg['phase_authority_status']=='candidate_unchanged' and agg['current_requirement_implementation_status']=='not_established' and agg['legacy_requirement_implementation_status']=='unknown_pending_direct_asset_semantic_review' and not agg['direct_confirmed_implementation_asset_ids'] and agg['consumer_closure_status']=='pending' and not agg['new_build_allowed'],'aggregate state')
  status_values=[unit,len(cov['atom_inventory']),len(cov['contract_confirmed_atom_ids']),len(cov['design_confirmed_atom_ids']),len(cov['design_unresolved_atom_ids']),len(cov['design_rejected_asset_ids']),len(cov['design_partial_pending_kind_atom_ids']),len(cov['implementation_confirmed_atom_ids']),len(cov['implementation_unresolved_atom_ids']),len(cov['implementation_rejected_asset_ids']),len(cov['implementation_uncovered_atom_ids']),len(cov['no_evidence_atom_ids'])];need('| '+' | '.join(map(str,status_values))+' |' in STATUS.read_text(),f'status aggregate row {unit}')
 actual_phase_rows=[line for line in st.splitlines() if (line.startswith('| IRUNIT-') or line.startswith('| IRCONN-')) and len(line.split('|'))==8];need(actual_phase_rows==expected_phase_rows,'status phase rows exact')
 need(meta['semantic_link_counts']=={'confirmed':3,'rejected':0,'unresolved':6},'batch statuses');docs='\n'.join(p.read_text() for p in (STATUS,METHOD,PREMISE,RESPONSE));assets={x[0] for d in U.values() for x in d['roles'].values()};need(all(a in PREMISE.read_text() and a in RESPONSE.read_text() for a in assets),'document assets');need(all(REV in p.read_text() for p in (STATUS,METHOD,PREMISE)),'document parent revision');need('BR12-A01はshared peer' in PREMISE.read_text() and 'BR14のatomはproduct-exclusive' in PREMISE.read_text() and 'BR14-OS phase 0' in st,'document product/phase boundary');need('{BATCH}' not in docs and '{REV}' not in docs and 'confirmed 3 (contract 3 / design 0) / rejected 0 / unresolved 6' in st and '8 atom' in RESPONSE.read_text() and '171 units remaining' in st,'document counts');need('| unit | atoms | contract | design confirmed | design unresolved |' in st,'document design split');need('runtime、test、hook、CI、adapterは実行していない' in METHOD.read_text() and 'candidate membershipはsemantic evidenceではない' in st,'document boundary')
 print('legacy requirement direct semantic review wave16: schema10 / 9 edges / 8 atoms / confirmed3 rejected0 unresolved6 / cumulative47 units 141 edges remaining171 / full static verification passed')
if __name__=='__main__':
 try:main()
 except Exception as e:print('FAIL:',e);sys.exit(1)
