#!/usr/bin/env python3
"""Wave12 schema10 full static verifier; archive assets are read, never executed."""
from pathlib import Path
import hashlib,json,re,subprocess,sys
R=Path(__file__).resolve().parents[3]; G=R/'docs/governance'; A=G/'audits/source-rebaseline'; AR=R/'archive/legacy-generation-2026-09-14/root'
REV='1c6062e4922b01bc0584aa76e902b737b65da25d'; BATCH='LEGACY-SEMANTIC-WAVE12-2026-09-21'
L=G/'legacy-requirement-direct-semantic-review-wave12.jsonl'; M=G/'legacy-requirement-direct-semantic-review-wave12.meta.json'; STATUS=A/'legacy-requirement-direct-semantic-review-wave12-status-2026-09-21.md'; METHOD=A/'legacy-requirement-direct-semantic-review-wave12-method-2026-09-21.md'; PREMISE=A/'legacy-requirement-direct-semantic-review-wave12-premise-packet-2026-09-21.md'; RESPONSE=A/'legacy-requirement-direct-semantic-review-wave12-review-response-2026-09-21.md'
CAT=G/'legacy-asset-phase-product-classification-bootstrap.jsonl'; CROSS=G/'legacy-requirement-implementation-crosswalk-bootstrap.jsonl'; DECOMP=G/'legacy-ir-product-unit-decomposition-bootstrap.jsonl'; PHASE=G/'phase-capability-inventory.json'; MAN=R/'archive/legacy-generation-2026-09-14/MANIFEST.sha256'; PRIOR=[(G/f'legacy-requirement-direct-semantic-review-wave{n}.jsonl',G/f'legacy-requirement-direct-semantic-review-wave{n}.meta.json') for n in range(1,12)]
def atom(i,k,s,rr,t,f):return {'atom_id':i,'boundary_review_state':'product_boundary_pending_human_decision','kind':k,'responsibility_role':rr,'shared_with_units':[],'source_fragments':[f],'subject':s,'text':t}
U={
'IRUNIT-HIL-BR-07-HELIX-HARNESS':{'phases':['PHCAP-04','PHCAP-12'],'atoms':[atom('BR07-HARNESS-A01','ai_terminal_prohibition','AI','directive/Issue terminal action prohibition','AIが不要判断だけでreject/drop/close/cancelできない','AIが不要判断だけでreject/drop/close/cancelできない'),atom('BR07-HARNESS-A02','nonactionable_nonterminal','AI','nonactionable disposition remains nonterminal','AIの非actionable dispositionは非終端で','AIの非actionable dispositionは非終端で'),atom('BR07-HARNESS-A03','po_authority','PO','cancel/supersede authority','cancel/supersedeはPOだけが行える','cancel/supersedeはPOだけが行える')],'connective':[],'anchors':['HIL-BR-07','disposition','supersession','counterevidence_required'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(260,270)],['BR07-HARNESS-A01','BR07-HARNESS-A02','BR07-HARNESS-A03'],'requirement_role_phase_nonintersection_explicit'),'design':('LEGACY-ASSET-F99FFC68663F1106347E','design','rejected','design_candidate_rejected',[(35,50)],[],'phase_and_product_candidate_intersection'),'implementation':('LEGACY-ASSET-57A29D57A3AD07CA4DFF','implementation_source','rejected','implementation_candidate_rejected',[(247,260)],[],'phase_and_product_candidate_intersection')}},
'IRUNIT-HIL-BR-21-HELIX-HARNESS':{'phases':['PHCAP-18'],'atoms':[atom('BR21-HARNESS-A01','subject_scope','設計上の重複、責務混在、変更波及、埋込みpolicy','refactoring scope','設計上の重複、責務混在、変更波及、埋込みpolicyを、','設計上の重複、責務混在、変更波及、埋込みpolicyを、'),atom('BR21-HARNESS-A02','design_contract','DesignRefactor駆動モデル','externalize/commonize/objectize','外部仕様と受入挙動を維持したまま外部化・共通化・オブジェクト化する第一級`DesignRefactor`駆動モデルを持つ。','外部仕様と受入挙動を維持したまま外部化・共通化・オブジェクト化する第一級`DesignRefactor`駆動モデルを持つ。'),atom('BR21-HARNESS-A03','reroute_contract','要求・公開contract・永続state semantics','Redesign/Retrofit reroute','要求・公開contract・永続state semanticsを変える場合は`Redesign`または`Retrofit`へrerouteする。','要求・公開contract・永続state semanticsを変える場合は`Redesign`または`Retrofit`へrerouteする。')],'connective':[],'anchors':['DesignTransformV1','DesignRefactor','V_MODEL_PAIRS','COMPATIBILITY_V_MODEL_PAIRS'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(862,872)],['BR21-HARNESS-A01','BR21-HARNESS-A02','BR21-HARNESS-A03'],'requirement_role_exact_contract_phase_intersection_not_semantic_basis'),'design':('LEGACY-ASSET-3B8F5F0230F7469B5D11','design','confirmed','design_contract_evidence',[(20,30),(89,98)],['BR21-HARNESS-A02','BR21-HARNESS-A03'],'phase_and_product_candidate_intersection'),'implementation':('LEGACY-ASSET-4253C9EE9C0E93F5980A','implementation_source','rejected','implementation_candidate_rejected',[(137,155)],[],'phase_and_product_candidate_intersection')}},
'IRUNIT-HIL-FR-45-HELIX-HARNESS':{'phases':['PHCAP-03','PHCAP-05'],'atoms':[atom('FR45-HARNESS-A01','subject_scope','Requirement Definition Ledger','ledger responsibility subject','Requirement Definition Ledgerは','Requirement Definition Ledgerは'),atom('FR45-HARNESS-A02','stable_identity','Requirement Definition Ledger','stable requirement identity','stable requirement ID','stable requirement ID'),atom('FR45-HARNESS-A03','immutable_revision','Requirement Definition Ledger','immutable revision','immutable revisionを持ち、','immutable revisionを持ち、'),atom('FR45-HARNESS-A04','typed_ledger_obligation','Requirement Definition Ledger','source atom through design obligation typed edges','source atom、canonical statement、BR/FR/TR/NFR、modality、priority、scope/non-goal、authority/rationale、acceptance oracle、owner、risk、capability/service、template applicability、design obligationを型付きedgeで保存する','source atom、canonical statement、BR/FR/TR/NFR、modality、priority、scope/non-goal、authority/rationale、acceptance oracle、owner、risk、capability/service、template applicability、design obligationを型付きedgeで保存する'),atom('FR45-HARNESS-A05','requirement_revision_projection','requirement definition/revision','definition and revision projection','requirement definition/revision','requirement definition/revision'),atom('FR45-HARNESS-A06','typed_edge_projection','typed edge','typed edge projection','typed edge','typed edge')],'connective':['と'],'anchors':['PLAN-RECOVERY-12','REQUIREMENTS_BINDING','stable requirement ID','typed edge','catalog_version'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(3318,3328)],['FR45-HARNESS-A01','FR45-HARNESS-A02','FR45-HARNESS-A03','FR45-HARNESS-A04','FR45-HARNESS-A05','FR45-HARNESS-A06'],'requirement_role_phase_nonintersection_explicit'),'design':('LEGACY-ASSET-AE6C75BE20AE0DC9BD20','plan','unresolved','design_candidate_unresolved',[(15,35),(42,45)],[],'phase_and_product_candidate_intersection'),'implementation':('LEGACY-ASSET-E3E4D23A3AB9C149BE3D','implementation_source','unresolved','partial_implementation_behavior_evidence_unexecuted',[(55,68),(230,239)],['FR45-HARNESS-A02'],'classification_conflict_phase_product_nonintersection')}}}
FIELDS={'artifact_evidence_kind','asset_id','authority_effect','batch_id','bounded_search_query','candidate_membership_semantics','candidate_phase_targets','candidate_product_targets','catalog_legacy_implementation_status','classification_id','consumer_closure_evidence','consumer_closure_status','counterevidence','coverage','covered_requirement_atom_ids','covered_requirement_atoms','current_requirement_implementation_status','evidence_atom_bindings','evidence_refs','legacy_asset_evidence_state','legacy_execution_status','legacy_requirement_implementation_contribution','new_build_allowed','observed_consumer_refs','phase_authority_status','phase_candidates','product_alignment_status','product_scope','review_id','review_scope','role_kind','schema_revision','selection_route','semantic_link_status','semantic_relation','source_path','source_requirement_id','source_sha256','source_statement_semantic_digest','source_text_spans','unit_candidate_id','unresolved'}
def need(x,s):
 if not x:raise AssertionError(s)
def sha(b):return 'sha256:'+hashlib.sha256(b).hexdigest()
def canon(x):return sha(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
def jl(p):return [json.loads(x) for x in p.read_text().splitlines() if x.strip()]
def excerpt(path,a,b):
 ls=path.read_text(errors='replace').splitlines();need(1<=a<=b<=len(ls),f'line bounds {path}:{a}-{b}');return '\n'.join(ls[a-1:b])+'\n'
def token(a,t):
 if re.fullmatch(r'[A-Za-z0-9_/-]+',a):return any((m.start()==0 or not t[m.start()-1].isalnum()) and (m.end()==len(t) or not t[m.end()].isalnum()) for m in re.finditer(re.escape(a),t))
 return a in t
def expected_cov(unit,rows):
 d=U[unit];ids=[a['atom_id'] for a in d['atoms']];rs=[r for r in rows if r['unit_candidate_id']==unit];design=sorted({x for r in rs if r['role_kind']=='design' and r['semantic_link_status'] in {'confirmed','unresolved'} for x in r['covered_requirement_atom_ids']});iun=sorted({x for r in rs if r['role_kind']=='implementation' and r['semantic_link_status']=='unresolved' for x in r['covered_requirement_atom_ids']});z={'atom_inventory':d['atoms'],'connective_fragments':d['connective'],'contract_confirmed_atom_ids':ids,'design_partial_atom_ids':design,'design_rejected_asset_ids':sorted(r['asset_id'] for r in rs if r['role_kind']=='design' and r['semantic_link_status']=='rejected'),'design_partial_pending_kind_atom_ids':[],'implementation_confirmed_atom_ids':[],'implementation_unresolved_atom_ids':iun,'implementation_rejected_atom_ids':[],'implementation_rejected_asset_ids':sorted(r['asset_id'] for r in rs if r['role_kind']=='implementation' and r['semantic_link_status']=='rejected'),'implementation_uncovered_atom_ids':sorted(set(ids)-set(iun)),'no_evidence_atom_ids':sorted(set(ids)-set(design)-set(iun)),'shared_atom_ids':[],'product_exclusive_atom_ids':ids}
 for k in list(z):z[k+'_sha256']=canon(z[k])
 z.update({'contract_semantic_edge_coverage_complete':True,'semantic_edge_coverage_complete':False,'no_shared_source_span':True,'product_boundary_decision_complete':False,'product_exclusive_contract_coverage_complete':True});return z
def main():
 rows=jl(L);meta=json.loads(M.read_text());cat={x['asset_id']:x for x in jl(CAT)};cross={x['unit_candidate_id']:x for x in jl(CROSS)};dec={u['unit_candidate_id']:u for x in jl(DECOMP) for u in x['candidate_units']};manifest={x.split('  ',1)[1]:x.split('  ',1)[0] for x in MAN.read_text().splitlines() if '  ' in x}
 need(len(cat)==4020,'catalog count');need(set(meta)=={'authority_effect','batch_id','bounded_search_receipts','consumer_closure_status','cumulative_reviewed_edge_count','cumulative_reviewed_unit_count','inputs','legacy_execution_performed','new_build_allowed','output_sha256','parent_revision','prior_review_batches','record_count','reviewed_edges','reviewed_unit_ids','schema_revision','semantic_link_counts','source_revision','status','unit_aggregates'},'meta fields');need(meta['schema_revision']==10 and meta['batch_id']==BATCH and meta['parent_revision']==REV,'meta identity');need(meta['record_count']==len(rows)==9 and meta['output_sha256']==sha(L.read_bytes()),'ledger digest');need(meta['authority_effect']=='none' and meta['status']=='research_premise_candidate' and meta['consumer_closure_status']=='pending' and not meta['legacy_execution_performed'] and not meta['new_build_allowed'],'authority boundary');need(meta['reviewed_unit_ids']==list(U) and meta['cumulative_reviewed_unit_count']==35 and meta['cumulative_reviewed_edge_count']==105,'unit/count')
 inputs=[MAN,CAT,CROSS,DECOMP,PHASE]+[p for pair in PRIOR for p in pair];need(meta['inputs']=={str(p.relative_to(R)):sha(p.read_bytes()) for p in inputs},'input digests')
 for p in inputs:need(sha(subprocess.run(['git','show',f'{REV}:{p.relative_to(R)}'],cwd=R,check=True,capture_output=True).stdout)==sha(p.read_bytes()),f'parent blob {p}')
 prioru=set();priore=set();priorassets=set();pb=[]
 for lp,mp in PRIOR:
  old=jl(lp);om=json.loads(mp.read_text());prioru|=set(om['reviewed_unit_ids']);priore|={(x['unit_candidate_id'],x['asset_id']) for x in om['reviewed_edges']};priorassets|={x['asset_id'] for x in old if x['artifact_evidence_kind'] in {'design','plan','implementation_source'}};pb.append({'batch_id':om['batch_id'],'ledger_sha256':sha(lp.read_bytes()),'meta_sha256':sha(mp.read_bytes())})
 edges={(r['unit_candidate_id'],r['asset_id']) for r in rows};expected={(u,x[0]) for u,d in U.items() for x in d['roles'].values()};selected={x[0] for d in U.values() for role,x in d['roles'].items() if role!='requirement'};need(meta['prior_review_batches']==pb and not edges&priore and not selected&priorassets,'prior overlap');need(edges==expected and len(prioru|set(U))==35 and len(priore|edges)==105,'edge/cumulative exact');need(meta['reviewed_edges']==[{'unit_candidate_id':r['unit_candidate_id'],'asset_id':r['asset_id']} for r in rows],'edge order')
 by={(r['unit_candidate_id'],r['role_kind']):r for r in rows};need(len(by)==9,'unique unit roles');need([r['review_id'] for r in rows]==[f'LSRW12-EDGE-{i:03d}' for i in range(1,10)],'review ids')
 for unit,d in U.items():
  c=cross[unit];du=dec[unit];need(c['product_scope']==['HELIX-HARNESS'] and du['product_target']=='HELIX-HARNESS' and not du.get('shared_source_overlaps'),'product/shared');need(c['direct_phase_candidates']==d['phases'],'unit phases');frags=[f for a in d['atoms'] for f in a['source_fragments']];need(len(frags)==len(set(frags)) and all(sum(f in s for s in c['source_text_spans'])==1 for f in frags),'atom fragment placement');need(set(d['connective'])<= {'と'} and len(d['connective'])==len(set(d['connective'])) and not set(d['connective'])&set(frags),'connective allowlist')
  for s in c['source_text_spans']:
   rem=s
   for f in frags:
    if f in rem:rem=rem.replace(f,'')
   for x in d['connective']:rem=rem.replace(x,'')
   need(not re.sub(r'[\s。、・|`]','',rem),f'atom loss {unit}: {rem}')
  search=sorted(a for a,z in cat.items() if any(token(q,(AR/z['source_path']).read_text(errors='replace')) for q in d['anchors']));rec=meta['bounded_search_receipts'][unit];sel=sorted(x[0] for x in d['roles'].values());rest=sorted(set(search)-set(sel));need(rec=={'query':{'match_mode':'archive_file_contains_any_utf8_anchor','anchors':d['anchors']},'catalog_record_count':4020,'candidate_asset_count':len(search),'candidate_asset_ids_sha256':canon(search),'selected_asset_ids':sel,'unreviewed_asset_count':len(rest),'unreviewed_asset_ids_sha256':canon(rest)},f'search receipt {unit}');need(set(sel)<=set(search),f'selected outside search {unit}')
  amap={a['atom_id']:a for a in d['atoms']}
  for role,x in d['roles'].items():
   aid,kind,status,relation,spans,ids,alignment=x;r=by[(unit,role)];z=cat[aid];need(set(r)==FIELDS,f'row fields {r["review_id"]}');need(r['asset_id']==aid and r['artifact_evidence_kind']==kind and r['semantic_link_status']==status and r['semantic_relation']==relation and r['product_alignment_status']==alignment,'role result');need(r['schema_revision']==10 and r['batch_id']==BATCH and r['authority_effect']=='none' and r['selection_route']=='bounded_global_search' and r['candidate_membership_semantics']=='bounded_global_search_candidate_only_not_semantic_evidence','row boundary');need(r['bounded_search_query']==rec['query'] and r['phase_candidates']==d['phases'] and r['product_scope']==['HELIX-HARNESS'],'row unit exact');need(r['source_requirement_id']==c['source_requirement_id'] and r['source_statement_semantic_digest']==c['source_statement_semantic_digest'] and r['source_text_spans']==c['source_text_spans'],'crosswalk exact');need(all(r[o]==z[s] for o,s in {'artifact_evidence_kind':'artifact_evidence_kind','classification_id':'classification_id','source_path':'source_path','source_sha256':'source_sha256','candidate_phase_targets':'candidate_phase_targets','candidate_product_targets':'candidate_product_targets','legacy_asset_evidence_state':'implementation_evidence_state','catalog_legacy_implementation_status':'legacy_implementation_status','observed_consumer_refs':'consumer_refs'}.items()),f'catalog exact {r["review_id"]}')
   phase_hit=bool(set(d['phases'])&set(z['candidate_phase_targets'])); product_hit='HELIX-HARNESS' in z['candidate_product_targets']
   if alignment=='classification_conflict_phase_product_nonintersection': need(not phase_hit and not product_hit and z['candidate_product_targets']==[],f'classification conflict exact {r["review_id"]}')
   elif alignment=='phase_and_product_candidate_intersection': need(phase_hit and product_hit,f'phase/product intersection {r["review_id"]}')
   elif alignment=='requirement_role_phase_nonintersection_explicit': need(role=='requirement' and not phase_hit and product_hit,f'requirement phase nonintersection {r["review_id"]}')
   else: need(alignment=='requirement_role_exact_contract_phase_intersection_not_semantic_basis' and role=='requirement' and phase_hit and product_hit,f'requirement phase intersection {r["review_id"]}')
   p=AR/z['source_path'];need(hashlib.sha256(p.read_bytes()).hexdigest()==r['source_sha256']==manifest[r['source_path']],'archive digest');need(r['legacy_execution_status']=='not_run' and r['current_requirement_implementation_status']=='not_established' and r['consumer_closure_status']=='pending' and not r['consumer_closure_evidence'] and not r['new_build_allowed'],'record state');need(r['covered_requirement_atom_ids']==ids and r['covered_requirement_atoms']==[amap[i] for i in ids],'atom coverage exact');need([(e['line_start'],e['line_end']) for e in r['evidence_refs']]==spans,'span exact')
   texts=[]
   for e in r['evidence_refs']:
    need(e['archive_path']==str(p.relative_to(R)) and e['artifact_role']==role and e['excerpt_status']=='static_read_only' and e['source_requirement_relation']==relation,'evidence metadata');t=excerpt(p,e['line_start'],e['line_end']);need(e['excerpt_sha256']==sha(t.encode()),'excerpt digest');texts.append(t)
   if status=='rejected':need(not ids and not r['evidence_atom_bindings'] and any('covered atoms=0' in q for q in r['counterevidence']),'rejected zero')
   else:
    need(sorted(b['atom_id'] for b in r['evidence_atom_bindings'])==sorted(ids),'binding ids')
    for b in r['evidence_atom_bindings']:
     need(b['atom_id'] in ids and b['evidence_ref_indexes'] and all(0<=i<len(texts) for i in b['evidence_ref_indexes']),'binding refs');joined='\n'.join(texts[i] for i in b['evidence_ref_indexes']);need(all(q in joined for q in b['required_terms']),'binding terms')
     if b['match_mode']=='literal_source_fragment':need(all(f in joined for f in amap[b['atom_id']]['source_fragments']),'literal binding')
     else:need(b['match_mode']=='controlled_term_set_partial' and b['source_fragment_anchors'] and all(q in amap[b['atom_id']]['text'] for q in b['source_fragment_anchors']),'controlled binding')
  agg=next(a for a in meta['unit_aggregates'] if a['unit_candidate_id']==unit);need(agg['product_scope']==['HELIX-HARNESS'] and agg['reviewed_edge_count']==3 and agg['atom_coverage_receipt']==expected_cov(unit,rows),'aggregate coverage');need(agg['semantic_link_counts']=={s:sum(r['unit_candidate_id']==unit and r['semantic_link_status']==s for r in rows) for s in ('confirmed','rejected','unresolved')},'aggregate statuses');need(agg['phase_authority_status']=='candidate_unchanged' and agg['current_requirement_implementation_status']=='not_established' and agg['legacy_requirement_implementation_status']=='unknown_pending_direct_asset_semantic_review' and not agg['direct_confirmed_implementation_asset_ids'] and agg['consumer_closure_status']=='pending' and not agg['new_build_allowed'],'aggregate state')
 need(meta['semantic_link_counts']=={'confirmed':4,'rejected':3,'unresolved':2},'batch statuses');docs='\n'.join(p.read_text() for p in (STATUS,METHOD,PREMISE,RESPONSE));assets={x[0] for d in U.values() for x in d['roles'].values()};need(all(a in PREMISE.read_text() and a in RESPONSE.read_text() for a in assets) and 'LEGACY-ASSET-33E80E6D11CC51ADA817' in docs,'document assets');need('{BATCH}' not in docs and '{REV}' not in docs and 'confirmed 4 / rejected 3 / unresolved 2' in STATUS.read_text() and '12 atom' in RESPONSE.read_text() and '183 units remaining' in STATUS.read_text(),'document counts');need('runtime、test、hook、CI、adapterは実行していない' in METHOD.read_text() and 'candidate membershipはsemantic evidenceではない' in STATUS.read_text() and '独立review待ち' in RESPONSE.read_text(),'document boundary')
 print('legacy requirement direct semantic review wave12: schema10 / 9 edges / 12 atoms / confirmed4 rejected3 unresolved2 / cumulative35 units 105 edges remaining183 / full static verification passed')
if __name__=='__main__':
 try:main()
 except Exception as e:print('FAIL:',e);sys.exit(1)
