#!/usr/bin/env python3
"""Wave13 schema10 full static verifier; archive assets are read, never executed."""
from pathlib import Path
import hashlib,json,re,subprocess,sys
R=Path(__file__).resolve().parents[3]; G=R/'docs/governance'; A=G/'audits/source-rebaseline'; AR=R/'archive/legacy-generation-2026-09-14/root'
REV='9061b51a1e0b4a898dcfd568891335cbb33bc135'; BATCH='LEGACY-SEMANTIC-WAVE13-2026-09-21'
L=G/'legacy-requirement-direct-semantic-review-wave13.jsonl'; M=G/'legacy-requirement-direct-semantic-review-wave13.meta.json'; STATUS=A/'legacy-requirement-direct-semantic-review-wave13-status-2026-09-21.md'; METHOD=A/'legacy-requirement-direct-semantic-review-wave13-method-2026-09-21.md'; PREMISE=A/'legacy-requirement-direct-semantic-review-wave13-premise-packet-2026-09-21.md'; RESPONSE=A/'legacy-requirement-direct-semantic-review-wave13-review-response-2026-09-21.md'
CAT=G/'legacy-asset-phase-product-classification-bootstrap.jsonl'; CROSS=G/'legacy-requirement-implementation-crosswalk-bootstrap.jsonl'; DECOMP=G/'legacy-ir-product-unit-decomposition-bootstrap.jsonl'; PHASE=G/'phase-capability-inventory.json'; MAN=R/'archive/legacy-generation-2026-09-14/MANIFEST.sha256'; PRIOR=[(G/f'legacy-requirement-direct-semantic-review-wave{n}.jsonl',G/f'legacy-requirement-direct-semantic-review-wave{n}.meta.json') for n in range(1,13)]
ROLE={
'agent_review_pair':'automated execution and independent audit pairing','event_alternation':'alternating PR and harness event coordination','shared_human_gate':'shared post-approval precondition','os_unattended_run':'OS unattended execution outside irreversible boundary','shared_completion_boundary':'shared unattended completion boundary','hook_detection':'Claude hook PR lifecycle detection','idempotent_audit_job':'idempotent audit job generation','all_base_branches':'all base branch inclusion','stacked_pr_inclusion':'stacked PR inclusion','completion_actor':'completion actor and trigger','raw_execution_log':'raw execution log exclusion','pr_evidence':'PR evidence compaction','test_ci_evidence':'test and CI evidence compaction','audit_finding_evidence':'audit finding compaction','durable_memory_promotion':'durable knowledge promotion','continuation_separation':'progress and durable memory separation'}
def atom(i,k,s,t,f,shared=()):
 return {'atom_id':i,'boundary_review_state':'product_boundary_pending_human_decision','kind':k,'responsibility_role':ROLE[k],'shared_with_units':list(shared),'source_fragments':[f],'subject':s,'text':t}
U={
'IRUNIT-HIL-BR-01-HELIX-OS':{'phases':['PHCAP-10','PHCAP-12','PHCAP-13'],'atoms':[atom('BR01-OS-A01','agent_review_pair','Codex自動走行／Claude Code監査','Codex自動走行とClaude Code監査を','Codex自動走行とClaude Code監査を'),atom('BR01-OS-A02','event_alternation','PR／harness.db event','PRとharness.db eventで交互に接続し','PRとharness.db eventで交互に接続し'),atom('BR01-OS-A03','shared_human_gate','人のL3承認','人のL3承認後','人のL3承認後',['IRUNIT-HIL-BR-01-HELIX-HARNESS']),atom('BR01-OS-A04','os_unattended_run','HELIX-OS自動走行','不可逆境界以外を無人完走','は不可逆境界以外を無人完走'),atom('BR01-OS-A05','shared_completion_boundary','不可逆境界','不可逆境界以外を無人完走する','不可逆境界以外を無人完走する',['IRUNIT-HIL-BR-01-HELIX-HARNESS'])],'connective':[],'anchors':['Codex','Claude','PR','review'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(2,12)],['BR01-OS-A01','BR01-OS-A02','BR01-OS-A03','BR01-OS-A04','BR01-OS-A05'],'requirement_role_phase_nonintersection_explicit'),'design':('LEGACY-ASSET-F35F343229FA2B08B3E0','design','unresolved','design_contract_evidence',[(1,65),(99,105)],['BR01-OS-A01','BR01-OS-A02'],'phase_and_product_candidate_intersection'),'implementation':('LEGACY-ASSET-13BA93ADBFD33682AF62','implementation_source','rejected','implementation_candidate_rejected',[(9,20)],[],'phase_and_product_candidate_intersection')}},
'IRUNIT-HIL-BR-02-HELIX-OS':{'phases':['PHCAP-10','PHCAP-12'],'atoms':[atom('BR02-OS-A01','hook_detection','Claude Code拡張hook','Claude Code拡張hookはCodexのPR作成/更新/完了を検出し','Claude Code拡張hookはCodexのPR作成/更新/完了を検出し'),atom('BR02-OS-A02','idempotent_audit_job','監査job','監査jobを冪等生成する','監査jobを冪等生成する'),atom('BR02-OS-A03','all_base_branches','全base branch','全base branchのPRを対象とし','全base branchのPRを対象とし'),atom('BR02-OS-A04','stacked_pr_inclusion','stacked PR','stacked PRを除外しない','stacked PRを除外しない')],'connective':[],'anchors':['Claude','PR','hook','audit'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(45,55)],['BR02-OS-A01','BR02-OS-A02','BR02-OS-A03','BR02-OS-A04'],'requirement_role_phase_nonintersection_explicit'),'design':('LEGACY-ASSET-4305445847D8D431F684','plan','unresolved','design_candidate_unresolved',[(108,132)],['BR02-OS-A01','BR02-OS-A02'],'phase_and_product_candidate_intersection'),'implementation':('LEGACY-ASSET-AC2078FFF049D6B56D19','implementation_source','unresolved','partial_implementation_behavior_evidence_unexecuted',[(248,280),(367,395)],['BR02-OS-A01','BR02-OS-A02'],'classification_conflict_product_nonintersection')}},
'IRUNIT-HIL-BR-03-HELIX-OS':{'phases':['PHCAP-19','PHCAP-20'],'atoms':[atom('BR03-OS-A01','completion_actor','Claude Code／Codex完了','Claude CodeはCodex完了時に','Claude CodeはCodex完了時に'),atom('BR03-OS-A02','raw_execution_log','raw実行ログ','raw実行ログ','raw実行ログ'),atom('BR03-OS-A03','pr_evidence','PR','PR','PR'),atom('BR03-OS-A04','test_ci_evidence','test/CI','test/CI','test/CI'),atom('BR03-OS-A05','audit_finding_evidence','監査所見','監査所見を圧縮し','監査所見を圧縮し'),atom('BR03-OS-A06','durable_memory_promotion','永続知識／harness memory','永続知識だけをharness memoryへ昇格する','永続知識だけをharness memoryへ昇格する'),atom('BR03-OS-A07','continuation_separation','DB continuation','進捗はDB continuationへ残しmemoryへ混載しない','進捗はDB continuationへ残しmemoryへ混載しない')],'connective':[],'anchors':['memory','completion','continuation','raw'],'roles':{'requirement':('LEGACY-ASSET-A60CF91DD2AF6693E6F9','requirement','confirmed','same_requirement_id_exact_source_contract_not_implementation',[(88,98)],['BR03-OS-A01','BR03-OS-A02','BR03-OS-A03','BR03-OS-A04','BR03-OS-A05','BR03-OS-A06','BR03-OS-A07'],'requirement_role_exact_contract_phase_intersection_not_semantic_basis'),'design':('LEGACY-ASSET-256C9F8C3029B185B151','design','unresolved','design_contract_evidence',[(31,35),(41,52),(335,336)],['BR03-OS-A02','BR03-OS-A06','BR03-OS-A07'],'phase_and_product_candidate_intersection'),'implementation':('LEGACY-ASSET-110202C8AB8053B3BBF2','implementation_source','unresolved','partial_implementation_behavior_evidence_unexecuted',[(15,31),(59,72)],['BR03-OS-A06'],'phase_and_product_candidate_intersection')}}}
FIELDS={'artifact_evidence_kind','asset_id','authority_effect','batch_id','bounded_search_query','candidate_membership_semantics','candidate_phase_targets','candidate_product_targets','catalog_legacy_implementation_status','classification_id','consumer_closure_evidence','consumer_closure_status','counterevidence','coverage','covered_requirement_atom_ids','covered_requirement_atoms','current_requirement_implementation_status','evidence_atom_bindings','evidence_refs','legacy_asset_evidence_state','legacy_execution_status','legacy_requirement_implementation_contribution','new_build_allowed','observed_consumer_refs','phase_authority_status','phase_candidates','product_alignment_status','product_scope','review_id','review_scope','role_kind','schema_revision','selection_route','semantic_link_status','semantic_relation','source_path','source_requirement_id','source_sha256','source_statement_semantic_digest','source_text_spans','unit_candidate_id','unresolved'}
def need(x,s):
 if not x:raise AssertionError(s)
def sha(b):return 'sha256:'+hashlib.sha256(b).hexdigest()
def canon(x):return sha(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
def jl(p):return [json.loads(x) for x in p.read_text().splitlines() if x.strip()]
def excerpt(path,a,b):
 ls=path.read_text(errors='replace').splitlines();need(1<=a<=b<=len(ls),f'line bounds {path}:{a}-{b}');return '\n'.join(ls[a-1:b])+'\n'
def token(a,t):
 if re.fullmatch(r'[A-Za-z0-9_/-]+',a):return any((m.start()==0 or not t[m.start()-1].isalnum()) and (m.end()==len(t) or not t[m.end()].isalnum()) for m in re.finditer(re.escape(a),t))
 return a in t
def expected_cov(unit,rows):
 d=U[unit];ids=[a['atom_id'] for a in d['atoms']];rs=[r for r in rows if r['unit_candidate_id']==unit];shared=sorted(a['atom_id'] for a in d['atoms'] if a['shared_with_units']);exclusive=sorted(set(ids)-set(shared));dcon=sorted({x for r in rs if r['role_kind']=='design' and r['semantic_link_status']=='confirmed' for x in r['covered_requirement_atom_ids']});dun=sorted({x for r in rs if r['role_kind']=='design' and r['semantic_link_status']=='unresolved' for x in r['covered_requirement_atom_ids']});iun=sorted({x for r in rs if r['role_kind']=='implementation' and r['semantic_link_status']=='unresolved' for x in r['covered_requirement_atom_ids']});z={'atom_inventory':d['atoms'],'connective_fragments':d['connective'],'contract_confirmed_atom_ids':ids,'design_confirmed_atom_ids':dcon,'design_unresolved_atom_ids':dun,'design_rejected_asset_ids':sorted(r['asset_id'] for r in rs if r['role_kind']=='design' and r['semantic_link_status']=='rejected'),'design_partial_pending_kind_atom_ids':[],'implementation_confirmed_atom_ids':[],'implementation_unresolved_atom_ids':iun,'implementation_rejected_atom_ids':[],'implementation_rejected_asset_ids':sorted(r['asset_id'] for r in rs if r['role_kind']=='implementation' and r['semantic_link_status']=='rejected'),'implementation_uncovered_atom_ids':sorted(set(ids)-set(iun)),'no_evidence_atom_ids':sorted(set(ids)-set(dcon)-set(dun)-set(iun)),'shared_atom_ids':shared,'product_exclusive_atom_ids':exclusive}
 for k in list(z):z[k+'_sha256']=canon(z[k])
 z.update({'contract_semantic_edge_coverage_complete':True,'semantic_edge_coverage_complete':False,'no_shared_source_span':not shared,'product_boundary_decision_complete':False,'product_exclusive_contract_coverage_complete':True});return z
def main():
 rows=jl(L);meta=json.loads(M.read_text());cat={x['asset_id']:x for x in jl(CAT)};cross={x['unit_candidate_id']:x for x in jl(CROSS)};dec={u['unit_candidate_id']:u for x in jl(DECOMP) for u in x['candidate_units']};manifest={x.split('  ',1)[1]:x.split('  ',1)[0] for x in MAN.read_text().splitlines() if '  ' in x};st=STATUS.read_text();expected_phase_rows=[]
 need(len(cat)==4020,'catalog count');need(set(meta)=={'authority_effect','batch_id','bounded_search_receipts','consumer_closure_status','cumulative_reviewed_edge_count','cumulative_reviewed_unit_count','inputs','legacy_execution_performed','new_build_allowed','output_sha256','parent_revision','prior_review_batches','record_count','reviewed_edges','reviewed_unit_ids','schema_revision','semantic_link_counts','source_revision','status','unit_aggregates'},'meta fields');need(meta['schema_revision']==10 and meta['batch_id']==BATCH and meta['parent_revision']==REV,'meta identity');need(meta['record_count']==len(rows)==9 and meta['output_sha256']==sha(L.read_bytes()),'ledger digest');need(meta['authority_effect']=='none' and meta['status']=='research_premise_candidate' and meta['consumer_closure_status']=='pending' and not meta['legacy_execution_performed'] and not meta['new_build_allowed'],'authority boundary');need(meta['reviewed_unit_ids']==list(U) and meta['cumulative_reviewed_unit_count']==38 and meta['cumulative_reviewed_edge_count']==114,'unit/count')
 inputs=[MAN,CAT,CROSS,DECOMP,PHASE]+[p for pair in PRIOR for p in pair];need(meta['inputs']=={str(p.relative_to(R)):sha(p.read_bytes()) for p in inputs},'input digests')
 for p in inputs:need(sha(subprocess.run(['git','show',f'{REV}:{p.relative_to(R)}'],cwd=R,check=True,capture_output=True).stdout)==sha(p.read_bytes()),f'parent blob {p}')
 prioru=set();priore=set();priorassets=set();pb=[]
 for lp,mp in PRIOR:
  old=jl(lp);om=json.loads(mp.read_text());prioru|=set(om['reviewed_unit_ids']);priore|={(x['unit_candidate_id'],x['asset_id']) for x in om['reviewed_edges']};priorassets|={x['asset_id'] for x in old if x['artifact_evidence_kind'] in {'design','plan','implementation_source'}};pb.append({'batch_id':om['batch_id'],'ledger_sha256':sha(lp.read_bytes()),'meta_sha256':sha(mp.read_bytes())})
 edges={(r['unit_candidate_id'],r['asset_id']) for r in rows};expected={(u,x[0]) for u,d in U.items() for x in d['roles'].values()};selected={x[0] for d in U.values() for role,x in d['roles'].items() if role!='requirement'};need(meta['prior_review_batches']==pb and not edges&priore and not selected&priorassets,'prior overlap');need(edges==expected and len(prioru|set(U))==38 and len(priore|edges)==114,'edge/cumulative exact');need(meta['reviewed_edges']==[{'unit_candidate_id':r['unit_candidate_id'],'asset_id':r['asset_id']} for r in rows],'edge order')
 by={(r['unit_candidate_id'],r['role_kind']):r for r in rows};need(len(by)==9,'unique unit roles');need([r['review_id'] for r in rows]==[f'LSRW13-EDGE-{i:03d}' for i in range(1,10)],'review ids')
 for unit,d in U.items():
  c=cross[unit];du=dec[unit];need(c['product_scope']==['HELIX-OS'] and du['product_target']=='HELIX-OS' and all(x.get('review_state')=='product_boundary_pending_human_decision' for x in du.get('shared_source_overlaps',[])),'product/shared');overlaps=sorted(x['source_text'] for x in du.get('shared_source_overlaps',[]));shared_frags=sorted(f for a in d['atoms'] if a['shared_with_units'] for f in a['source_fragments']);need(overlaps==shared_frags and all(a['shared_with_units']==['IRUNIT-HIL-BR-01-HELIX-HARNESS'] for a in d['atoms'] if a['shared_with_units']),'shared atom mapping');need(c['direct_phase_candidates']==d['phases'],'unit phases');frags=[f for a in d['atoms'] for f in a['source_fragments']];need(len(frags)==len(set(frags)) and all(sum(f in s for s in c['source_text_spans'])==1 for f in frags),'atom fragment placement');need(set(d['connective'])<= {'と'} and len(d['connective'])==len(set(d['connective'])) and not set(d['connective'])&set(frags),'connective allowlist')
  expected_phase_rows.extend('| '+' | '.join([unit,'HELIX-OS',p['phase_id'],p['current_status'],p['legacy_capability_status'],p['transition_assessment']])+' |' for p in c['phase_capability_evidence'])
  for s in c['source_text_spans']:
   rem=s
   for f in frags:
    if f in rem:rem=rem.replace(f,'')
   for x in d['connective']:rem=rem.replace(x,'')
   need(not re.sub(r'[\s。、・|`]','',rem),f'atom loss {unit}: {rem}')
  search=sorted(a for a,z in cat.items() if any(token(q,(AR/z['source_path']).read_text(errors='replace')) for q in d['anchors']));rec=meta['bounded_search_receipts'][unit];sel=sorted(x[0] for x in d['roles'].values());rest=sorted(set(search)-set(sel));need(rec=={'query':{'match_mode':'archive_file_contains_any_utf8_anchor','anchors':d['anchors']},'catalog_record_count':4020,'candidate_asset_count':len(search),'candidate_asset_ids_sha256':canon(search),'selected_asset_ids':sel,'unreviewed_asset_count':len(rest),'unreviewed_asset_ids_sha256':canon(rest)},f'search receipt {unit}');need(set(sel)<=set(search),f'selected outside search {unit}')
  amap={a['atom_id']:a for a in d['atoms']}
  for role,x in d['roles'].items():
   aid,kind,status,relation,spans,ids,alignment=x;r=by[(unit,role)];z=cat[aid];need(set(r)==FIELDS,f'row fields {r["review_id"]}');need(r['asset_id']==aid and r['artifact_evidence_kind']==kind and r['semantic_link_status']==status and r['semantic_relation']==relation and r['product_alignment_status']==alignment,'role result');need(r['schema_revision']==10 and r['batch_id']==BATCH and r['authority_effect']=='none' and r['selection_route']=='bounded_global_search' and r['candidate_membership_semantics']=='bounded_global_search_candidate_only_not_semantic_evidence','row boundary');need(r['bounded_search_query']==rec['query'] and r['phase_candidates']==d['phases'] and r['product_scope']==['HELIX-OS'],'row unit exact');need(r['source_requirement_id']==c['source_requirement_id'] and r['source_statement_semantic_digest']==c['source_statement_semantic_digest'] and r['source_text_spans']==c['source_text_spans'],'crosswalk exact');need(all(r[o]==z[s] for o,s in {'artifact_evidence_kind':'artifact_evidence_kind','classification_id':'classification_id','source_path':'source_path','source_sha256':'source_sha256','candidate_phase_targets':'candidate_phase_targets','candidate_product_targets':'candidate_product_targets','legacy_asset_evidence_state':'implementation_evidence_state','catalog_legacy_implementation_status':'legacy_implementation_status','observed_consumer_refs':'consumer_refs'}.items()),f'catalog exact {r["review_id"]}')
   phase_hit=bool(set(d['phases'])&set(z['candidate_phase_targets'])); product_hit='HELIX-OS' in z['candidate_product_targets']
   if alignment=='classification_conflict_phase_product_nonintersection': need(not phase_hit and not product_hit and z['candidate_product_targets']==[],f'classification conflict exact {r["review_id"]}')
   elif alignment=='classification_conflict_product_nonintersection': need(phase_hit and not product_hit and z['candidate_product_targets']==[],f'classification product conflict exact {r["review_id"]}')
   elif alignment=='phase_and_product_candidate_intersection': need(phase_hit and product_hit,f'phase/product intersection {r["review_id"]}')
   elif alignment=='requirement_role_phase_nonintersection_explicit': need(role=='requirement' and not phase_hit and product_hit,f'requirement phase nonintersection {r["review_id"]}')
   else: need(alignment=='requirement_role_exact_contract_phase_intersection_not_semantic_basis' and role=='requirement' and phase_hit and product_hit,f'requirement phase intersection {r["review_id"]}')
   p=AR/z['source_path'];need(hashlib.sha256(p.read_bytes()).hexdigest()==r['source_sha256']==manifest[r['source_path']],'archive digest');need(r['legacy_execution_status']=='not_run' and r['current_requirement_implementation_status']=='not_established' and r['consumer_closure_status']=='pending' and not r['consumer_closure_evidence'] and not r['new_build_allowed'],'record state');need(r['covered_requirement_atom_ids']==ids and r['covered_requirement_atoms']==[amap[i] for i in ids],'atom coverage exact');need([(e['line_start'],e['line_end']) for e in r['evidence_refs']]==spans,'span exact')
   if status in {'confirmed','unresolved'}:
    need(r['counterevidence'] and all(isinstance(q,str) and q.strip() for q in r['counterevidence']),f'bounded counterevidence {r["review_id"]}')
    if role=='requirement':need(any('実装・実行証拠ではない' in q for q in r['counterevidence']) and any('consumer closure未確認' in q for q in r['counterevidence']),f'requirement limits {r["review_id"]}')
    if role=='design':need(any('実装・実行証拠ではない' in q for q in r['counterevidence']),f'design limits {r["review_id"]}')
   texts=[]
   for e in r['evidence_refs']:
    need(e['archive_path']==str(p.relative_to(R)) and e['artifact_role']==role and e['excerpt_status']=='static_read_only' and e['source_requirement_relation']==relation,'evidence metadata');t=excerpt(p,e['line_start'],e['line_end']);need(e['excerpt_sha256']==sha(t.encode()),'excerpt digest');texts.append(t)
   if status=='rejected':need(not ids and not r['evidence_atom_bindings'] and any('covered atoms=0' in q for q in r['counterevidence']),'rejected zero')
   else:
    need(sorted(b['atom_id'] for b in r['evidence_atom_bindings'])==sorted(ids),'binding ids')
    for b in r['evidence_atom_bindings']:
     need(b['atom_id'] in ids and b['evidence_ref_indexes'] and all(0<=i<len(texts) for i in b['evidence_ref_indexes']),'binding refs');joined='\n'.join(texts[i] for i in b['evidence_ref_indexes']);need(all(q in joined for q in b['required_terms']),'binding terms')
     if b['match_mode']=='literal_source_fragment':need(all(f in joined for f in amap[b['atom_id']]['source_fragments']),'literal binding')
     else:need(b['match_mode']=='controlled_term_set_partial' and b['source_fragment_anchors'] and all(q in amap[b['atom_id']]['text'] for q in b['source_fragment_anchors']),'controlled binding')
   if role=='design' and status=='confirmed':need(kind=='design' and relation=='design_contract_evidence' and ids and r['legacy_requirement_implementation_contribution']=='design_contract_only_no_implementation_claim' and all(b['match_mode']=='controlled_term_set_partial' and b['required_terms'] and b['source_fragment_anchors'] for b in r['evidence_atom_bindings']) and any('consumer closure未確認' in q for q in r['counterevidence']),'design confirmed gate')
  agg=next(a for a in meta['unit_aggregates'] if a['unit_candidate_id']==unit);cov=expected_cov(unit,rows);need(agg['product_scope']==['HELIX-OS'] and agg['reviewed_edge_count']==3 and agg['atom_coverage_receipt']==cov,'aggregate coverage');need(agg['semantic_link_counts']=={s:sum(r['unit_candidate_id']==unit and r['semantic_link_status']==s for r in rows) for s in ('confirmed','rejected','unresolved')},'aggregate statuses');need(agg['phase_authority_status']=='candidate_unchanged' and agg['current_requirement_implementation_status']=='not_established' and agg['legacy_requirement_implementation_status']=='unknown_pending_direct_asset_semantic_review' and not agg['direct_confirmed_implementation_asset_ids'] and agg['consumer_closure_status']=='pending' and not agg['new_build_allowed'],'aggregate state')
  status_values=[unit,len(cov['atom_inventory']),len(cov['contract_confirmed_atom_ids']),len(cov['design_confirmed_atom_ids']),len(cov['design_unresolved_atom_ids']),len(cov['design_rejected_asset_ids']),len(cov['design_partial_pending_kind_atom_ids']),len(cov['implementation_confirmed_atom_ids']),len(cov['implementation_unresolved_atom_ids']),len(cov['implementation_rejected_asset_ids']),len(cov['implementation_uncovered_atom_ids']),len(cov['no_evidence_atom_ids'])];need('| '+' | '.join(map(str,status_values))+' |' in STATUS.read_text(),f'status aggregate row {unit}')
 actual_phase_rows=[line for line in st.splitlines() if line.startswith('| IRUNIT-') and len(line.split('|'))==8];need(actual_phase_rows==expected_phase_rows,'status phase rows exact')
 need(meta['semantic_link_counts']=={'confirmed':3,'rejected':1,'unresolved':5},'batch statuses');docs='\n'.join(p.read_text() for p in (STATUS,METHOD,PREMISE,RESPONSE));assets={x[0] for d in U.values() for x in d['roles'].values()};need(all(a in PREMISE.read_text() and a in RESPONSE.read_text() for a in assets),'document assets');need('{BATCH}' not in docs and '{REV}' not in docs and 'confirmed 3 (contract 3 / design 0) / rejected 1 / unresolved 5' in st and '16 atom' in RESPONSE.read_text() and '180 units remaining' in st,'document counts');need('| unit | atoms | contract | design confirmed | design unresolved |' in st,'document design split');need('runtime、test、hook、CI、adapterは実行していない' in METHOD.read_text() and 'candidate membershipはsemantic evidenceではない' in st,'document boundary')
 print('legacy requirement direct semantic review wave13: schema10 / 9 edges / 16 atoms / confirmed3 rejected1 unresolved5 / cumulative38 units 114 edges remaining180 / full static verification passed')
if __name__=='__main__':
 try:main()
 except Exception as e:print('FAIL:',e);sys.exit(1)
