import { join } from "node:path";
import type { GeneratedFile } from "./index";

export type TemplateSet = { [name: string]: string };

const CLAUDE_AGENT_TEMPLATES = [
  ["be-api", "Backend API の route / contract / integration を確認するレビュアー。"],
  ["be-logic", "Backend domain logic の invariant / boundary / TDD 適合を確認するレビュアー。"],
  ["code-reviewer", "正しさ、security、保守性を確認する read-only senior engineering レビュアー。"],
  ["db-schema", "Database schema の migration / index / data contract を確認するレビュアー。"],
  ["devops-deploy", "CI、deployment、rollback、release readiness を確認するレビュアー。"],
  [
    "pdm-innovation-manager",
    "機会、scope、portfolio fit を確認する product management レビュアー。",
  ],
  [
    "pdm-marketing-innovation",
    "市場性、user value、product framing、adoption を確認するレビュアー。",
  ],
  [
    "pdm-tech-innovation",
    "実現可能性、platform leverage、risk を確認する technical product レビュアー。",
  ],
  ["pmo-haiku", "簡潔な status、blocker、next action を確認する lightweight PMO レビュアー。"],
  ["pmo-project-explorer", "goal、制約、evidence gap を確認する project discovery レビュアー。"],
  [
    "pmo-project-scout",
    "backlog、ownership、workflow routing を確認する project triage レビュアー。",
  ],
  ["pmo-sonnet", "PLAN 構造、handover 品質、文書間整合を確認する PMO レビュアー。"],
  ["pmo-tech-docs", "ADR、process、governance 品質を確認する technical documentation レビュアー。"],
  ["pmo-tech-fork", "fork、extraction、distribution の clean-room 境界を確認するレビュアー。"],
  [
    "pmo-tech-news",
    "外部 signal と日付付き source check を確認する technical research レビュアー。",
  ],
  ["qa-test", "test strategy、oracle 強度、regression scope を確認する quality レビュアー。"],
  ["refactor-scout", "複雑度、重複、低 risk extraction 候補を確認する refactoring レビュアー。"],
  ["security-audit", "auth、secret、PII、threat model concern を確認する security レビュアー。"],
  ["helix-tl", "HELIX workflow、gate、test、release readiness を確認する TL レビュアー。"],
] as const;

const CLAUDE_COMMAND_TEMPLATES = [
  ["build", "freeze 済み HELIX spec / test design に沿って実装する。"],
  ["code-simplify", "選択した code に対する最小で安全な単純化を特定する。"],
  ["sdd-plan", "実装前に HELIX の spec-driven planning document を作成する。"],
  ["sdd-review", "HELIX trace / gate 要求に照らして spec / design をレビューする。"],
  ["ship", "release evidence、rollback note、最終検証を準備する。"],
  ["spec", "実装前に spec-first design を作成する。"],
  ["test", "現在の変更に対して targeted HELIX verification を実行する。"],
] as const;

export const CONSUMER_CLAUDE_AGENT_NAMES = CLAUDE_AGENT_TEMPLATES.map(([name]) => name);

export const CONSUMER_CLAUDE_COMMAND_NAMES = [
  ...CLAUDE_COMMAND_TEMPLATES.map(([name]) => name),
  "helix-status",
  "helix-test",
];

export const CONSUMER_TEAM_DEFINITION_PATH = ".helix/teams/default-hybrid.yaml";

function agentTemplate(name: string, description: string): string {
  return [
    "---",
    `name: ${name}`,
    `description: ${description}`,
    "tools: Read, Grep, Glob, Bash",
    "---",
    "",
    "現在の repository に対して、consumer-safe な HELIX subagent として振る舞う。",
    "",
    "必須 baseline:",
    "- `AGENTS.md`、`CLAUDE.md`、`.claude/CLAUDE.md` が存在する場合は読む。",
    "- PLAN-M-02 で CLI 名と state dir が変更されるまでは、HELIX local state evidence は `.helix` 配下を正本とし、`helix status`、`helix completion decision-packet --json`、`helix completion review-bundle --json`、`helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json`、`helix doctor --profile consumer` を使う。completion review-bundle は exact digest と semantic digest の両方を確認する。",
    "- summary より先に findings を出し、file / command evidence を添える。",
    "- secret、credential、PII、machine-local absolute path を書かない。",
    "- user が明示的に実装を求めない限り read-only review を優先する。",
    "",
  ].join("\n");
}

function commandTemplate(name: string, description: string): string {
  return [
    "---",
    `description: ${description}`,
    'argument-hint: "<target>"',
    "---",
    "",
    `Command: ${name}`,
    "",
    "対象: $ARGUMENTS",
    "",
    "note: PLAN-M-02 承認前は `helix` alias ではなく、現行 `helix` CLI だけで repository-local の HELIX lifecycle を扱う。最初に `helix status --json`、`helix completion decision-packet --json`、`helix completion review-bundle --json`、`helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json` を実行し、completion review-bundle の exact digest と semantic digest を確認する。対象に必要な narrow verification を走らせ、workflow または gate behavior に影響する場合は `helix doctor --profile consumer` で閉じる。",
    "",
  ].join("\n");
}

const CLAUDE_AGENT_TEMPLATE_SET: TemplateSet = Object.fromEntries(
  CLAUDE_AGENT_TEMPLATES.map(([name, description]) => [
    `adapter/.claude/agents/${name}.md`,
    agentTemplate(name, description),
  ]),
);

const CLAUDE_COMMAND_TEMPLATE_SET: TemplateSet = Object.fromEntries(
  CLAUDE_COMMAND_TEMPLATES.map(([name, description]) => [
    `adapter/.claude/commands/${name}.md`,
    commandTemplate(name, description),
  ]),
);

const CLAUDE_AGENT_FILES: { template: string; file: GeneratedFile }[] = CLAUDE_AGENT_TEMPLATES.map(
  ([name]) => ({
    template: `adapter/.claude/agents/${name}.md`,
    file: {
      path: join(".claude", "agents", `${name}.md`),
      category: "A",
      purpose: `Claude subagent template: ${name}`,
    },
  }),
);

const CLAUDE_COMMAND_FILES: { template: string; file: GeneratedFile }[] =
  CLAUDE_COMMAND_TEMPLATES.map(([name]) => ({
    template: `adapter/.claude/commands/${name}.md`,
    file: {
      path: join(".claude", "commands", `${name}.md`),
      category: "A",
      purpose: `Claude slash command template: ${name}`,
    },
  }));

export const BUILTIN_GITHUB_TEMPLATES: TemplateSet = {
  ...CLAUDE_AGENT_TEMPLATE_SET,
  ...CLAUDE_COMMAND_TEMPLATE_SET,
  "adapter/AGENTS.md": [
    "<!-- HELIX:managed:start -->",
    "# HELIX アダプター",
    "",
    "この project は HELIX lifecycle を現行 `helix` command で扱う。PLAN-M-02 で atomic identifier migration が行われるまでは、CLI 名は `helix` のまま扱う。",
    "",
    "PO への進捗報告・調査結論・確認依頼など chat 出力は日本語を既定とする。docs / handover / adapter prose も日本語を基本とし、CLI 名・識別子・技術用語は原語のまま扱ってよい。",
    "",
    "- 状態確認: `helix status`",
    "- 完了判定 packet 確認: `helix completion decision-packet --json`",
    "- 完了 review bundle 確認: `helix completion review-bundle --json` (exact digest と semantic digest を確認)",
    "- Version-up dry-run: `helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json`",
    "- 診断: `helix doctor --profile consumer`",
    "- rename packet 確認: `helix rename plan --json`",
    "- 引き継ぎ: `helix handover`",
    '- Codex 委譲: `helix codex --role <role> --task "..."`',
    '- Claude 委譲: `helix claude --role <role> --task "..."`',
    "- チーム dry-run: `helix team run --definition .helix/teams/default-hybrid.yaml --mode hybrid --json`",
    "",
    "この managed block の外側にある project-owned instruction は consumer 側の所有物として扱い、勝手に上書きしない。",
    "<!-- HELIX:managed:end -->",
    "",
  ].join("\n"),
  "adapter/CLAUDE.md": [
    "<!-- HELIX:managed:start -->",
    "# HELIX 共有コンテキスト",
    "",
    "harness state と delegation には repository-local の現行 `helix` command を使う。PLAN-M-02 までは command 名を `helix` とする。",
    "",
    "PO への進捗報告・調査結論・確認依頼など chat 出力は日本語を既定とする。docs / handover / adapter prose も日本語を基本とし、CLI 名・識別子・技術用語は原語のまま扱ってよい。",
    "",
    "- `helix status` は local runtime mode を報告する。",
    "- `helix completion decision-packet --json` は completionClaimAllowed=false と未完了 blocker queue を確認する。",
    "- `helix completion review-bundle --json` は S4 / version-up / rename / action-binding の scoped review packet、exact digest、semantic digest を確認する。",
    "- `helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json` は distribution tag 更新を plan-only / no-write 証跡として確認する。",
    "- `helix doctor --profile consumer` は consumer repo 向け health check を実行する。",
    "- `helix rename plan --json` は PLAN-M-02 承認前の blocked packet を確認する。",
    "- `helix handover` は cross-runtime handover state を読み書きする。",
    '- `helix codex --role <role> --task "..."` は Codex へ委譲する。',
    '- `helix claude --role <role> --task "..."` は Claude へ委譲する。',
    "",
    "adapter doc に secret、token、machine-local absolute path を書かない。",
    "<!-- HELIX:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/CLAUDE.md": [
    "<!-- HELIX:managed:start -->",
    "# Claude runtime アダプター",
    "",
    "Claude Code session の HELIX lifecycle work は、現行 `helix` CLI 経由で扱う。",
    "consumer 側所有の Claude instruction は、この managed block の外側へ追加できる。",
    "PLAN-M-02 で atomic identifier migration が行われるまでは、CLI 名は `helix`、state dir は `.helix` のまま扱う。",
    "",
    "PO への進捗報告・調査結論・確認依頼など chat 出力は日本語を既定とする。docs / handover / adapter prose も日本語を基本とし、CLI 名・識別子・技術用語は原語のまま扱ってよい。",
    "",
    "- セッション証跡: `helix status`、`helix completion decision-packet --json`、`helix completion review-bundle --json` (exact digest と semantic digest を確認)、`helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json`、`helix rename plan --json`、`helix handover`",
    "- 診断: `helix doctor --profile consumer`",
    "- レビュー分離: 可能な場合は別 runtime / model family を使う",
    "",
    "<!-- HELIX:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/settings.json": [
    "{",
    '  "hooks": {',
    '    "PreToolUse": [',
    "      {",
    '        "matcher": "Agent|Task",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook agent-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "agent-guard: subagent allowlist/model enforcement"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "Edit|Write|MultiEdit",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook work-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "work-guard: foreign edit protection"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "Bash",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook git-command-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "git-command-guard: destructive git operation protection"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix session start",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "Edit|Write|MultiEdit|Bash",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook post-tool-use",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix session summary",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "    ,",
    '    "SubagentStop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook subagent-stop",',
    '            "timeout": 5,',
    '            "statusMessage": "agent-slots: release oldest guard slot (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "adapter/.codex/config.toml": ["[features]", "hooks = true", ""].join("\n"),
  "adapter/.codex/hooks.json": [
    "{",
    '  "$comment": "Codex adapter hooks for HELIX. Hosted/API tool surfaces still require explicit `helix guard preflight` before edits because repo-local Codex hooks do not execute there. The CLI name is intentionally unchanged until PLAN-M-02.",',
    '  "hooks": {',
    '    "PreToolUse": [',
    "      {",
    '        "matcher": "spawn_agent|spawn_agents_on_csv",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook agent-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "agent-guard: Codex sub-agent role/model guard"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "apply_patch|write_file",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook work-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "work-guard: foreign edit protection"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "exec_command|local_shell",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook git-command-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "git-command-guard: destructive git operation protection"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix session start",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "apply_patch|write_file|exec_command|local_shell",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix hook post-tool-use",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "helix session summary",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "adapter/.claude/commands/helix-status.md": [
    "---",
    "description: HELIX status / completion packet / doctor 出力を確認する。",
    "---",
    "",
    "`helix status --json`、`helix completion decision-packet --json`、`helix completion review-bundle --json`、`helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json`、`helix doctor --profile consumer` を実行し、HELIX mode、completionClaimAllowed、completion review bundle の exact digest / semantic digest、version-up plan-only 境界、未完了 blocker、hard-gate failure を要約する。",
    "",
  ].join("\n"),
  "adapter/.claude/commands/helix-test.md": [
    "---",
    "description: 現在の変更に対して HELIX verification を実行する。",
    'argument-hint: "<changed area or PLAN id>"',
    "---",
    "",
    "対象: $ARGUMENTS",
    "",
    "最初に `helix status --json`、`helix completion decision-packet --json`、`helix completion review-bundle --json`、`helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json` を確認し、completion review-bundle の exact digest / semantic digest を照合する。narrow Vitest target、`bun run typecheck`、`bun run lint` を実行する。変更が HELIX workflow または gate に影響する場合は `helix doctor --profile consumer` で閉じる。",
    "",
  ].join("\n"),
  "project/.vscode/tasks.json": [
    "{",
    '  "version": "2.0.0",',
    '  "tasks": [',
    "    {",
    '      "label": "HELIX: status",',
    '      "type": "shell",',
    '      "command": "bun run helix status",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: doctor",',
    '      "type": "shell",',
    '      "command": "bun run helix doctor --profile consumer",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: completion decision-packet",',
    '      "type": "shell",',
    '      "command": "bun run helix completion decision-packet --json",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: completion review-bundle",',
    '      "type": "shell",',
    '      "command": "bun run helix completion review-bundle --json",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: version-up dry-run",',
    '      "type": "shell",',
    '      "command": "bun run helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: rename plan",',
    '      "type": "shell",',
    '      "command": "bun run helix rename plan --json",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: handover status",',
    '      "type": "shell",',
    '      "command": "bun run helix handover status --json",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: setup dry-run",',
    '      "type": "shell",',
    '      "command": "bun run helix setup project --dry-run",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: team run dry-run",',
    '      "type": "shell",',
    '      "command": "bun run helix team run --definition .helix/teams/default-hybrid.yaml --mode hybrid --json",',
    '      "problemMatcher": []',
    "    }",
    "  ]",
    "}",
    "",
  ].join("\n"),
  "project/.vscode/settings.json": ["{", '  "task.allowAutomaticTasks": "off"', "}", ""].join("\n"),
  "project/package.json": [
    "{",
    '  "name": "helix-consumer-project",',
    '  "version": "0.0.0",',
    '  "private": true,',
    '  "scripts": {',
    '    "helix": "helix",',
    '    "typecheck": "bun run helix status --json",',
    '    "test": "bun run helix completion review-bundle --json"',
    "  },",
    '  "devDependencies": {',
    '    "typescript": "^5.6.3",',
    '    "helix": "github:RetryYN/HELIX-HARNESS"',
    "  }",
    "}",
    "",
  ].join("\n"),
  "project/.helix/memory/.gitkeep": "",
  "project/.helix/handover/.gitkeep": "",
  "project/.helix/evidence/.gitkeep": "",
  "project/.helix/teams/default-hybrid.yaml": [
    "name: default-hybrid",
    "strategy: sequential",
    "max_parallel: 2",
    "serialization:",
    "  file_conflict: false",
    "  downstream_dependency: true",
    "  shared_state: false",
    "members:",
    "  - role: se",
    "    engine: codex-se",
    "    difficulty: standard",
    "    ownership: 実装対象ファイルを明示し、既存変更を戻さない",
    "    task: HELIX setup 後の対象 slice を実装し、変更ファイルと検証 command を残す",
    "  - role: tl",
    "    engine: pmo-sonnet",
    "    difficulty: standard",
    "    serialize_after: se",
    "    ownership: worker の変更範囲を review し、要求・設計・テストの意味整合を確認する",
    "    task: worker の実装結果を review し、findings-first で gate / test / handover の不足を指摘する",
    "",
  ].join("\n"),
  "common/harness-check.yml": [
    "name: harness-check",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "    branches: [main]",
    "permissions:",
    "  contents: read",
    "jobs:",
    "  harness-check:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "        with:",
    "          persist-credentials: false",
    "      - uses: oven-sh/setup-bun@v2",
    "      - run: bun install --frozen-lockfile",
    "      - name: HELIX CLI dependency",
    "        run: bun run helix --version",
    "      - name: HELIX setup dry-run",
    "        run: bun run helix setup project --dry-run --json",
    "      - name: HELIX status",
    "        run: bun run helix status --json",
    "      - name: HELIX completion decision packet",
    "        run: bun run helix completion decision-packet --json",
    "      - name: HELIX completion review bundle",
    "        run: bun run helix completion review-bundle --json",
    "      - name: HELIX version-up dry-run",
    "        run: bun run helix version-up dry-run --current v0.1.0 --target v0.1.4 --release-remote https://github.com/RetryYN/HELIX-HARNESS-OS.git --json",
    "      - name: HELIX consumer doctor",
    "        run: bun run helix doctor --profile consumer --json",
    "      - name: HELIX rename plan",
    "        run: bun run helix rename plan --json",
    "      - name: Handover route",
    "        run: bun run helix handover status --json",
    "      - name: HELIX team run dry-run",
    "        run: bun run helix team run --definition .helix/teams/default-hybrid.yaml --mode hybrid --json",
    "      - run: bun run typecheck",
    "      - run: bun run test",
    "",
  ].join("\n"),
  "common/commitlint.config.js":
    "module.exports = { extends: ['@commitlint/config-conventional'] };\n",
  "common/escalation-stale.yml": [
    "name: escalation-stale",
    "on:",
    "  schedule:",
    "    - cron: '0 0 * * 1'",
    "permissions:",
    "  contents: read",
    "jobs:",
    "  escalation-audit:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "        with:",
    "          persist-credentials: false",
    "      - uses: oven-sh/setup-bun@v2",
    "      - run: bun install --frozen-lockfile",
    "      - name: Handover route",
    "        run: bun run helix handover status --json",
    "      - name: HELIX completion decision packet",
    "        run: bun run helix completion decision-packet --json",
    "      - name: HELIX completion review bundle",
    "        run: bun run helix completion review-bundle --json",
    "      - name: HELIX consumer doctor",
    "        run: bun run helix doctor --profile consumer --json",
    "",
  ].join("\n"),
  "common/recovery.md": [
    "---",
    "name: Recovery",
    "about: AI 逸脱・暴走・強制停止からの復旧",
    "labels: recovery",
    "---",
    "",
    "## 発生事象",
    "",
    "## root cause",
    "",
    "## 復旧手順 / 再開ポイント",
    "",
    "## 再発防止",
    "",
    "## L14 route",
    "",
  ].join("\n"),
  "common/add-feature.md": [
    "---",
    "name: Add-feature",
    "about: 機能追加",
    "labels: add-feature",
    "---",
    "",
    "## 追加する機能",
    "",
    "## drive",
    "",
    "## 受け入れ条件",
    "",
    "## 上位整合",
    "",
  ].join("\n"),
  "common/PULL_REQUEST_TEMPLATE.md": [
    "## 概要",
    "",
    "## 関連 PLAN / Issue",
    "Closes #",
    "",
    "## V-model artifact",
    "- [ ] ① 設計 (docs/design/)",
    "- [ ] ② 実装 (src/)",
    "- [ ] ③ テスト設計 (docs/test-design/)",
    "- [ ] ④ テストコード (tests/)",
    "",
    "## 検証",
    "- [ ] typecheck pass",
    "- [ ] 全回帰 pass",
    "- [ ] review 前置 通過",
    "",
  ].join("\n"),
  "team/CODEOWNERS": [
    "* {{TL_TEAM}}",
    "/docs/ {{PO_TEAM}}",
    "/src/ {{TL_TEAM}}",
    "/tests/ {{QA_TEAM}}",
    "",
  ].join("\n"),
  "team/setup-branch-protection.sh": [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    'APPROVAL_RECORD="$' + '{HELIX_BRANCH_PROTECTION_APPROVAL_RECORD:-}"',
    'if [[ -z "$' + '{APPROVAL_RECORD}" || ! -f "$' + '{APPROVAL_RECORD}" ]]; then',
    '  echo "action-binding approval record is required before branch protection apply" >&2',
    "  exit 2",
    "fi",
    'grep -q "action_binding_approval_record" "$' + '{APPROVAL_RECORD}"',
    'REPO="$' + '{1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"',
    "gh auth status >/dev/null",
    'gh api -X PUT "repos/$' + '{REPO}/branches/main/protection" \\',
    '  -f "required_status_checks[strict]=true" \\',
    '  -f "required_status_checks[contexts][]=harness-check" \\',
    '  -f "enforce_admins=true" \\',
    '  -f "required_pull_request_reviews[required_approving_review_count]=1" \\',
    '  -f "restrictions="',
    'echo "main の branch protection を適用しました: $' + '{REPO}"',
    "",
  ].join("\n"),
};

export const COMMON_FILES: { template: string; file: GeneratedFile }[] = [
  {
    template: "adapter/AGENTS.md",
    file: {
      path: "AGENTS.md",
      category: "A",
      purpose: "HELIX adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/CLAUDE.md",
    file: {
      path: "CLAUDE.md",
      category: "A",
      purpose: "HELIX shared adapter context (managed block)",
    },
  },
  {
    template: "adapter/.codex/config.toml",
    file: {
      path: join(".codex", "config.toml"),
      category: "A",
      purpose: "Codex project-local hook enablement",
    },
  },
  {
    template: "adapter/.codex/hooks.json",
    file: {
      path: join(".codex", "hooks.json"),
      category: "A",
      purpose: "Codex hook settings for HELIX CLI entrypoints",
    },
  },
  {
    template: "adapter/.claude/CLAUDE.md",
    file: {
      path: join(".claude", "CLAUDE.md"),
      category: "A",
      purpose: "Claude runtime adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/.claude/settings.json",
    file: {
      path: join(".claude", "settings.json"),
      category: "A",
      purpose: "Claude hook settings for HELIX CLI entrypoints",
    },
  },
  ...CLAUDE_AGENT_FILES,
  ...CLAUDE_COMMAND_FILES,
  {
    template: "adapter/.claude/commands/helix-status.md",
    file: {
      path: join(".claude", "commands", "helix-status.md"),
      category: "A",
      purpose: "Claude slash command for HELIX status checks",
    },
  },
  {
    template: "adapter/.claude/commands/helix-test.md",
    file: {
      path: join(".claude", "commands", "helix-test.md"),
      category: "A",
      purpose: "Claude slash command for HELIX verification",
    },
  },
  {
    template: "common/harness-check.yml",
    file: {
      path: join(".github", "workflows", "harness-check.yml"),
      category: "A",
      purpose: "CI (typecheck + regression)",
    },
  },
  {
    template: "common/commitlint.config.js",
    file: { path: "commitlint.config.js", category: "A", purpose: "Conventional Commits" },
  },
  {
    template: "common/escalation-stale.yml",
    file: {
      path: join(".github", "workflows", "escalation-stale.yml"),
      category: "A",
      purpose: "stale escalation issue workflow",
    },
  },
  {
    template: "common/recovery.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "recovery.md"),
      category: "A",
      purpose: "Recovery issue template",
    },
  },
  {
    template: "common/add-feature.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "add-feature.md"),
      category: "A",
      purpose: "Add-feature issue template",
    },
  },
  {
    template: "common/PULL_REQUEST_TEMPLATE.md",
    file: {
      path: join(".github", "PULL_REQUEST_TEMPLATE.md"),
      category: "A",
      purpose: "PR template",
    },
  },
];

export const PROJECT_SETUP_FILES: { template: string; file: GeneratedFile }[] = [
  {
    template: "project/package.json",
    file: {
      path: "package.json",
      category: "A",
      purpose:
        "HELIX consumer package scripts and tag-pinned harness dependency for VSCode tasks / CI",
    },
  },
  {
    template: "project/.vscode/tasks.json",
    file: {
      path: join(".vscode", "tasks.json"),
      category: "A",
      purpose:
        "VSCode HELIX task shortcuts for status, doctor, version-up dry-run, rename plan, and setup dry-run",
    },
  },
  {
    template: "project/.vscode/settings.json",
    file: {
      path: join(".vscode", "settings.json"),
      category: "A",
      purpose: "VSCode HELIX workspace safety defaults",
    },
  },
  {
    template: "project/.helix/memory/.gitkeep",
    file: {
      path: join(".helix", "memory", ".gitkeep"),
      category: "A",
      purpose: "HELIX project-local memory baseline",
    },
  },
  {
    template: "project/.helix/handover/.gitkeep",
    file: {
      path: join(".helix", "handover", ".gitkeep"),
      category: "A",
      purpose: "HELIX project-local handover baseline",
    },
  },
  {
    template: "project/.helix/evidence/.gitkeep",
    file: {
      path: join(".helix", "evidence", ".gitkeep"),
      category: "A",
      purpose: "HELIX project-local evidence baseline",
    },
  },
  {
    template: "project/.helix/teams/default-hybrid.yaml",
    file: {
      path: join(".helix", "teams", "default-hybrid.yaml"),
      category: "A",
      purpose: "HELIX default hybrid team-run definition",
    },
  },
];
