import { join } from "node:path";
import type { GeneratedFile } from "./index";

export type TemplateSet = { [name: string]: string };

const CLAUDE_AGENT_TEMPLATES = [
  ["be-api", "Backend API の route / contract / integration を確認するレビュアー。"],
  ["be-logic", "Backend domain logic の invariant / boundary / TDD 適合を確認するレビュアー。"],
  ["code-reviewer", "正しさ、security、保守性を確認する read-only senior engineering レビュアー。"],
  ["db-schema", "Database schema の migration / index / data contract を確認するレビュアー。"],
  ["devops-deploy", "CI、deployment、rollback、release readiness を確認するレビュアー。"],
  [
    "pdm-innovation-manager",
    "機会、scope、portfolio fit を確認する product management レビュアー。",
  ],
  [
    "pdm-marketing-innovation",
    "市場性、user value、product framing、adoption を確認するレビュアー。",
  ],
  [
    "pdm-tech-innovation",
    "実現可能性、platform leverage、risk を確認する technical product レビュアー。",
  ],
  ["pmo-haiku", "簡潔な status、blocker、next action を確認する lightweight PMO レビュアー。"],
  ["pmo-project-explorer", "goal、制約、evidence gap を確認する project discovery レビュアー。"],
  [
    "pmo-project-scout",
    "backlog、ownership、workflow routing を確認する project triage レビュアー。",
  ],
  ["pmo-sonnet", "PLAN 構造、handover 品質、文書間整合を確認する PMO レビュアー。"],
  ["pmo-tech-docs", "ADR、process、governance 品質を確認する technical documentation レビュアー。"],
  ["pmo-tech-fork", "fork、extraction、distribution の clean-room 境界を確認するレビュアー。"],
  [
    "pmo-tech-news",
    "外部 signal と日付付き source check を確認する technical research レビュアー。",
  ],
  ["qa-test", "test strategy、oracle 強度、regression scope を確認する quality レビュアー。"],
  ["refactor-scout", "複雑度、重複、低 risk extraction 候補を確認する refactoring レビュアー。"],
  ["security-audit", "auth、secret、PII、threat model concern を確認する security レビュアー。"],
  ["helix-tl", "HELIX workflow、gate、test、release readiness を確認する TL レビュアー。"],
] as const;

const CLAUDE_COMMAND_TEMPLATES = [
  ["build", "freeze 済み HELIX spec / test design に沿って実装する。"],
  ["code-simplify", "選択した code に対する最小で安全な単純化を特定する。"],
  ["sdd-plan", "実装前に HELIX の spec-driven planning document を作成する。"],
  ["sdd-review", "HELIX trace / gate 要求に照らして spec / design をレビューする。"],
  ["ship", "release evidence、rollback note、最終検証を準備する。"],
  ["spec", "実装前に spec-first design を作成する。"],
  ["test", "現在の変更に対して targeted HELIX verification を実行する。"],
] as const;

function agentTemplate(name: string, description: string): string {
  return [
    "---",
    `name: ${name}`,
    `description: ${description}`,
    "tools: Read, Grep, Glob, Bash",
    "---",
    "",
    "現在の repository に対して、consumer-safe な HELIX subagent として振る舞う。",
    "",
    "必須 baseline:",
    "- `AGENTS.md`、`CLAUDE.md`、`.claude/CLAUDE.md` が存在する場合は読む。",
    "- PLAN-M-02 で CLI 名が変更されるまでは、`ut-tdd status` と `ut-tdd doctor --profile consumer` を HELIX local state evidence として使う。",
    "- summary より先に findings を出し、file / command evidence を添える。",
    "- secret、credential、PII、machine-local absolute path を書かない。",
    "- user が明示的に実装を求めない限り read-only review を優先する。",
    "",
  ].join("\n");
}

function commandTemplate(name: string, description: string): string {
  return [
    "---",
    `description: ${description}`,
    'argument-hint: "<target>"',
    "---",
    "",
    `Command: ${name}`,
    "",
    "対象: $ARGUMENTS",
    "",
    "現行 `ut-tdd` CLI 経由で repository-local HELIX command を使う。最初に `ut-tdd status --json` を実行し、対象に必要な narrow verification を走らせ、workflow または gate behavior に影響する場合は `ut-tdd doctor --profile consumer` で閉じる。",
    "",
  ].join("\n");
}

const CLAUDE_AGENT_TEMPLATE_SET: TemplateSet = Object.fromEntries(
  CLAUDE_AGENT_TEMPLATES.map(([name, description]) => [
    `adapter/.claude/agents/${name}.md`,
    agentTemplate(name, description),
  ]),
);

const CLAUDE_COMMAND_TEMPLATE_SET: TemplateSet = Object.fromEntries(
  CLAUDE_COMMAND_TEMPLATES.map(([name, description]) => [
    `adapter/.claude/commands/${name}.md`,
    commandTemplate(name, description),
  ]),
);

const CLAUDE_AGENT_FILES: { template: string; file: GeneratedFile }[] = CLAUDE_AGENT_TEMPLATES.map(
  ([name]) => ({
    template: `adapter/.claude/agents/${name}.md`,
    file: {
      path: join(".claude", "agents", `${name}.md`),
      category: "A",
      purpose: `Claude subagent template: ${name}`,
    },
  }),
);

const CLAUDE_COMMAND_FILES: { template: string; file: GeneratedFile }[] =
  CLAUDE_COMMAND_TEMPLATES.map(([name]) => ({
    template: `adapter/.claude/commands/${name}.md`,
    file: {
      path: join(".claude", "commands", `${name}.md`),
      category: "A",
      purpose: `Claude slash command template: ${name}`,
    },
  }));

export const BUILTIN_GITHUB_TEMPLATES: TemplateSet = {
  ...CLAUDE_AGENT_TEMPLATE_SET,
  ...CLAUDE_COMMAND_TEMPLATE_SET,
  "adapter/AGENTS.md": [
    "<!-- UT-TDD:managed:start -->",
    "# HELIX アダプター",
    "",
    "この project は local orchestration surface として HELIX command を使う。PLAN-M-02 で atomic identifier migration が行われるまでは、CLI 名は `ut-tdd` のまま扱う。",
    "",
    "PO への進捗報告・調査結論・確認依頼など chat 出力は日本語を既定とする。docs / handover / adapter prose も日本語を基本とし、CLI 名・識別子・技術用語は原語のまま扱ってよい。",
    "",
    "- Status: `ut-tdd status`",
    "- Doctor: `ut-tdd doctor --profile consumer`",
    "- Handover: `ut-tdd handover`",
    '- Codex delegation: `ut-tdd codex --role <role> --task "..."`',
    '- Claude delegation: `ut-tdd claude --role <role> --task "..."`',
    "- Team run: `ut-tdd team run --definition .ut-tdd/teams/<team>.yaml`",
    "",
    "この managed block の外側にある project-owned instruction は consumer 側の所有物として扱い、勝手に上書きしない。",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/CLAUDE.md": [
    "<!-- UT-TDD:managed:start -->",
    "# HELIX 共有コンテキスト",
    "",
    "harness state と delegation には repository-local HELIX command を使う。PLAN-M-02 までは現行 command 名を `ut-tdd` とする。",
    "",
    "PO への進捗報告・調査結論・確認依頼など chat 出力は日本語を既定とする。docs / handover / adapter prose も日本語を基本とし、CLI 名・識別子・技術用語は原語のまま扱ってよい。",
    "",
    "- `ut-tdd status` は local runtime mode を報告する。",
    "- `ut-tdd doctor --profile consumer` は consumer repo 向け health check を実行する。",
    "- `ut-tdd handover` は cross-runtime handover state を読み書きする。",
    '- `ut-tdd codex --role <role> --task "..."` は Codex へ委譲する。',
    '- `ut-tdd claude --role <role> --task "..."` は Claude へ委譲する。',
    "",
    "adapter doc に secret、token、machine-local absolute path を書かない。",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/CLAUDE.md": [
    "<!-- UT-TDD:managed:start -->",
    "# Claude runtime アダプター",
    "",
    "Claude Code session の HELIX lifecycle work は、現行 `ut-tdd` CLI 経由で扱う。",
    "consumer-owned Claude instruction は、この managed block の外側へ追加できる。",
    "PLAN-M-02 で atomic identifier migration が行われるまでは、CLI 名は `ut-tdd`、state dir は `.ut-tdd` のまま扱う。",
    "",
    "PO への進捗報告・調査結論・確認依頼など chat 出力は日本語を既定とする。docs / handover / adapter prose も日本語を基本とし、CLI 名・識別子・技術用語は原語のまま扱ってよい。",
    "",
    "- Session evidence: `ut-tdd status` と `ut-tdd handover`",
    "- Health check: `ut-tdd doctor --profile consumer`",
    "- Review separation: 可能な場合は別 runtime / model family を使う",
    "",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/settings.json": [
    "{",
    '  "hooks": {',
    '    "PreToolUse": [',
    "      {",
    '        "matcher": "Agent|Task",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd hook agent-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "agent-guard: subagent allowlist/model enforcement"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "Edit|Write|MultiEdit",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd hook work-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "work-guard: foreign edit protection"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd session start",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "Edit|Write|MultiEdit|Bash",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd hook post-tool-use",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd session summary",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "    ,",
    '    "SubagentStop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd hook subagent-stop",',
    '            "timeout": 5,',
    '            "statusMessage": "agent-slots: release oldest guard slot (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "adapter/.codex/config.toml": ["[features]", "hooks = true", ""].join("\n"),
  "adapter/.codex/hooks.json": [
    "{",
    '  "$comment": "Codex adapter hooks for HELIX. Hosted/API tool surfaces still require explicit `ut-tdd guard preflight` before edits because repo-local Codex hooks do not execute there. The CLI name is intentionally unchanged until PLAN-M-02.",',
    '  "hooks": {',
    '    "PreToolUse": [',
    "      {",
    '        "matcher": "spawn_agent|spawn_agents_on_csv",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd hook agent-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "agent-guard: Codex sub-agent role/model guard"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "apply_patch|write_file",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd hook work-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "work-guard: foreign edit protection"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd session start",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "apply_patch|write_file|exec_command|local_shell",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd hook post-tool-use",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd session summary",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "adapter/.claude/commands/helix-status.md": [
    "---",
    "description: HELIX status と doctor 出力を確認する。",
    "---",
    "",
    "`ut-tdd status --json` と `ut-tdd doctor --profile consumer` を実行し、HELIX mode、active draft、open defer、hard-gate failure を要約する。",
    "",
  ].join("\n"),
  "adapter/.claude/commands/helix-test.md": [
    "---",
    "description: 現在の変更に対して HELIX verification を実行する。",
    'argument-hint: "<changed area or PLAN id>"',
    "---",
    "",
    "対象: $ARGUMENTS",
    "",
    "最初に narrow Vitest target を実行し、続いて `bun run typecheck`、`bun run lint` を実行する。変更が HELIX workflow または gate に影響する場合は `ut-tdd doctor --profile consumer` で閉じる。",
    "",
  ].join("\n"),
  "project/.vscode/tasks.json": [
    "{",
    '  "version": "2.0.0",',
    '  "tasks": [',
    "    {",
    '      "label": "HELIX: status",',
    '      "type": "shell",',
    '      "command": "ut-tdd status",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: doctor",',
    '      "type": "shell",',
    '      "command": "ut-tdd doctor --profile consumer",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: handover status",',
    '      "type": "shell",',
    '      "command": "ut-tdd handover status --json",',
    '      "problemMatcher": []',
    "    },",
    "    {",
    '      "label": "HELIX: setup dry-run",',
    '      "type": "shell",',
    '      "command": "ut-tdd setup project --dry-run",',
    '      "problemMatcher": []',
    "    }",
    "  ]",
    "}",
    "",
  ].join("\n"),
  "project/.vscode/settings.json": ["{", '  "task.allowAutomaticTasks": "off"', "}", ""].join("\n"),
  "project/.ut-tdd/memory/.gitkeep": "",
  "project/.ut-tdd/handover/.gitkeep": "",
  "project/.ut-tdd/evidence/.gitkeep": "",
  "common/harness-check.yml": [
    "name: harness-check",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "    branches: [main]",
    "jobs:",
    "  harness-check:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: oven-sh/setup-bun@v2",
    "      - run: bun install --frozen-lockfile",
    "      - name: HELIX CLI dependency",
    "        run: bun run ut-tdd --version",
    "      - name: HELIX setup dry-run",
    "        run: bun run ut-tdd setup project --dry-run --json",
    "      - name: HELIX status",
    "        run: bun run ut-tdd status --json",
    "      - name: HELIX consumer doctor",
    "        run: bun run ut-tdd doctor --profile consumer --json",
    "      - name: Handover route",
    "        run: bun run ut-tdd handover status --json",
    "      - run: bun run typecheck",
    "      - run: bun run test",
    "",
  ].join("\n"),
  "common/commitlint.config.js":
    "module.exports = { extends: ['@commitlint/config-conventional'] };\n",
  "common/escalation-stale.yml": [
    "name: escalation-stale",
    "on:",
    "  schedule:",
    "    - cron: '0 0 * * 1'",
    "jobs:",
    "  noop:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - run: echo escalation policy placeholder",
    "",
  ].join("\n"),
  "common/recovery.md": "# Recovery\n\n壊れた invariant、evidence、rollback path を記録する。\n",
  "common/add-feature.md": "# Add-feature\n\n目的、scope、test、review evidence を記録する。\n",
  "common/PULL_REQUEST_TEMPLATE.md": "## 概要\n\n## 検証\n\n## review evidence\n\nCloses #\n",
  "team/CODEOWNERS": [
    "* {{TL_TEAM}}",
    "/docs/ {{PO_TEAM}}",
    "/src/ {{TL_TEAM}}",
    "/tests/ {{QA_TEAM}}",
    "",
  ].join("\n"),
  "team/setup-branch-protection.sh": [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    'REPO="$' + '{1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"',
    'echo "main の branch protection は action-binding approval が必要です: $' + '{REPO}"',
    'echo "harness-check required / review count / admin enforcement は approval packet で確認してください"',
    'echo "この script は remote GitHub API を呼びません"',
    "exit 2",
    "",
  ].join("\n"),
};

export const COMMON_FILES: { template: string; file: GeneratedFile }[] = [
  {
    template: "adapter/AGENTS.md",
    file: {
      path: "AGENTS.md",
      category: "A",
      purpose: "HELIX adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/CLAUDE.md",
    file: {
      path: "CLAUDE.md",
      category: "A",
      purpose: "HELIX shared adapter context (managed block)",
    },
  },
  {
    template: "adapter/.codex/config.toml",
    file: {
      path: join(".codex", "config.toml"),
      category: "A",
      purpose: "Codex project-local hook enablement",
    },
  },
  {
    template: "adapter/.codex/hooks.json",
    file: {
      path: join(".codex", "hooks.json"),
      category: "A",
      purpose: "Codex hook settings for HELIX CLI entrypoints",
    },
  },
  {
    template: "adapter/.claude/CLAUDE.md",
    file: {
      path: join(".claude", "CLAUDE.md"),
      category: "A",
      purpose: "Claude runtime adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/.claude/settings.json",
    file: {
      path: join(".claude", "settings.json"),
      category: "A",
      purpose: "Claude hook settings for HELIX CLI entrypoints",
    },
  },
  ...CLAUDE_AGENT_FILES,
  ...CLAUDE_COMMAND_FILES,
  {
    template: "adapter/.claude/commands/helix-status.md",
    file: {
      path: join(".claude", "commands", "helix-status.md"),
      category: "A",
      purpose: "Claude slash command for HELIX status checks",
    },
  },
  {
    template: "adapter/.claude/commands/helix-test.md",
    file: {
      path: join(".claude", "commands", "helix-test.md"),
      category: "A",
      purpose: "Claude slash command for HELIX verification",
    },
  },
  {
    template: "common/harness-check.yml",
    file: {
      path: join(".github", "workflows", "harness-check.yml"),
      category: "A",
      purpose: "CI (typecheck + regression)",
    },
  },
  {
    template: "common/commitlint.config.js",
    file: { path: "commitlint.config.js", category: "A", purpose: "Conventional Commits" },
  },
  {
    template: "common/escalation-stale.yml",
    file: {
      path: join(".github", "workflows", "escalation-stale.yml"),
      category: "A",
      purpose: "stale escalation issue workflow",
    },
  },
  {
    template: "common/recovery.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "recovery.md"),
      category: "A",
      purpose: "Recovery issue template",
    },
  },
  {
    template: "common/add-feature.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "add-feature.md"),
      category: "A",
      purpose: "Add-feature issue template",
    },
  },
  {
    template: "common/PULL_REQUEST_TEMPLATE.md",
    file: {
      path: join(".github", "PULL_REQUEST_TEMPLATE.md"),
      category: "A",
      purpose: "PR template",
    },
  },
];

export const PROJECT_SETUP_FILES: { template: string; file: GeneratedFile }[] = [
  {
    template: "project/.vscode/tasks.json",
    file: {
      path: join(".vscode", "tasks.json"),
      category: "A",
      purpose: "VSCode HELIX task shortcuts for status, doctor, and setup dry-run",
    },
  },
  {
    template: "project/.vscode/settings.json",
    file: {
      path: join(".vscode", "settings.json"),
      category: "A",
      purpose: "VSCode HELIX workspace safety defaults",
    },
  },
  {
    template: "project/.ut-tdd/memory/.gitkeep",
    file: {
      path: join(".ut-tdd", "memory", ".gitkeep"),
      category: "A",
      purpose: "HELIX project-local memory baseline",
    },
  },
  {
    template: "project/.ut-tdd/handover/.gitkeep",
    file: {
      path: join(".ut-tdd", "handover", ".gitkeep"),
      category: "A",
      purpose: "HELIX project-local handover baseline",
    },
  },
  {
    template: "project/.ut-tdd/evidence/.gitkeep",
    file: {
      path: join(".ut-tdd", "evidence", ".gitkeep"),
      category: "A",
      purpose: "HELIX project-local evidence baseline",
    },
  },
];
