import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { readFileSync, realpathSync } from "node:fs";
import { resolve } from "node:path";
import { z } from "zod";
import type { HarnessDb } from "./index";
import { observeCanonicalDesignDenominator, type CanonicalDesignDenominatorObservation } from "./design-denominator-observer";
import { readAndValidateLatestSealedPo7Authority, type SealedPo7AuthorityV1 } from "./po7-sealed-authority";

const ZERO = createHash("sha256").update("genesis").digest("hex");
const PATHS = { critical: "docs/governance/generated/design-freeze-critical-path-v1.json", review: "docs/governance/generated/design-freeze-critical-path-independent-review-v1.json", audit: "docs/governance/generated/design-freeze-critical-path-source-rebound-independent-audit-v1.json", po7Audit: "docs/governance/generated/po7-activation-runtime-independent-audit-v1.json" } as const;
const stable = (value: unknown): string => JSON.stringify(value, (_key, item) => item && typeof item === "object" && !Array.isArray(item) ? Object.fromEntries(Object.entries(item).sort(([a], [b]) => a.localeCompare(b))) : item);
const digest = (value: unknown): string => createHash("sha256").update(typeof value === "string" ? value : stable(value)).digest("hex");
const fileDigest = (path: string): string => createHash("sha256").update(readFileSync(path)).digest("hex");
const headSchema = z.object({ authority: z.string().regex(/^[0-9a-f]{64}$/), freeze: z.string().regex(/^[0-9a-f]{64}$/), progress: z.string().regex(/^[0-9a-f]{64}$/), candidate: z.string().regex(/^[0-9a-f]{64}$/) }).strict();
const inputSchema = z.object({ repoRoot: z.string().min(1), operationId: z.string().min(1), idempotencyKey: z.string().min(1), expectedPo7Epoch: z.number().int().positive(), expectedPo7EventDigest: z.string().regex(/^[0-9a-f]{64}$/), expectedHeads: headSchema, expiresAt: z.string().datetime({ offset: true }), supersedesReceiptDigest: z.string().regex(/^[0-9a-f]{64}$/).default(ZERO), faultAfterWrite: z.number().int().positive().optional() }).strict();
export type PostPoDesignFreezeTransitionV2Input = z.infer<typeof inputSchema>;
export interface RepositoryObservationV2 { headOid: string; treeOid: string; remoteRefs: { ref: string; oid: string }[]; remoteObservationDigest: string; indexPolicyDigest: string }
export interface PostPoDesignFreezeTransitionV2Dependencies { observeDenominator?: (root: string) => CanonicalDesignDenominatorObservation; observeRepository?: (root: string) => RepositoryObservationV2; observeEvidence?: (root: string) => ReturnType<typeof observeDesignFreezeEvidenceV2>; trustedNow?: () => string }
export interface PostPoDesignFreezeTransitionV2Receipt { operationId: string; payloadDigest: string; freezeReceiptDigest: string; candidateDigest: string; writeSetDigest: string; replay: boolean }

function git(root: string, args: string[]): string { return execFileSync("git", ["-C", root, ...args], { encoding: "utf8" }).trim(); }
function observeRepository(root: string): RepositoryObservationV2 {
  const headOid = git(root, ["rev-parse", "HEAD"]); const treeOid = git(root, ["rev-parse", "HEAD^{tree}"]);
  execFileSync("git", ["-C", root, "diff", "--quiet", "HEAD", "--"]);
  const raw = git(root, ["ls-remote", "--heads", "origin"]); const remoteRefs = raw.split("\n").filter(Boolean).map((line) => { const [oid, ref] = line.split(/\s+/); return { ref, oid }; }).sort((a, b) => a.ref.localeCompare(b.ref));
  const containing = remoteRefs.filter(({ oid }) => spawnSync("git", ["-C", root, "merge-base", "--is-ancestor", headOid, oid]).status === 0);
  if (!containing.length) throw new Error("Design Freeze v2 HEAD is not contained by a fresh remote observation");
  return { headOid, treeOid, remoteRefs, remoteObservationDigest: digest(remoteRefs), indexPolicyDigest: digest({ version: "tracked-index-equals-head-v2", excludes: ["untracked", "ignored"], submodule: "git-diff-head" }) };
}
export function observeDesignFreezeEvidenceV2(root: string, enforceHead = true) {
  const requireHeadMatch = (relative: string, currentDigest: string) => { if (!enforceHead) return; let headDigest: string; try { headDigest = createHash("sha256").update(execFileSync("git", ["-C", root, "show", `HEAD:${relative}`], { maxBuffer: 256 * 1024 * 1024 })).digest("hex"); } catch { throw new Error(`Design Freeze v2 source absent from HEAD: ${relative}`); } if (headDigest !== currentDigest) throw new Error(`Design Freeze v2 source differs from HEAD: ${relative}`); };
  const result = Object.fromEntries(Object.entries(PATHS).map(([name, relative]) => { const path = resolve(root, relative); const real = realpathSync(path); if (!real.startsWith(`${root}/`)) throw new Error("Design Freeze v2 source escape"); const currentDigest=fileDigest(real);requireHeadMatch(relative,currentDigest);return [name, { path: relative, digest: currentDigest, value: JSON.parse(readFileSync(real, "utf8")) }]; })) as Record<keyof typeof PATHS, { path: string; digest: string; value: any }>;
  const { critical, review, audit, po7Audit } = Object.fromEntries(Object.entries(result).map(([name, row]) => [name, row.value])) as any;
  if (critical.status !== "design_freeze_authority_activated_runtime_separated" || critical.summary?.design_freeze_rows !== 8 || critical.summary?.design_freeze_open_rows !== 0 || critical.summary?.po_authority_activated_units !== 7) throw new Error("Design Freeze v2 critical path not closed");
  if (!String(review.status).startsWith("independent_review_pass_") || review.findings?.length || audit.status !== "independent_audit_pass_design_freeze_closed_runtime_separated" || audit.findings?.length || po7Audit.status !== "independent_audit_pass_authority_activated" || po7Audit.findings?.length) throw new Error("Design Freeze v2 review chain not current");
  if (review.sources?.find((row: any) => row.path === PATHS.critical)?.sha256 !== result.critical.digest || audit.source?.sha256 !== result.critical.digest) throw new Error("Design Freeze v2 critical source join drift");
  const reboundPaths = new Set<string>([...critical.design_freeze_critical_path.map((row: any) => row.source_artifact.path), ...critical.runtime_acceptance_blockers_separated.map((row: any) => row.source_artifact.path), ...critical.current_nonblocking_review_sources.map((row: any) => row.path), ...review.sources.map((row: any) => row.path)]);
  for (const relative of reboundPaths) requireHeadMatch(relative, fileDigest(realpathSync(resolve(root, relative))));
  const authority = review.review_authority; if (!authority?.runtime_model_separated || !authority.producer_identity || !authority.reviewer_identity || authority.producer_identity === authority.reviewer_identity || authority.producer_runtime === authority.reviewer_runtime) throw new Error("Design Freeze v2 reviewer separation invalid");
  return { result, critical, review, audit, po7Audit, reviewAuthority: authority };
}
function heads(db: HarnessDb) {
  const latest = (table: string, column: string) => String(db.prepare(`SELECT ${column} value FROM ${table} ORDER BY rowid DESC LIMIT 1`).get()?.value ?? ZERO);
  return { authority: latest("design_freeze_v2_authority_link_events", "event_digest"), freeze: latest("design_freeze_v2_projections", "event_digest"), progress: latest("design_freeze_v2_progress_projections", "event_digest"), candidate: latest("design_freeze_v2_l01_candidates", "event_digest") };
}
const headValues = (expected: z.infer<typeof headSchema>, current: z.infer<typeof headSchema>) => [expected.authority,current.authority,expected.freeze,current.freeze,expected.progress,current.progress,expected.candidate,current.candidate];

export function commitPostPoDesignFreezeTransitionV2(db: HarnessDb, raw: PostPoDesignFreezeTransitionV2Input, deps: PostPoDesignFreezeTransitionV2Dependencies = {}): PostPoDesignFreezeTransitionV2Receipt {
  const input = inputSchema.parse(raw); const root = realpathSync(input.repoRoot); const requestDigest = digest({ operationId: input.operationId, idempotencyKey: input.idempotencyKey, expectedPo7Epoch: input.expectedPo7Epoch, expectedPo7EventDigest: input.expectedPo7EventDigest, expectedHeads: input.expectedHeads, expiresAt: input.expiresAt, supersedesReceiptDigest: input.supersedesReceiptDigest });
  db.exec("BEGIN IMMEDIATE");
  try {
    const replay = db.prepare("SELECT operation_id,request_digest FROM design_freeze_v2_transition_operations WHERE idempotency_key=?").get(input.idempotencyKey);
    if (replay) { if (replay.request_digest !== requestDigest) throw new Error("Design Freeze v2 idempotency conflict"); const terminal = db.prepare("SELECT * FROM design_freeze_v2_transition_terminal_receipts WHERE operation_id=?").get(String(replay.operation_id)); if (!terminal) throw new Error("Design Freeze v2 reconcile required"); db.exec("COMMIT"); return { operationId: String(replay.operation_id), payloadDigest: String(terminal.payload_digest), freezeReceiptDigest: String(terminal.freeze_receipt_digest), candidateDigest: String(terminal.candidate_digest), writeSetDigest: String(terminal.write_set_digest), replay: true }; }
    const currentHeads = heads(db); if (stable(currentHeads) !== stable(input.expectedHeads)) throw new Error("Design Freeze v2 four-head CAS conflict");
    const po7: SealedPo7AuthorityV1 = readAndValidateLatestSealedPo7Authority(db, input.expectedPo7Epoch, input.expectedPo7EventDigest);
    const evidence = (deps.observeEvidence ?? ((value) => observeDesignFreezeEvidenceV2(value)))(root); const denominator = (deps.observeDenominator ?? ((value) => observeCanonicalDesignDenominator({ repoRoot: value })))(root); const repository = (deps.observeRepository ?? observeRepository)(root); const issuedAt = (deps.trustedNow ?? (() => new Date().toISOString()))();
    if (Date.parse(input.expiresAt) <= Date.parse(issuedAt)) throw new Error("Design Freeze v2 authority expired");
    if (denominator.sliceIds.length !== 19 || denominator.artifactObservations.length !== 76 || denominator.headDigestMatchCount !== 76 || denominator.sourceRepository.headOid !== repository.headOid || denominator.sourceRepository.treeOid !== repository.treeOid) throw new Error("Design Freeze v2 denominator repository binding drift");
    const sources = Object.fromEntries(Object.entries(evidence.result).map(([name, row]) => [name, { path: row.path, digest: row.digest, status: row.value.status }]));
    const fullPreimage = { schema_version: "helix.post-po-design-freeze-transition.v2", operation_id: input.operationId, idempotency_key: input.idempotencyKey, po7: { operation_id: po7.operationId, epoch: po7.authorityEpoch, event_digest: po7.eventDigest, payload_digest: po7.payloadDigest, terminal_write_set_digest: po7.terminalWriteSetDigest, terminal_row_digest: po7.terminalRowDigest, authority_receipt_digests: po7.authorityReceiptDigests, authority_receipt_set_digest: po7.authorityReceiptSetDigest, full_row_set_digest: po7.fullRowSetDigest }, critical: { sources, denominator_ids: evidence.critical.design_freeze_critical_path.map((row: any) => row.blocker_id).sort(), open: 0 }, review_authority: evidence.reviewAuthority, repository, design_denominator: denominator, expected_heads: input.expectedHeads, current_heads: currentHeads, issued_at: issuedAt, expires_at: input.expiresAt, supersedes_receipt_digest: input.supersedesReceiptDigest, status: "current" };
    const fullPreimageJson = stable(fullPreimage); const fullPreimageDigest = digest(fullPreimageJson); const payloadDigest = digest({ requestDigest, fullPreimageDigest }); const hv = headValues(input.expectedHeads, currentHeads); const reviewIdentity = String(evidence.reviewAuthority.reviewer_identity); const reviewRuntime = String(evidence.reviewAuthority.reviewer_runtime); const reviewIdentityDigest = digest(evidence.reviewAuthority); const criticalSetDigest = digest(sources);
    const authorityEventDigest = digest({ kind: "authority-link", payloadDigest, previous: currentHeads.authority, po7: po7.fullRowSetDigest, issuedAt });
    const freezeReceiptDigest = digest({ receipt_id: `${input.operationId}:freeze`, operation_id: input.operationId, full_preimage: fullPreimage, payload_digest: payloadDigest, authority_event_digest: authorityEventDigest });
    const freezeEventDigest = digest({ kind: "freeze", freezeReceiptDigest, previous: currentHeads.freeze }); const freezeProjectionDigest = digest({ freezeEventDigest, freezeReceiptDigest, designOpenRows: 0 });
    const progressEventDigest = digest({ kind: "progress", freezeReceiptDigest, previous: currentHeads.progress }); const progressProjectionDigest = digest({ progressEventDigest, freezeReceiptDigest, slices: 19, artifacts: 76, credits: [0,0,0] });
    const candidateEventDigest = digest({ kind: "L01-candidate", freezeReceiptDigest, previous: currentHeads.candidate, issuedAt, expiresAt: input.expiresAt }); const candidateDigest = digest({ candidate_id: `${input.operationId}:L01`, operation_id: input.operationId, event_digest: candidateEventDigest, freeze_receipt_digest: freezeReceiptDigest, repository, authority_epoch: input.expectedPo7Epoch, states: ["proposed","pending_pair","not_frozen",0,"not_created"], issued_at: issuedAt, expires_at: input.expiresAt });
    const handoffEventDigest = digest({ kind: "L01-handoff", candidateDigest, freezeReceiptDigest }); const handoffDigest = digest({ handoff_id: `${input.operationId}:L01-handoff`, operation_id: input.operationId, event_digest: handoffEventDigest, candidate_digest: candidateDigest, transition_payload_digest: payloadDigest, denominator_observation_digest: denominator.observationDigest, heads: currentHeads, issued_at: issuedAt, expires_at: input.expiresAt });
    const outboxEventDigest = digest({ kind: "local-reconcile", handoffDigest, payloadDigest, remote: repository.remoteObservationDigest });
    const operationRow = [input.operationId,input.idempotencyKey,requestDigest,payloadDigest,input.expectedPo7Epoch,...hv,fullPreimageJson,fullPreimageDigest,19,76,reviewIdentity,reviewRuntime,reviewIdentityDigest,"fresh_remote_heads",repository.remoteObservationDigest,input.expiresAt,input.supersedesReceiptDigest,"current",issuedAt];
    const authorityRow = [`${input.operationId}:authority-link`,input.operationId,1,authorityEventDigest,currentHeads.authority,po7.operationId,po7.eventDigest,po7.authorityReceiptSetDigest,input.expectedPo7Epoch,...hv,"current",issuedAt];
    const freezeRow = [`${input.operationId}:freeze`,input.operationId,freezeReceiptDigest,payloadDigest,fullPreimageJson,fullPreimageDigest,po7.authorityReceiptSetDigest,criticalSetDigest,19,76,reviewIdentity,reviewRuntime,reviewIdentityDigest,repository.headOid,repository.treeOid,repository.indexPolicyDigest,...hv,"fresh_remote_heads",repository.remoteObservationDigest,currentHeads.freeze,input.supersedesReceiptDigest,input.expiresAt,"current",issuedAt];
    const freezeProjectionRow = [`${input.operationId}:freeze-projection`,input.operationId,freezeEventDigest,currentHeads.freeze,freezeReceiptDigest,19,76,0,...hv,freezeProjectionDigest,"current",issuedAt];
    const progressRow = [`${input.operationId}:progress`,input.operationId,progressEventDigest,currentHeads.progress,freezeReceiptDigest,19,76,0,0,0,...hv,repository.remoteObservationDigest,progressProjectionDigest,"current",issuedAt];
    const candidateRow = [`${input.operationId}:L01`,input.operationId,candidateEventDigest,currentHeads.candidate,candidateDigest,freezeReceiptDigest,input.expectedPo7Epoch,repository.headOid,repository.treeOid,...hv,"proposed","pending_pair","not_frozen",0,"not_created",repository.remoteObservationDigest,input.expiresAt,ZERO,"current",issuedAt];
    const handoffRow = [`${input.operationId}:L01-handoff`,input.operationId,handoffEventDigest,ZERO,handoffDigest,candidateDigest,freezeReceiptDigest,input.expectedPo7Epoch,...hv,"observed",repository.remoteObservationDigest,input.expiresAt,ZERO,"current",issuedAt];
    const outboxRow = [`${input.operationId}:outbox`,input.operationId,outboxEventDigest,payloadDigest,handoffDigest,...hv,repository.remoteObservationDigest,input.expiresAt,ZERO,"local_reconcile_only","pending",issuedAt];
    const writes = [["design_freeze_v2_transition_operations",operationRow],["design_freeze_v2_authority_link_events",authorityRow],["design_freeze_v2_receipts",freezeRow],["design_freeze_v2_projections",freezeProjectionRow],["design_freeze_v2_progress_projections",progressRow],["design_freeze_v2_l01_candidates",candidateRow],["design_freeze_v2_l01_handoffs",handoffRow],["design_freeze_v2_transition_outbox",outboxRow]] as const; const writeSetDigest = digest(writes.map(([table,row]) => ({ table,row })));
    const terminalRow = [`${input.operationId}:terminal`,input.operationId,payloadDigest,fullPreimageDigest,authorityEventDigest,freezeReceiptDigest,freezeProjectionDigest,progressProjectionDigest,candidateDigest,handoffDigest,outboxEventDigest,repository.remoteObservationDigest,writeSetDigest,...hv,input.expiresAt,input.supersedesReceiptDigest,"current",issuedAt];
    let count = 0; const insert = (table: string, row: readonly unknown[]) => { db.prepare(`INSERT INTO ${table} VALUES (${row.map(() => "?").join(",")})`).run(...row); count += 1; if (input.faultAfterWrite === count) throw new Error(`Design Freeze v2 injected fault ${count}`); }; for (const [table,row] of writes) insert(table,row); insert("design_freeze_v2_transition_terminal_receipts",terminalRow);
    const afterPo7 = readAndValidateLatestSealedPo7Authority(db, input.expectedPo7Epoch, input.expectedPo7EventDigest); const afterDenominator = (deps.observeDenominator ?? ((value) => observeCanonicalDesignDenominator({ repoRoot: value })))(root); const afterRepository = (deps.observeRepository ?? observeRepository)(root); const afterEvidence = (deps.observeEvidence ?? ((value) => observeDesignFreezeEvidenceV2(value)))(root);
    if (afterPo7.fullRowSetDigest !== po7.fullRowSetDigest || afterDenominator.observationDigest !== denominator.observationDigest || stable(afterRepository) !== stable(repository) || digest(afterEvidence.result) !== digest(evidence.result)) throw new Error("Design Freeze v2 source changed during transaction");
    db.exec("COMMIT"); return { operationId: input.operationId, payloadDigest, freezeReceiptDigest, candidateDigest, writeSetDigest, replay: false };
  } catch (error) { db.exec("ROLLBACK"); throw error; }
}

export { ZERO as DESIGN_FREEZE_V2_GENESIS_HEAD };
