import { col, pk } from "./harness-db-table-builders";
import type { TableDef } from "./harness-db-types";

export const HARNESS_DB_CORE_TABLES: TableDef[] = [
  // Reverse-344 / PLAN-L7-416: append-only session logから再構築可能なcontinuation read model。
  // event_idを物理PKとし、(session_id,event_seq)の意味的一意性とpayload conflictはwriterで
  // fail-closeする。JSONL appendとSQLite projectionを同一transactionとは見なさない。
  {
    name: "session_events",
    columns: [
      // registryは単一列PKのみのため、composite (session_id,event_seq) をcanonical event_keyへ符号化。
      pk("event_key"),
      col("event_id"),
      col("schema_version", "INTEGER"),
      col("operation_id"),
      col("session_id"),
      col("event_seq", "INTEGER"),
      col("plan_id"),
      col("event_kind"),
      col("next_action"),
      col("memory_ref"),
      col("recorded_at"),
      col("payload_hash"),
    ],
  },
  {
    name: "delivery_receipts",
    columns: [
      pk("delivery_id"),
      col("entry_id"),
      col("consumer_id"),
      col("payload_digest"),
      col("status"),
      col("recorded_at"),
      col("retention_until"),
      col("source_retention_until"),
    ],
  },
  {
    name: "continuation_fences",
    columns: [pk("scope"), col("fence_token", "INTEGER"), col("owner"), col("acquired_at")],
  },
  // --- §2.7 基本 7 ---
  {
    name: "plan_registry",
    columns: [
      pk("plan_id"),
      col("kind"),
      col("layer"),
      col("sub_doc"),
      col("drive"),
      col("status"),
      col("parent"),
      col("updated_at"),
      // decision_outcome: S4 verdict for PoC (kind=poc) PLANs.
      // Values: "confirmed" | "rejected" | "pivot" | "" (null/unset stored as "").
      // Source: PLAN frontmatter field `decision_outcome`. Used by projectPocEvaluations (FR-L1-43).
      col("decision_outcome"),
      // source_hash: sha256 of the full PLAN markdown content. Used by drive-db-registration to
      // detect persisted harness.db staleness even when the plan count is unchanged.
      col("source_hash"),
    ],
  },
  {
    name: "artifact_registry",
    columns: [
      pk("artifact_id"),
      col("artifact_type"),
      col("path"),
      col("pair_artifact"),
      col("status"),
      col("updated_at"),
    ],
  },
  {
    name: "model_runs",
    columns: [
      pk("run_id"),
      col("runtime"),
      col("model"),
      col("role"),
      col("drive"),
      col("plan_id"),
      col("started_at"),
      col("completed_at"),
      col("evidence_path"),
      // FR-L1-38 token telemetry (PLAN-L7-57): cross-runtime per-run usage. NULL for review-evidence
      // 由来の行 (token 不明)、token-tracker が session ログ走査で投入した行のみ非 NULL。
      // cached_input/reasoning は runtime により欠ける (Claude=cache_read, Codex=cached_input/reasoning)。
      col("input_tokens", "INTEGER"),
      col("output_tokens", "INTEGER"),
      col("cached_input_tokens", "INTEGER"),
      col("reasoning_tokens", "INTEGER"),
      // cost_usd: provider 非対称の enrichment。Claude=CLAUDE_PRICING で計算可、Codex=OpenAI 単価
      // source 未取得のため NULL (core metric は token 効率、$ は出せる runtime のみ)。
      col("cost_usd", "REAL"),
    ],
  },
  {
    name: "trace_edges",
    columns: [
      pk("edge_id"),
      col("from_artifact"),
      col("to_artifact"),
      col("edge_kind"),
      col("plan_id"),
      col("status"),
    ],
  },
  {
    name: "coverage",
    columns: [
      pk("coverage_id"),
      col("scope"),
      col("subject_id"),
      col("metric"),
      col("value", "REAL"),
      col("threshold", "REAL"),
      col("status"),
    ],
  },
  {
    name: "findings",
    columns: [
      pk("finding_id"),
      col("kind"),
      col("severity"),
      col("subject_id"),
      col("source"),
      col("status"),
      col("evidence_path"),
    ],
  },
  {
    name: "gate_runs",
    columns: [
      pk("gate_run_id"),
      col("gate_id"),
      col("plan_id"),
      col("status"),
      col("checked_at"),
      col("evidence_path"),
      col("session_id"),
      col("command"),
      col("exit_code", "INTEGER"),
      col("output_digest"),
      col("materialization_id"),
      // OS subprocess が返した物理 receipt への参照。legacy/projected row は NULL を許す。
      col("process_receipt_key"),
    ],
  },
  {
    name: "closure_process_receipts",
    columns: [
      pk("process_receipt_key"),
      col("schema_version"),
      col("materialization_id"),
      col("kind"),
      col("repository_head"),
      col("executable"),
      col("argv_json"),
      col("dedupe_key"),
      col("exit_code", "INTEGER"),
      col("signal"),
      col("timed_out", "INTEGER"),
      col("stdout_digest"),
      col("stderr_digest"),
      col("stdout_path"),
      col("stderr_path"),
      col("completed_at"),
    ],
  },
  {
    name: "closure_authority_review_receipts",
    columns: [
      pk("receipt_id"),
      col("worker_run_id"),
      col("reviewer_run_id"),
      col("artifact_path"),
      col("artifact_digest"),
      col("repository_head"),
      col("bundle_digest"),
      col("proposal_set_digest"),
      col("recompute_digest"),
      col("verdict_digest"),
      col("status"),
      col("exit_code", "INTEGER"),
      col("completed_at"),
    ],
  },
  {
    name: "closure_terminal_boundaries",
    columns: [
      pk("boundary_key"),
      col("authority_head"),
      col("registry_digest"),
      col("source_blob_digest"),
      col("plan_id"),
      col("classification"),
      col("reason"),
      col("owner"),
      col("next_decision_route"),
      col("automation_terminal", "INTEGER"),
      col("whole_program_blocker", "INTEGER"),
      col("opened_event_digest"),
      col("resolved_event_digest"),
      col("resolution_authority_digest"),
      col("previous_event_digest"),
      col("event_digest"),
    ],
  },
  {
    name: "runner_attestations",
    columns: [
      pk("event_digest"),
      col("previous_digest"),
      col("run_id"),
      col("session_id"),
      col("plan_id"),
      col("kind"),
      col("oracle_id"),
      col("repository_head"),
      col("command"),
      col("exit_code", "INTEGER"),
      col("status"),
      col("evidence_path"),
      col("output_digest"),
      col("completed_at"),
      col("signature"),
      col("process_receipt_key"),
    ],
  },
  {
    name: "closure_materializations",
    columns: [
      pk("materialization_id"),
      col("repository_head"),
      col("status"),
      col("journal_path"),
      col("manifest_path"),
      col("committed_at"),
    ],
  },
  // --- §9.1 Reference-Feedback 拡張 10 ---
  {
    name: "drive_runs",
    columns: [
      pk("drive_run_id"),
      col("plan_id"),
      col("session_id"),
      col("drive"),
      col("mode"),
      col("layer"),
      col("kind"),
      col("started_at"),
      col("completed_at"),
      col("status"),
    ],
  },
  {
    name: "route_modes",
    columns: [
      pk("route_mode_id"),
      col("plan_id"),
      col("drive_run_id"),
      col("mode"),
      col("drive"),
      col("layer"),
      col("kind"),
      col("source"),
      col("indexed_at"),
    ],
  },
  {
    name: "hook_events",
    columns: [
      pk("event_id"),
      col("session_id"),
      col("plan_id"),
      col("hook_name"),
      col("event_type"),
      col("occurred_at"),
      col("digest"),
      col("evidence_path"),
    ],
  },
  {
    name: "skill_invocations",
    columns: [
      pk("skill_invocation_id"),
      col("session_id"),
      col("plan_id"),
      col("skill_id"),
      col("layer"),
      col("drive"),
      col("fired_at"),
      col("source"),
      col("accepted", "INTEGER"),
    ],
  },
  {
    name: "skill_recommendations",
    columns: [
      pk("skill_recommendation_id"),
      col("session_id"),
      col("plan_id"),
      col("skill_id"),
      col("rank", "INTEGER"),
      col("score", "REAL"),
      col("reason"),
      col("recommended_at"),
    ],
  },
  {
    name: "feedback_events",
    columns: [
      pk("feedback_event_id"),
      col("finding_id"),
      col("plan_id"),
      col("source_table"),
      col("source_id"),
      col("source_color"),
      col("signal_type"),
      col("severity"),
      col("status"),
      col("next_action"),
      col("created_at"),
    ],
  },
  {
    name: "feedback_lifecycle",
    columns: [
      pk("lifecycle_key"),
      col("source_table"),
      col("source_id"),
      col("source_generation"),
      col("activity_epoch", "INTEGER"),
      col("policy_epoch", "INTEGER"),
      col("state"),
      col("bucket"),
      col("payload_digest"),
      col("first_observed_at"),
      col("last_transition_at"),
      col("last_event_id"),
      col("actor"),
      col("reason"),
      col("policy_version"),
      col("surfaced_sessions"),
    ],
  },
  {
    name: "feedback_lifecycle_health",
    columns: [
      pk("health_id"),
      col("damaged_count", "INTEGER"),
      col("checkpoint_byte_offset", "INTEGER"),
      col("checkpoint_event_id"),
      col("projected_at"),
    ],
  },
  {
    name: "quality_signals",
    columns: [
      pk("signal_id"),
      col("source"),
      col("subject_id"),
      col("metric"),
      col("value", "REAL"),
      col("threshold", "REAL"),
      col("status"),
      col("computed_at"),
    ],
  },
  {
    name: "test_runs",
    columns: [
      pk("test_run_id"),
      col("session_id"),
      col("plan_id"),
      col("command"),
      col("runner"),
      col("runtime"),
      col("os"),
      col("shell"),
      col("scope"),
      col("started_at"),
      col("completed_at"),
      col("exit_code", "INTEGER"),
      col("evidence_path"),
      col("output_digest"),
      col("green_definition_id"),
      col("status"),
      // closure materialization以外の既存test projectionとの互換性のためnullable。
      col("process_receipt_key"),
    ],
  },
  {
    name: "runtime_verification_events",
    columns: [
      pk("event_id"),
      col("plan_id"),
      col("requirement_id"),
      col("test_oracle_id"),
      col("claim"),
      col("session_id"),
      col("source"),
      col("runtime_surface"),
      col("correlation_id"),
      col("evidence_path"),
      col("occurred_at"),
      col("redaction_policy"),
      col("verification_class"),
      col("accept_status"),
    ],
  },
  {
    name: "test_cases",
    columns: [
      pk("test_case_id"),
      col("test_run_id"),
      col("test_file"),
      col("test_name"),
      col("plan_id"),
      col("fr_id"),
      col("artifact_id"),
      col("kind"),
      col("oracle_id"),
      col("name"),
      col("first_seen_at"),
      col("last_seen_at"),
      col("status"),
      col("duration_ms", "REAL"),
      col("evidence_path"),
    ],
  },
  {
    name: "test_results",
    columns: [
      pk("test_result_id"),
      col("test_case_id"),
      col("test_run_id"),
      col("oracle_id"),
      col("status"),
      col("duration_ms", "REAL"),
      col("failure_digest"),
      col("started_at"),
      col("completed_at"),
      col("message"),
      col("evidence_path"),
    ],
  },
  {
    name: "test_artifact_edges",
    columns: [
      pk("edge_id"),
      col("test_artifact_edge_id"),
      col("test_case_id"),
      col("test_run_id"),
      col("artifact_id"),
      col("plan_id"),
      col("source_path"),
      col("artifact_path"),
      col("edge_kind"),
      col("oracle_id"),
      col("evidence_path"),
    ],
  },
  {
    name: "test_flake_events",
    columns: [
      pk("flake_event_id"),
      col("test_case_id"),
      col("window"),
      col("pass_count", "INTEGER"),
      col("fail_count", "INTEGER"),
      col("flake_score", "REAL"),
      col("computed_at"),
      col("evidence_path"),
    ],
  },
  {
    name: "search_index",
    columns: [
      pk("search_id"),
      col("subject_type"),
      col("subject_id"),
      col("path"),
      col("title"),
      col("tokens"),
      col("summary"),
      col("updated_at"),
    ],
  },
  {
    name: "workflow_runs",
    columns: [
      pk("workflow_run_id"),
      col("plan_id"),
      col("drive_run_id"),
      col("workflow"),
      col("phase"),
      col("ready_status"),
      col("blocked_reason"),
      col("human_required", "INTEGER"),
      col("checked_at"),
    ],
  },
  {
    name: "guardrail_decisions",
    columns: [
      pk("guardrail_decision_id"),
      col("plan_id"),
      col("session_id"),
      col("guardrail"),
      col("decision"),
      col("mode"),
      col("human_signoff_required", "INTEGER"),
      col("evidence_path"),
      col("decided_at"),
    ],
  },
  {
    name: "guard_override_transactions",
    columns: [
      pk("nonce"),
      col("guard_kind"),
      col("operation_class"),
      col("subject_digest"),
      col("reason_digest"),
      col("status"),
      col("created_at"),
      col("consumed_at"),
      col("abort_reason"),
    ],
  },
  {
    name: "issue_queue",
    columns: [
      pk("issue_queue_id"),
      col("source_event_id"),
      col("plan_id"),
      col("target"),
      col("title"),
      col("body"),
      col("status"),
      col("human_approval_required", "INTEGER"),
      col("approved_by"),
      col("approved_at"),
      col("external_issue_id"),
      col("external_issue_url"),
      col("created_at"),
    ],
  },
  {
    name: "trouble_events",
    columns: [
      pk("trouble_event_id"),
      col("source_event_id"),
      col("plan_id"),
      col("category"),
      col("severity"),
      col("summary"),
      col("status"),
      col("created_at"),
    ],
  },
  {
    name: "retry_events",
    columns: [
      pk("retry_event_id"),
      col("plan_id"),
      col("workflow"),
      col("phase"),
      col("attempt_count", "INTEGER"),
      col("status"),
      col("created_at"),
    ],
  },
  {
    name: "improvement_log",
    columns: [
      pk("improvement_log_id"),
      col("source_event_id"),
      col("plan_id"),
      col("category"),
      col("summary"),
      col("next_action"),
      col("status"),
      col("created_at"),
    ],
  },
  {
    name: "automation_assets",
    columns: [
      pk("asset_id"),
      col("asset_type"),
      col("path"),
      col("trigger"),
      col("role"),
      col("capability"),
      col("skill_type"),
      col("applies_layers"),
      col("applies_drive_models"),
      col("drift_status"),
      col("indexed_at"),
    ],
  },
];
