import { pk } from "./harness-db-table-builders";
import type { ColumnType, TableDef } from "./harness-db-types";

const col = (name: string, type: ColumnType = "TEXT") => ({ name, type, notNull: true });
const digests = (names: string[]) =>
  names.map((name) => `length(${name}) = 64 AND ${name} NOT GLOB '*[^0-9a-f]*'`);

export const HARNESS_DB_DESIGN_FREEZE_TABLES: TableDef[] = [
  {
    name: "design_freeze_transition_operations",
    columns: [
      pk("operation_id"),
      col("idempotency_key"),
      col("request_digest"),
      col("payload_digest"),
      col("authority_epoch", "INTEGER"),
      col("authority_event_digest"),
      col("critical_digest"),
      col("critical_review_digest"),
      col("critical_audit_digest"),
      col("activation_audit_digest"),
      col("repository_head_oid"),
      col("repository_tree_oid"),
      col("repository_snapshot_digest"),
      col("index_policy_digest"),
      col("denominator_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "authority_epoch > 0",
      "length(repository_head_oid) >= 40",
      "length(repository_tree_oid) >= 40",
      "status = 'current'",
      ...digests([
        "request_digest",
        "payload_digest",
        "authority_event_digest",
        "critical_digest",
        "critical_review_digest",
        "critical_audit_digest",
        "activation_audit_digest",
        "repository_snapshot_digest",
        "index_policy_digest",
        "denominator_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_authority_link_events",
    columns: [
      pk("event_id"),
      col("operation_id"),
      col("event_digest"),
      col("po7_operation_id"),
      col("po7_event_digest"),
      col("po7_terminal_row_digest"),
      col("authority_receipt_set_digest"),
      col("authority_epoch", "INTEGER"),
      col("previous_event_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "authority_epoch > 0",
      "status = 'current'",
      ...digests([
        "event_digest",
        "po7_event_digest",
        "po7_terminal_row_digest",
        "authority_receipt_set_digest",
        "previous_event_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_receipts",
    columns: [
      pk("receipt_id"),
      col("operation_id"),
      col("receipt_digest"),
      col("payload_digest"),
      col("authority_receipt_set_digest"),
      col("critical_set_digest"),
      col("reviewer_identity_digest"),
      col("repository_head_oid"),
      col("repository_tree_oid"),
      col("repository_snapshot_digest"),
      col("index_policy_digest"),
      col("denominator_count", "INTEGER"),
      col("denominator_digest"),
      col("previous_receipt_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "denominator_count = 8",
      "length(repository_head_oid) >= 40",
      "length(repository_tree_oid) >= 40",
      "status = 'current'",
      ...digests([
        "receipt_digest",
        "payload_digest",
        "authority_receipt_set_digest",
        "critical_set_digest",
        "reviewer_identity_digest",
        "repository_snapshot_digest",
        "index_policy_digest",
        "denominator_digest",
        "previous_receipt_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_projections",
    columns: [
      pk("projection_id"),
      col("operation_id"),
      col("authority_link_event_digest"),
      col("freeze_receipt_digest"),
      col("design_rows", "INTEGER"),
      col("design_open_rows", "INTEGER"),
      col("runtime_rows_separated", "INTEGER"),
      col("projection_digest"),
      col("status"),
      col("projected_at"),
    ],
    checks: [
      "design_rows = 8",
      "design_open_rows = 0",
      "runtime_rows_separated = 5",
      "status = 'current'",
      ...digests(["authority_link_event_digest", "freeze_receipt_digest", "projection_digest"]),
    ],
  },
  {
    name: "design_freeze_progress_projections",
    columns: [
      pk("projection_id"),
      col("operation_id"),
      col("freeze_receipt_digest"),
      col("design_rows", "INTEGER"),
      col("design_open_rows", "INTEGER"),
      col("runtime_rows", "INTEGER"),
      col("implementation_credit", "INTEGER"),
      col("verification_credit", "INTEGER"),
      col("coverage_credit", "INTEGER"),
      col("projection_digest"),
      col("status"),
      col("projected_at"),
    ],
    checks: [
      "design_rows = 8",
      "design_open_rows = 0",
      "runtime_rows = 5",
      "implementation_credit = 0",
      "verification_credit = 0",
      "coverage_credit = 0",
      "status = 'current'",
      ...digests(["freeze_receipt_digest", "projection_digest"]),
    ],
  },
  {
    name: "design_freeze_l01_candidates",
    columns: [
      pk("candidate_id"),
      col("operation_id"),
      col("candidate_digest"),
      col("freeze_receipt_digest"),
      col("repository_head_oid"),
      col("repository_tree_oid"),
      col("authority_epoch", "INTEGER"),
      col("local_state"),
      col("pair_state"),
      col("freeze_state"),
      col("counted", "INTEGER"),
      col("remote_creation_state"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "authority_epoch > 0",
      "length(repository_head_oid) >= 40",
      "length(repository_tree_oid) >= 40",
      "local_state = 'proposed'",
      "pair_state = 'pending_pair'",
      "freeze_state = 'not_frozen'",
      "counted = 0",
      "remote_creation_state = 'not_created'",
      "status = 'current'",
      ...digests(["candidate_digest", "freeze_receipt_digest"]),
    ],
  },
  {
    name: "design_freeze_l01_handoffs",
    columns: [
      pk("handoff_id"),
      col("operation_id"),
      col("handoff_digest"),
      col("candidate_digest"),
      col("freeze_receipt_digest"),
      col("repository_head_oid"),
      col("repository_tree_oid"),
      col("denominator_digest"),
      col("authority_epoch", "INTEGER"),
      col("remote_authority"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "authority_epoch > 0",
      "length(repository_head_oid) >= 40",
      "length(repository_tree_oid) >= 40",
      "remote_authority = 'not_granted'",
      "status = 'current'",
      ...digests([
        "handoff_digest",
        "candidate_digest",
        "freeze_receipt_digest",
        "denominator_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_transition_outbox",
    columns: [
      pk("outbox_id"),
      col("operation_id"),
      col("payload_digest"),
      col("candidate_digest"),
      col("delivery_class"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "delivery_class = 'local_reconcile_only'",
      "status = 'pending'",
      ...digests(["payload_digest", "candidate_digest"]),
    ],
  },
  {
    name: "design_freeze_transition_terminal_receipts",
    columns: [
      pk("receipt_id"),
      col("operation_id"),
      col("payload_digest"),
      col("authority_link_event_digest"),
      col("freeze_receipt_digest"),
      col("freeze_projection_digest"),
      col("progress_projection_digest"),
      col("candidate_digest"),
      col("handoff_digest"),
      col("write_set_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "status = 'current'",
      ...digests([
        "payload_digest",
        "authority_link_event_digest",
        "freeze_receipt_digest",
        "freeze_projection_digest",
        "progress_projection_digest",
        "candidate_digest",
        "handoff_digest",
        "write_set_digest",
      ]),
    ],
  },
];
