import { pk } from "./harness-db-table-builders";
import type { ColumnType, TableDef } from "./harness-db-types";

const col = (name: string, type: ColumnType = "TEXT") => ({
  name,
  type,
  notNull: true,
});
const digests = (names: string[]) =>
  names.map((name) => `length(${name}) = 64 AND ${name} NOT GLOB '*[^0-9a-f]*'`);
const heads = () => [
  col("expected_authority_head_digest"),
  col("current_authority_head_digest"),
  col("expected_freeze_head_digest"),
  col("current_freeze_head_digest"),
  col("expected_progress_head_digest"),
  col("current_progress_head_digest"),
  col("expected_candidate_head_digest"),
  col("current_candidate_head_digest"),
];
const headNames = heads().map((column) => column.name);
const lifecycle = "status IN ('proposed','current','stale','revoked','superseded')";
const denominators = ["design_slice_denominator = 19", "design_artifact_denominator = 76"];

/** v1をprovisional historyとして保持したまま導入するPost-PO Design Freeze v2境界。 */
export const HARNESS_DB_DESIGN_FREEZE_V2_TABLES: TableDef[] = [
  {
    name: "design_freeze_v2_transition_operations",
    columns: [
      pk("operation_id"),
      col("idempotency_key"),
      col("request_digest"),
      col("payload_digest"),
      col("authority_epoch", "INTEGER"),
      ...heads(),
      col("full_preimage_json"),
      col("full_preimage_digest"),
      col("design_slice_denominator", "INTEGER"),
      col("design_artifact_denominator", "INTEGER"),
      col("review_identity"),
      col("review_runtime"),
      col("review_identity_digest"),
      col("remote_observation_state"),
      col("remote_observation_digest"),
      col("expires_at"),
      col("supersedes_receipt_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "authority_epoch > 0",
      ...denominators,
      "length(full_preimage_json) > 1",
      "length(review_identity) > 0",
      "length(review_runtime) > 0",
      lifecycle,
      ...digests([
        "request_digest",
        "payload_digest",
        ...headNames,
        "full_preimage_digest",
        "review_identity_digest",
        "remote_observation_digest",
        "supersedes_receipt_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_v2_authority_link_events",
    columns: [
      pk("event_id"),
      col("operation_id"),
      col("event_sequence", "INTEGER"),
      col("event_digest"),
      col("previous_event_digest"),
      col("po7_operation_id"),
      col("po7_event_digest"),
      col("authority_receipt_set_digest"),
      col("authority_epoch", "INTEGER"),
      ...heads(),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "event_sequence > 0",
      "authority_epoch > 0",
      "status IN ('current','stale','revoked','superseded')",
      ...digests([
        "event_digest",
        "previous_event_digest",
        "po7_event_digest",
        "authority_receipt_set_digest",
        ...headNames,
      ]),
    ],
  },
  {
    name: "design_freeze_v2_receipts",
    columns: [
      pk("receipt_id"),
      col("operation_id"),
      col("receipt_digest"),
      col("payload_digest"),
      col("full_preimage_json"),
      col("full_preimage_digest"),
      col("authority_receipt_set_digest"),
      col("critical_set_digest"),
      col("design_slice_denominator", "INTEGER"),
      col("design_artifact_denominator", "INTEGER"),
      col("review_identity"),
      col("review_runtime"),
      col("review_identity_digest"),
      col("repository_head_oid"),
      col("repository_tree_oid"),
      col("index_policy_digest"),
      ...heads(),
      col("remote_observation_state"),
      col("remote_observation_digest"),
      col("previous_receipt_digest"),
      col("supersedes_receipt_digest"),
      col("expires_at"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      ...denominators,
      "length(full_preimage_json) > 1",
      "length(repository_head_oid) >= 40",
      "length(repository_tree_oid) >= 40",
      "length(review_identity) > 0",
      "length(review_runtime) > 0",
      lifecycle,
      ...digests([
        "receipt_digest",
        "payload_digest",
        "full_preimage_digest",
        "authority_receipt_set_digest",
        "critical_set_digest",
        "review_identity_digest",
        "index_policy_digest",
        ...headNames,
        "remote_observation_digest",
        "previous_receipt_digest",
        "supersedes_receipt_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_v2_projections",
    columns: [
      pk("projection_id"),
      col("operation_id"),
      col("event_digest"),
      col("previous_event_digest"),
      col("freeze_receipt_digest"),
      col("design_slice_denominator", "INTEGER"),
      col("design_artifact_denominator", "INTEGER"),
      col("design_open_rows", "INTEGER"),
      ...heads(),
      col("projection_digest"),
      col("status"),
      col("projected_at"),
    ],
    checks: [
      ...denominators,
      "design_open_rows = 0",
      "status IN ('current','stale','revoked','superseded')",
      ...digests([
        "event_digest",
        "previous_event_digest",
        "freeze_receipt_digest",
        ...headNames,
        "projection_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_v2_progress_projections",
    columns: [
      pk("projection_id"),
      col("operation_id"),
      col("event_digest"),
      col("previous_event_digest"),
      col("freeze_receipt_digest"),
      col("design_slice_denominator", "INTEGER"),
      col("design_artifact_denominator", "INTEGER"),
      col("implementation_credit", "INTEGER"),
      col("verification_credit", "INTEGER"),
      col("coverage_credit", "INTEGER"),
      ...heads(),
      col("remote_observation_digest"),
      col("projection_digest"),
      col("status"),
      col("projected_at"),
    ],
    checks: [
      ...denominators,
      "implementation_credit = 0",
      "verification_credit = 0",
      "coverage_credit = 0",
      "status IN ('current','stale','revoked','superseded')",
      ...digests([
        "event_digest",
        "previous_event_digest",
        "freeze_receipt_digest",
        ...headNames,
        "remote_observation_digest",
        "projection_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_v2_l01_candidates",
    columns: [
      pk("candidate_id"),
      col("operation_id"),
      col("event_digest"),
      col("previous_event_digest"),
      col("candidate_digest"),
      col("freeze_receipt_digest"),
      col("authority_epoch", "INTEGER"),
      col("repository_head_oid"),
      col("repository_tree_oid"),
      ...heads(),
      col("local_state"),
      col("pair_state"),
      col("freeze_state"),
      col("counted", "INTEGER"),
      col("remote_creation_state"),
      col("remote_observation_digest"),
      col("expires_at"),
      col("supersedes_candidate_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "authority_epoch > 0",
      "length(repository_head_oid) >= 40",
      "length(repository_tree_oid) >= 40",
      "counted IN (0,1)",
      "local_state IN ('proposed','cancelled','expired','stale')",
      "pair_state IN ('pending_pair','cancelled','stale')",
      "freeze_state IN ('not_frozen','stale')",
      "remote_creation_state IN ('not_created','observed','created','quarantined')",
      "status IN ('proposed','current','stale','revoked','superseded','cancelled','expired')",
      ...digests([
        "event_digest",
        "previous_event_digest",
        "candidate_digest",
        "freeze_receipt_digest",
        ...headNames,
        "remote_observation_digest",
        "supersedes_candidate_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_v2_l01_handoffs",
    columns: [
      pk("handoff_id"),
      col("operation_id"),
      col("event_digest"),
      col("previous_event_digest"),
      col("handoff_digest"),
      col("candidate_digest"),
      col("freeze_receipt_digest"),
      col("authority_epoch", "INTEGER"),
      ...heads(),
      col("remote_observation_state"),
      col("remote_observation_digest"),
      col("expires_at"),
      col("supersedes_handoff_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "authority_epoch > 0",
      "remote_observation_state IN ('not_observed','observed','mismatched','quarantined')",
      "status IN ('proposed','current','stale','revoked','superseded','cancelled','expired')",
      ...digests([
        "event_digest",
        "previous_event_digest",
        "handoff_digest",
        "candidate_digest",
        "freeze_receipt_digest",
        ...headNames,
        "remote_observation_digest",
        "supersedes_handoff_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_v2_transition_outbox",
    columns: [
      pk("outbox_id"),
      col("operation_id"),
      col("event_digest"),
      col("payload_digest"),
      col("handoff_digest"),
      ...heads(),
      col("remote_observation_digest"),
      col("expires_at"),
      col("supersedes_outbox_digest"),
      col("delivery_class"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "delivery_class = 'local_reconcile_only'",
      "status IN ('pending','reconciled','stale','revoked','superseded','expired')",
      ...digests([
        "event_digest",
        "payload_digest",
        "handoff_digest",
        ...headNames,
        "remote_observation_digest",
        "supersedes_outbox_digest",
      ]),
    ],
  },
  {
    name: "design_freeze_v2_transition_terminal_receipts",
    columns: [
      pk("receipt_id"),
      col("operation_id"),
      col("payload_digest"),
      col("full_preimage_digest"),
      col("authority_event_digest"),
      col("freeze_receipt_digest"),
      col("freeze_projection_digest"),
      col("progress_projection_digest"),
      col("candidate_digest"),
      col("handoff_digest"),
      col("outbox_event_digest"),
      col("remote_observation_digest"),
      col("write_set_digest"),
      ...heads(),
      col("expires_at"),
      col("supersedes_receipt_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "status IN ('current','stale','revoked','superseded')",
      ...digests([
        "payload_digest",
        "full_preimage_digest",
        "authority_event_digest",
        "freeze_receipt_digest",
        "freeze_projection_digest",
        "progress_projection_digest",
        "candidate_digest",
        "handoff_digest",
        "outbox_event_digest",
        "remote_observation_digest",
        "write_set_digest",
        ...headNames,
        "supersedes_receipt_digest",
      ]),
    ],
  },
];
