import { col, pk } from "./harness-db-table-builders";
import type { TableDef } from "./harness-db-types";

export const HARNESS_DB_DESIGN_TABLES: TableDef[] = [
  {
    name: "design_declarations",
    columns: [
      pk("declaration_id"),
      col("defined_id"),
      col("declaration_kind"),
      col("title"),
      col("layer"),
      col("owner"),
      col("status"),
      col("source_path"),
      col("source"),
      col("indexed_at"),
    ],
  },
  {
    name: "design_references",
    columns: [
      pk("reference_id"),
      col("from_id"),
      col("to_id"),
      col("reference_kind"),
      col("status"),
      col("source_path"),
      col("source"),
      col("indexed_at"),
    ],
  },
  {
    name: "design_impact",
    columns: [
      pk("impact_id"),
      col("root_id"),
      col("impacted_id"),
      col("impact_kind"),
      col("direction"),
      col("status"),
      col("root_layer"),
      col("impacted_layer"),
      col("root_source_path"),
      col("impacted_source_path"),
      col("reference_id"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_current_location",
    columns: [
      pk("snapshot_id"),
      col("schema_version"),
      col("source_clock"),
      col("current_layer"),
      col("l12_layer"),
      col("current_status"),
      col("completion_boundary"),
      col("selected_drive_model"),
      col("drive_route_status"),
      col("default_drive_model"),
      col("roadmap_status"),
      col("plans_total", "INTEGER"),
      col("open_l7_plans", "INTEGER"),
      col("terminal_l14_plans", "INTEGER"),
      col("l12_done", "INTEGER"),
      col("l12_missing", "INTEGER"),
      col("l12_reverify", "INTEGER"),
      col("design_coverage_status"),
      col("acceptance_traceability_status"),
      col("zip_adoption_status"),
      col("tailoring_status"),
      col("operation_designed", "INTEGER"),
      col("operation_observed", "INTEGER"),
      col("operation_observed_gap", "INTEGER"),
      col("operation_missing", "INTEGER"),
      col("operation_reverify", "INTEGER"),
      col("findings_error", "INTEGER"),
      col("findings_warn", "INTEGER"),
      col("doc_dependency_count", "INTEGER"),
      col("implementation_dependency_count", "INTEGER"),
      col("source_command"),
      col("view_command"),
      col("snapshot_hash"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_drive_model_candidates",
    columns: [
      pk("candidate_id"),
      col("snapshot_id"),
      col("model"),
      col("rank", "INTEGER"),
      col("status"),
      col("selected", "INTEGER"),
      col("route_id"),
      col("trigger"),
      col("required_action"),
      col("command"),
      col("coverage_ids"),
      col("coverage_labels"),
      col("doc_dependencies"),
      col("implementation_dependencies"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_roadmap_current_actions",
    columns: [
      pk("action_id"),
      col("snapshot_id"),
      col("category"),
      col("status"),
      col("automation_class"),
      col("phase_action"),
      col("l12_layers"),
      col("coverage_ids"),
      col("coverage_labels"),
      col("command"),
      col("batch_command"),
      col("review_command"),
      col("evidence_patch_command"),
      col("evidence_probe_command"),
      col("evidence_materialize_command"),
      col("evidence_approval_draft_command"),
      col("evidence_apply_dry_run_command"),
      col("evidence_apply_execute_command"),
      col("evidence_apply_write_policy"),
      col("required_action"),
      col("doc_dependencies"),
      col("implementation_dependencies"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_zip_adoption_decisions",
    columns: [
      pk("adoption_id"),
      col("snapshot_id"),
      col("category"),
      col("label"),
      col("status"),
      col("source_package"),
      col("source_document"),
      col("declaration_ids"),
      col("source_paths"),
      col("doc_dependencies"),
      col("implementation_dependencies"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_tailoring_decisions",
    columns: [
      pk("tailoring_id"),
      col("snapshot_id"),
      col("category"),
      col("label"),
      col("detail_level"),
      col("status"),
      col("profile"),
      col("source_document"),
      col("declaration_ids"),
      col("source_paths"),
      col("doc_dependencies"),
      col("implementation_dependencies"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_vmodel_regression_guards",
    columns: [
      pk("guard_id"),
      col("snapshot_id"),
      col("status"),
      col("scope"),
      col("command"),
      col("protected_surface"),
      col("guard_count", "INTEGER"),
      col("required_action"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_vmodel_fit_blockers",
    columns: [
      pk("blocker_code"),
      col("snapshot_id"),
      col("status"),
      col("blocker_count", "INTEGER"),
      col("command"),
      col("required_action"),
      col("doc_dependencies"),
      col("implementation_dependencies"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_vmodel_handoff_summary",
    columns: [
      pk("summary_id"),
      col("snapshot_id"),
      col("status"),
      col("handoff_total", "INTEGER"),
      col("machine_pending", "INTEGER"),
      col("approval_pending", "INTEGER"),
      col("approval_required", "INTEGER"),
      col("approval_rejected", "INTEGER"),
      col("apply_ready", "INTEGER"),
      col("scope_match", "INTEGER"),
      col("scope_mismatch", "INTEGER"),
      col("scope_missing", "INTEGER"),
      col("valid_for_apply", "INTEGER"),
      col("invalid_for_apply", "INTEGER"),
      col("recovery_gate_status"),
      col("effective_phase"),
      col("approval_state"),
      col("approval_status"),
      col("scope_status"),
      col("decision_id"),
      col("materialize_status"),
      col("reviewed_candidate_count", "INTEGER"),
      col("command"),
      col("reason_codes"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_l12_layer_coverage",
    columns: [
      pk("coverage_row_id"),
      col("snapshot_id"),
      col("layer"),
      col("label"),
      col("status"),
      col("zip_source_binding_ids"),
      col("tailoring_rule_ids"),
      col("tailoring_detail_levels"),
      col("legacy_layers"),
      col("plan_ids"),
      col("design_ids"),
      col("test_design_ids"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "design_coverage_gate",
    columns: [
      pk("coverage_id"),
      col("snapshot_id"),
      col("l12_layer"),
      col("label"),
      col("status"),
      col("return_route"),
      col("zip_source_binding_ids"),
      col("tailoring_rule_ids"),
      col("tailoring_detail_levels"),
      col("required_kinds"),
      col("accepted_layers"),
      col("declaration_ids"),
      col("source_paths"),
      col("doc_dependencies"),
      col("implementation_dependencies"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_operation_scopes",
    columns: [
      pk("operation_scope_id"),
      col("snapshot_id"),
      col("scope"),
      col("label"),
      col("coverage_id"),
      col("coverage_label"),
      col("status"),
      col("design_ids"),
      col("observed_count", "INTEGER"),
      col("observed_gap", "INTEGER"),
      col("observation_sources"),
      col("evidence_tables"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "project_artifact_remap",
    columns: [
      pk("artifact_remap_id"),
      col("snapshot_id"),
      col("kind"),
      col("artifact_id"),
      col("source_path"),
      col("legacy_layer"),
      col("l12_layer"),
      col("coverage_id"),
      col("coverage_label"),
      col("status"),
      col("zip_source_binding_ids"),
      col("tailoring_rule_ids"),
      col("tailoring_detail_levels"),
      col("doc_dependencies"),
      col("implementation_dependencies"),
      col("reasons"),
      col("indexed_at"),
    ],
  },
  {
    name: "vmodel_zip_manifest",
    columns: [
      pk("manifest_id"),
      col("source_package"),
      col("archive_path"),
      col("present", "INTEGER"),
      col("ok", "INTEGER"),
      col("root_prefix"),
      col("entries_total", "INTEGER"),
      col("inventory_status"),
      col("required_sources_found", "INTEGER"),
      col("required_sources_total", "INTEGER"),
      col("by_extension"),
      col("findings"),
      col("evidence_tables"),
      col("snapshot_hash"),
      col("indexed_at"),
    ],
  },
  {
    name: "vmodel_zip_source_bindings",
    columns: [
      pk("binding_id"),
      col("manifest_id"),
      col("source_path"),
      col("source_category"),
      col("status"),
      col("source_present", "INTEGER"),
      col("actual_path"),
      col("l12_layers"),
      col("helix_surfaces"),
      col("evidence_tables"),
      col("required_action"),
      col("zip_source_binding_hash"),
      col("indexed_at"),
    ],
  },
  {
    name: "visualization_view_model",
    columns: [
      pk("view_model_id"),
      col("schema_version"),
      col("source_clock"),
      col("generated_from"),
      col("project_views"),
      col("harness_views"),
      col("source_fields"),
      col("warnings_count", "INTEGER"),
      col("snapshot_hash"),
      col("indexed_at"),
    ],
  },
  {
    name: "visualization_tree_view",
    columns: [
      pk("tree_view_id"),
      col("schema_version"),
      col("source_clock"),
      col("root_ids"),
      col("root_count", "INTEGER"),
      col("node_count", "INTEGER"),
      col("warnings_count", "INTEGER"),
      col("snapshot_hash"),
      col("indexed_at"),
    ],
  },
];
