import { pk } from "./harness-db-table-builders";
import type { ColumnType, TableDef } from "./harness-db-types";

const col = (name: string, type: ColumnType = "TEXT") => ({ name, type, notNull: true });

const digestChecks = (columns: string[]) =>
  columns.map((name) => `length(${name}) = 64 AND ${name} NOT GLOB '*[^0-9a-f]*'`);

export const HARNESS_DB_PO7_TABLES: TableDef[] = [
  {
    name: "po7_activation_operations",
    columns: [
      pk("operation_id"),
      col("idempotency_key"),
      col("request_digest"),
      col("payload_digest"),
      col("authority_epoch", "INTEGER"),
      col("previous_event_digest"),
      col("universal_packet_digest"),
      col("universal_source_set_digest"),
      col("vmodel_packet_digest"),
      col("vmodel_source_set_digest"),
      col("decision_table_digest"),
      col("authority_event_payload_digest"),
      col("actor_id"),
      col("actor_authority"),
      col("authority_evidence_digest"),
      col("answer_event_id"),
      col("answer_message_digest"),
      col("normalized_answer_digest"),
      col("observed_at"),
      col("status"),
    ],
    checks: [
      "authority_epoch >= 0",
      "status IN ('committing','active','stale','revoked','superseded')",
      ...digestChecks([
        "request_digest",
        "payload_digest",
        "universal_packet_digest",
        "universal_source_set_digest",
        "vmodel_packet_digest",
        "vmodel_source_set_digest",
        "decision_table_digest",
        "authority_event_payload_digest",
        "authority_evidence_digest",
        "answer_message_digest",
        "normalized_answer_digest",
      ]),
    ],
  },
  {
    name: "po7_group_option_receipts",
    columns: [
      pk("receipt_id"),
      col("operation_id"),
      col("decision_group_id"),
      col("selected_option_id"),
      col("option_decision_digest"),
      col("packet_digest"),
      col("source_revision_digest"),
      col("actor_id"),
      col("actor_authority"),
      col("authority_evidence_digest"),
      col("idempotency_key"),
      col("authority_epoch", "INTEGER"),
      col("previous_receipt_digest"),
      col("answer_event_id"),
      col("answer_message_digest"),
      col("normalized_answer_digest"),
      col("issued_at"),
      col("status"),
    ],
    checks: [
      "selected_option_id = 'A'",
      "authority_epoch > 0",
      "status IN ('active','stale','revoked','superseded')",
      ...digestChecks([
        "option_decision_digest",
        "packet_digest",
        "source_revision_digest",
        "authority_evidence_digest",
        "previous_receipt_digest",
        "answer_message_digest",
        "normalized_answer_digest",
      ]),
    ],
  },
  {
    name: "po7_question_answer_receipts",
    columns: [
      pk("receipt_id"),
      col("operation_id"),
      col("question_id"),
      col("queue_id"),
      col("decision_group_id"),
      col("selected_option_id"),
      col("answer_value"),
      col("answer_value_digest"),
      col("packet_digest"),
      col("source_revision_digest"),
      col("answer_event_id"),
      col("answer_message_digest"),
      col("normalized_answer_digest"),
      col("authority_epoch", "INTEGER"),
      col("issued_at"),
      col("status"),
    ],
    checks: [
      "selected_option_id = 'A'",
      "authority_epoch > 0",
      "status IN ('active','stale','revoked','superseded')",
      ...digestChecks([
        "answer_value_digest",
        "packet_digest",
        "source_revision_digest",
        "answer_message_digest",
        "normalized_answer_digest",
      ]),
    ],
  },
  {
    name: "po7_vmodel_authority_events",
    columns: [
      pk("event_id"),
      col("operation_id"),
      col("event_sequence", "INTEGER"),
      col("event_digest"),
      col("previous_event_digest"),
      col("packet_digest"),
      col("source_set_digest"),
      col("decision_table_digest"),
      col("actor_id"),
      col("actor_authority"),
      col("authority_evidence_digest"),
      col("co_authority_receipt_digests"),
      col("idempotency_key"),
      col("authority_epoch", "INTEGER"),
      col("answer_event_id"),
      col("answer_message_digest"),
      col("normalized_answer_digest"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "event_sequence > 0",
      "authority_epoch > 0",
      "status IN ('active','stale','revoked','superseded')",
      ...digestChecks([
        "event_digest",
        "packet_digest",
        "source_set_digest",
        "decision_table_digest",
        "authority_evidence_digest",
        "answer_message_digest",
        "normalized_answer_digest",
      ]),
    ],
  },
  {
    name: "po7_activation_projections",
    columns: [
      pk("projection_id"),
      col("operation_id"),
      col("authority_epoch", "INTEGER"),
      col("event_digest"),
      col("group_count", "INTEGER"),
      col("question_count", "INTEGER"),
      col("disposition_set_digest"),
      col("queue_set_digest"),
      col("freeze_blocker_status"),
      col("reason_digest"),
      col("status"),
      col("projected_at"),
    ],
    checks: [
      "authority_epoch > 0",
      "group_count IN (0,6)",
      "question_count IN (0,22)",
      "freeze_blocker_status IN ('closed','reopened')",
      "status IN ('active','stale','revoked','superseded')",
      ...digestChecks([
        "event_digest",
        "disposition_set_digest",
        "queue_set_digest",
        "reason_digest",
      ]),
    ],
  },
  {
    name: "po7_activation_terminal_receipts",
    columns: [
      pk("receipt_id"),
      col("operation_id"),
      col("payload_digest"),
      col("event_digest"),
      col("write_set_digest"),
      col("authority_epoch", "INTEGER"),
      col("status"),
      col("issued_at"),
    ],
    checks: [
      "authority_epoch > 0",
      "status IN ('active','stale','revoked','superseded')",
      ...digestChecks(["payload_digest", "event_digest", "write_set_digest"]),
    ],
  },
];
